/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Apr  4 10:38:16 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbEx5.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("    if signed: %0d * %0d DUT gave %0d", 37u);
static std::string const __str_literal_5("    if signed: %0d * %0d DUT gave %0d instead of %0d",
					 52u);
static std::string const __str_literal_3("    if unsigned: %0d * %0d DUT gave %0d", 39u);
static std::string const __str_literal_6("    if unsigned: %0d * %0d DUT gave %0d instead of %0d",
					 54u);
static std::string const __str_literal_4("FAILED case %0d", 15u);
static std::string const __str_literal_8("FAILED due to cycle limit", 25u);
static std::string const __str_literal_7("PASSED %0d test cases in %0d cycles", 35u);
static std::string const __str_literal_1("PASSED case %0d", 15u);


/* Constructor */
MOD_mkTbEx5::MOD_mkTbEx5(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_dut_a(simHdl, "dut_a", this, 8u),
    INST_dut_b(simHdl, "dut_b", this, 8u),
    INST_dut_i(simHdl, "dut_i", this, 4u, (tUInt8)9u, (tUInt8)0u),
    INST_dut_prod(simHdl, "dut_prod", this, 8u),
    INST_dut_tp(simHdl, "dut_tp", this, 8u),
    INST_tb_cycle(simHdl, "tb_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_tb_feed_count(simHdl, "tb_feed_count", this, 32u, 0u, (tUInt8)0u),
    INST_tb_operands_fifo(simHdl, "tb_operands_fifo", this, 16u, 4u, 1u, 0u),
    INST_tb_randomA_ignore(simHdl, "tb_randomA_ignore", this, 8u, (tUInt8)0u),
    INST_tb_randomA_initialized(simHdl, "tb_randomA_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomA_zaz(simHdl, "tb_randomA_zaz", this, 8u, (tUInt8)0u),
    INST_tb_randomB_ignore(simHdl, "tb_randomB_ignore", this, 8u, (tUInt8)0u),
    INST_tb_randomB_initialized(simHdl, "tb_randomB_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomB_zaz(simHdl, "tb_randomB_zaz", this, 8u, (tUInt8)0u),
    INST_tb_read_count(simHdl, "tb_read_count", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h1224(2863311530u),
    DEF_v__h834(2863311530u)
{
  symbol_count = 46u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbEx5::init_symbols_0()
{
  init_symbol(&symbols[0u], "_read__h162", SYM_DEF, &DEF__read__h162, 4u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_dut_mulStep", SYM_DEF, &DEF_CAN_FIRE_RL_dut_mulStep, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_tb_feed", SYM_DEF, &DEF_CAN_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_tb_read", SYM_DEF, &DEF_CAN_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[9u], "dut_a", SYM_MODULE, &INST_dut_a);
  init_symbol(&symbols[10u], "dut_b", SYM_MODULE, &INST_dut_b);
  init_symbol(&symbols[11u], "dut_i", SYM_MODULE, &INST_dut_i);
  init_symbol(&symbols[12u], "dut_prod", SYM_MODULE, &INST_dut_prod);
  init_symbol(&symbols[13u], "dut_tp", SYM_MODULE, &INST_dut_tp);
  init_symbol(&symbols[14u], "RL_dut_mulStep", SYM_RULE);
  init_symbol(&symbols[15u], "RL_tb_feed", SYM_RULE);
  init_symbol(&symbols[16u], "RL_tb_monitor_test", SYM_RULE);
  init_symbol(&symbols[17u], "RL_tb_randomA_every", SYM_RULE);
  init_symbol(&symbols[18u], "RL_tb_randomA_every_1", SYM_RULE);
  init_symbol(&symbols[19u], "RL_tb_randomB_every", SYM_RULE);
  init_symbol(&symbols[20u], "RL_tb_randomB_every_1", SYM_RULE);
  init_symbol(&symbols[21u], "RL_tb_read", SYM_RULE);
  init_symbol(&symbols[22u], "tb_cycle", SYM_MODULE, &INST_tb_cycle);
  init_symbol(&symbols[23u], "tb_feed_count", SYM_MODULE, &INST_tb_feed_count);
  init_symbol(&symbols[24u], "tb_operands_fifo", SYM_MODULE, &INST_tb_operands_fifo);
  init_symbol(&symbols[25u], "tb_randomA_ignore", SYM_MODULE, &INST_tb_randomA_ignore);
  init_symbol(&symbols[26u], "tb_randomA_initialized", SYM_MODULE, &INST_tb_randomA_initialized);
  init_symbol(&symbols[27u], "tb_randomA_zaz", SYM_MODULE, &INST_tb_randomA_zaz);
  init_symbol(&symbols[28u], "tb_randomB_ignore", SYM_MODULE, &INST_tb_randomB_ignore);
  init_symbol(&symbols[29u], "tb_randomB_initialized", SYM_MODULE, &INST_tb_randomB_initialized);
  init_symbol(&symbols[30u], "tb_randomB_zaz", SYM_MODULE, &INST_tb_randomB_zaz);
  init_symbol(&symbols[31u], "tb_read_count", SYM_MODULE, &INST_tb_read_count);
  init_symbol(&symbols[32u], "v__h1304", SYM_DEF, &DEF_v__h1304, 8u);
  init_symbol(&symbols[33u], "v__h915", SYM_DEF, &DEF_v__h915, 8u);
  init_symbol(&symbols[34u], "WILL_FIRE_RL_dut_mulStep", SYM_DEF, &DEF_WILL_FIRE_RL_dut_mulStep, 1u);
  init_symbol(&symbols[35u], "WILL_FIRE_RL_tb_feed", SYM_DEF, &DEF_WILL_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[36u],
	      "WILL_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[37u],
	      "WILL_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[38u],
	      "WILL_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[39u],
	      "WILL_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[40u],
	      "WILL_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[41u], "WILL_FIRE_RL_tb_read", SYM_DEF, &DEF_WILL_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[42u], "x__h1671", SYM_DEF, &DEF_x__h1671, 32u);
  init_symbol(&symbols[43u], "x__h2176", SYM_DEF, &DEF_x__h2176, 32u);
  init_symbol(&symbols[44u], "x_wget__h1167", SYM_DEF, &DEF_x_wget__h1167, 8u);
  init_symbol(&symbols[45u], "x_wget__h777", SYM_DEF, &DEF_x_wget__h777, 8u);
}


/* Rule actions */

void MOD_mkTbEx5::RL_dut_mulStep()
{
  tUInt8 DEF_x__h230;
  tUInt8 DEF_x__h194;
  tUInt8 DEF_x__h357;
  tUInt8 DEF_m__h180;
  tUInt8 DEF_dut_a_BITS_7_TO_1___h217;
  tUInt8 DEF_dut_prod_BITS_7_TO_1___h322;
  tUInt32 DEF__0_CONCAT_dut_tp_PLUS_0_CONCAT_IF_dut_a_BIT_0_T_ETC___d12;
  tUInt8 DEF_x__h336;
  tUInt8 DEF_dut_a___d3;
  tUInt8 DEF__read__h71;
  DEF_x__h272 = INST_dut_tp.METH_read();
  DEF__read__h97 = INST_dut_prod.METH_read();
  DEF__read__h71 = INST_dut_b.METH_read();
  DEF_dut_a___d3 = INST_dut_a.METH_read();
  DEF__read__h162 = INST_dut_i.METH_read();
  DEF_dut_prod_BITS_7_TO_1___h322 = (tUInt8)(DEF__read__h97 >> 1u);
  DEF_m__h180 = (tUInt8)((tUInt8)1u & DEF_dut_a___d3) ? DEF__read__h71 : (tUInt8)0u;
  DEF__0_CONCAT_dut_tp_PLUS_0_CONCAT_IF_dut_a_BIT_0_T_ETC___d12 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_x__h272))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_m__h180))));
  DEF_x__h336 = (tUInt8)(DEF__0_CONCAT_dut_tp_PLUS_0_CONCAT_IF_dut_a_BIT_0_T_ETC___d12 >> 1u);
  DEF_dut_a_BITS_7_TO_1___h217 = (tUInt8)(DEF_dut_a___d3 >> 1u);
  DEF_x__h357 = (tUInt8)15u & (DEF__read__h162 + (tUInt8)1u);
  DEF_x__h194 = (tUInt8)255u & DEF_dut_a_BITS_7_TO_1___h217;
  DEF_x__h230 = (tUInt8)255u & ((((tUInt8)((tUInt8)1u & DEF__0_CONCAT_dut_tp_PLUS_0_CONCAT_IF_dut_a_BIT_0_T_ETC___d12)) << 7u) | DEF_dut_prod_BITS_7_TO_1___h322);
  INST_dut_a.METH_write(DEF_x__h194);
  INST_dut_prod.METH_write(DEF_x__h230);
  INST_dut_tp.METH_write(DEF_x__h336);
  INST_dut_i.METH_write(DEF_x__h357);
}

void MOD_mkTbEx5::RL_tb_randomA_every()
{
  tUInt8 DEF_new_value__h876;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h834 = rand32();
  DEF_new_value__h876 = (tUInt8)((tUInt8)255u & DEF_v__h834);
  INST_tb_randomA_zaz.METH_wset(DEF_new_value__h876);
}

void MOD_mkTbEx5::RL_tb_randomA_every_1()
{
  DEF_x_wget__h777 = INST_tb_randomA_zaz.METH_wget();
  DEF_v__h915 = INST_tb_randomA_zaz.METH_whas() ? DEF_x_wget__h777 : (tUInt8)0u;
  INST_tb_randomA_ignore.METH_wset(DEF_v__h915);
}

void MOD_mkTbEx5::RL_tb_randomB_every()
{
  tUInt8 DEF_new_value__h1266;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1224 = rand32();
  DEF_new_value__h1266 = (tUInt8)((tUInt8)255u & DEF_v__h1224);
  INST_tb_randomB_zaz.METH_wset(DEF_new_value__h1266);
}

void MOD_mkTbEx5::RL_tb_randomB_every_1()
{
  DEF_x_wget__h1167 = INST_tb_randomB_zaz.METH_wget();
  DEF_v__h1304 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1167 : (tUInt8)0u;
  INST_tb_randomB_ignore.METH_wset(DEF_v__h1304);
}

void MOD_mkTbEx5::RL_tb_feed()
{
  tUInt32 DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d49;
  tUInt32 DEF_x__h1652;
  tUInt8 DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48;
  DEF_x__h1671 = INST_tb_feed_count.METH_read();
  DEF_x_wget__h1167 = INST_tb_randomB_zaz.METH_wget();
  DEF_x_wget__h777 = INST_tb_randomA_zaz.METH_wget();
  DEF_v__h1304 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1167 : (tUInt8)0u;
  DEF_v__h915 = INST_tb_randomA_zaz.METH_whas() ? DEF_x_wget__h777 : (tUInt8)0u;
  DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33 = DEF_v__h915 == (tUInt8)128u;
  DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34 = DEF_v__h1304 == (tUInt8)128u;
  DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48 = !DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33 && !DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34;
  DEF_x__h1652 = DEF_x__h1671 + 1u;
  DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d49 = 65535u & ((((tUInt32)(DEF_v__h915)) << 8u) | (tUInt32)(DEF_v__h1304));
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_tb_operands_fifo.METH_enq(DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d49);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_dut_a.METH_write(DEF_v__h915);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_dut_b.METH_write(DEF_v__h1304);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_dut_prod.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_dut_tp.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_dut_i.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA__ETC___d48)
    INST_tb_feed_count.METH_write(DEF_x__h1652);
}

void MOD_mkTbEx5::RL_tb_read()
{
  tUInt32 DEF_x__h2050;
  tUInt8 DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70;
  tUInt32 DEF_tb_operands_fifo_first____d59;
  tUInt8 DEF_b__h1691;
  tUInt8 DEF_signed_tb_operands_fifo_first__9_BITS_7_TO_0_2___d68;
  tUInt8 DEF_a__h1690;
  tUInt8 DEF_signed_tb_operands_fifo_first__9_BITS_15_TO_8_0___d67;
  tUInt32 DEF_v__h1721;
  tUInt32 DEF_signed_dut_tp_CONCAT_dut_prod_4_8___d69;
  tUInt32 DEF_expected__h1753;
  tUInt32 DEF_signed_0_CONCAT_tb_operands_fifo_first__9_BIT_ETC___d71;
  tUInt8 DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66;
  DEF_x__h2176 = INST_tb_read_count.METH_read();
  DEF_tb_operands_fifo_first____d59 = INST_tb_operands_fifo.METH_first();
  DEF_a__h1690 = (tUInt8)(DEF_tb_operands_fifo_first____d59 >> 8u);
  DEF_signed_tb_operands_fifo_first__9_BITS_15_TO_8_0___d67 = DEF_a__h1690;
  DEF_b__h1691 = (tUInt8)((tUInt8)255u & DEF_tb_operands_fifo_first____d59);
  DEF_expected__h1753 = (tUInt32)(65535u & ((65535u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_a__h1690))) * (65535u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_b__h1691)))));
  DEF_signed_0_CONCAT_tb_operands_fifo_first__9_BIT_ETC___d71 = DEF_expected__h1753;
  DEF_signed_tb_operands_fifo_first__9_BITS_7_TO_0_2___d68 = DEF_b__h1691;
  DEF_x__h272 = INST_dut_tp.METH_read();
  DEF__read__h97 = INST_dut_prod.METH_read();
  DEF_v__h1721 = 65535u & ((((tUInt32)(DEF_x__h272)) << 8u) | (tUInt32)(DEF__read__h97));
  DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66 = DEF_v__h1721 == DEF_expected__h1753;
  DEF_signed_dut_tp_CONCAT_dut_prod_4_8___d69 = DEF_v__h1721;
  DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70 = !DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66;
  DEF_x__h2050 = DEF_x__h2176 + 1u;
  INST_tb_operands_fifo.METH_deq();
  INST_dut_i.METH_write((tUInt8)9u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_x__h2176);
    if (DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66)
      dollar_display(sim_hdl,
		     this,
		     "s,-8,-8,-16",
		     &__str_literal_2,
		     DEF_signed_tb_operands_fifo_first__9_BITS_15_TO_8_0___d67,
		     DEF_signed_tb_operands_fifo_first__9_BITS_7_TO_0_2___d68,
		     DEF_signed_dut_tp_CONCAT_dut_prod_4_8___d69);
    if (DEF_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb_oper_ETC___d66)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,16",
		     &__str_literal_3,
		     DEF_a__h1690,
		     DEF_b__h1691,
		     DEF_v__h1721);
    if (DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_4, DEF_x__h2176);
    if (DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70)
      dollar_display(sim_hdl,
		     this,
		     "s,-8,-8,-16,-16",
		     &__str_literal_5,
		     DEF_signed_tb_operands_fifo_first__9_BITS_15_TO_8_0___d67,
		     DEF_signed_tb_operands_fifo_first__9_BITS_7_TO_0_2___d68,
		     DEF_signed_dut_tp_CONCAT_dut_prod_4_8___d69,
		     DEF_signed_0_CONCAT_tb_operands_fifo_first__9_BIT_ETC___d71);
    if (DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,16,16",
		     &__str_literal_6,
		     DEF_a__h1690,
		     DEF_b__h1691,
		     DEF_v__h1721,
		     DEF_expected__h1753);
    if (DEF_NOT_dut_tp_CONCAT_dut_prod_4_8_EQ_0_CONCAT_tb__ETC___d70)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_read_count.METH_write(DEF_x__h2050);
}

void MOD_mkTbEx5::RL_tb_monitor_test()
{
  tUInt32 DEF_x__h2423;
  tUInt8 DEF_tb_cycle_3_EQ_0___d74;
  tUInt8 DEF_tb_cycle_3_EQ_16384___d75;
  tUInt32 DEF_x__h2427;
  DEF_x__h2176 = INST_tb_read_count.METH_read();
  DEF_x__h2427 = INST_tb_cycle.METH_read();
  DEF_tb_cycle_3_EQ_16384___d75 = DEF_x__h2427 == 16384u;
  DEF_tb_cycle_3_EQ_0___d74 = DEF_x__h2427 == 0u;
  DEF_tb_read_count_2_EQ_128___d53 = DEF_x__h2176 == 128u;
  DEF_x__h2423 = DEF_x__h2427 + 1u;
  if (DEF_tb_cycle_3_EQ_0___d74)
    INST_tb_randomA_initialized.METH_write((tUInt8)1u);
  if (DEF_tb_cycle_3_EQ_0___d74)
    INST_tb_randomB_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_tb_read_count_2_EQ_128___d53)
      dollar_display(sim_hdl, this, "s,32,32", &__str_literal_7, DEF_x__h2176, DEF_x__h2427);
    if (DEF_tb_read_count_2_EQ_128___d53)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_tb_cycle_3_EQ_16384___d75)
      dollar_display(sim_hdl, this, "s", &__str_literal_8);
    if (DEF_tb_cycle_3_EQ_16384___d75)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_cycle.METH_write(DEF_x__h2423);
}


/* Methods */


/* Reset routines */

void MOD_mkTbEx5::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_tb_read_count.reset_RST(ARG_rst_in);
  INST_tb_randomB_initialized.reset_RST(ARG_rst_in);
  INST_tb_randomA_initialized.reset_RST(ARG_rst_in);
  INST_tb_operands_fifo.reset_RST(ARG_rst_in);
  INST_tb_feed_count.reset_RST(ARG_rst_in);
  INST_tb_cycle.reset_RST(ARG_rst_in);
  INST_dut_i.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbEx5::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbEx5::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_dut_a.dump_state(indent + 2u);
  INST_dut_b.dump_state(indent + 2u);
  INST_dut_i.dump_state(indent + 2u);
  INST_dut_prod.dump_state(indent + 2u);
  INST_dut_tp.dump_state(indent + 2u);
  INST_tb_cycle.dump_state(indent + 2u);
  INST_tb_feed_count.dump_state(indent + 2u);
  INST_tb_operands_fifo.dump_state(indent + 2u);
  INST_tb_randomA_ignore.dump_state(indent + 2u);
  INST_tb_randomA_initialized.dump_state(indent + 2u);
  INST_tb_randomA_zaz.dump_state(indent + 2u);
  INST_tb_randomB_ignore.dump_state(indent + 2u);
  INST_tb_randomB_initialized.dump_state(indent + 2u);
  INST_tb_randomB_zaz.dump_state(indent + 2u);
  INST_tb_read_count.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbEx5::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 46u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_dut_mulStep", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_dut_mulStep", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h162", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h97", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_read_count_2_EQ_128___d53", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1224", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1304", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h834", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h915", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1671", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2176", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h272", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1167", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h777", 8u);
  num = INST_dut_a.dump_VCD_defs(num);
  num = INST_dut_b.dump_VCD_defs(num);
  num = INST_dut_i.dump_VCD_defs(num);
  num = INST_dut_prod.dump_VCD_defs(num);
  num = INST_dut_tp.dump_VCD_defs(num);
  num = INST_tb_cycle.dump_VCD_defs(num);
  num = INST_tb_feed_count.dump_VCD_defs(num);
  num = INST_tb_operands_fifo.dump_VCD_defs(num);
  num = INST_tb_randomA_ignore.dump_VCD_defs(num);
  num = INST_tb_randomA_initialized.dump_VCD_defs(num);
  num = INST_tb_randomA_zaz.dump_VCD_defs(num);
  num = INST_tb_randomB_ignore.dump_VCD_defs(num);
  num = INST_tb_randomB_initialized.dump_VCD_defs(num);
  num = INST_tb_randomB_zaz.dump_VCD_defs(num);
  num = INST_tb_read_count.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbEx5::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx5 &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbEx5::vcd_defs(tVCDDumpType dt, MOD_mkTbEx5 &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_dut_mulStep) != DEF_CAN_FIRE_RL_dut_mulStep)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_dut_mulStep, 1u);
	backing.DEF_CAN_FIRE_RL_dut_mulStep = DEF_CAN_FIRE_RL_dut_mulStep;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_feed) != DEF_CAN_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_feed, 1u);
	backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_monitor_test) != DEF_CAN_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every) != DEF_CAN_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every_1) != DEF_CAN_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every) != DEF_CAN_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every_1) != DEF_CAN_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_read) != DEF_CAN_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_read, 1u);
	backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33) != DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33, 1u);
	backing.DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33 = DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34) != DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34, 1u);
	backing.DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34 = DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_dut_mulStep) != DEF_WILL_FIRE_RL_dut_mulStep)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_dut_mulStep, 1u);
	backing.DEF_WILL_FIRE_RL_dut_mulStep = DEF_WILL_FIRE_RL_dut_mulStep;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_feed) != DEF_WILL_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_feed, 1u);
	backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_monitor_test) != DEF_WILL_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every) != DEF_WILL_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every_1) != DEF_WILL_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every) != DEF_WILL_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every_1) != DEF_WILL_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_read) != DEF_WILL_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_read, 1u);
	backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF__read__h162) != DEF__read__h162)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h162, 4u);
	backing.DEF__read__h162 = DEF__read__h162;
      }
      ++num;
      if ((backing.DEF__read__h97) != DEF__read__h97)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h97, 8u);
	backing.DEF__read__h97 = DEF__read__h97;
      }
      ++num;
      if ((backing.DEF_tb_read_count_2_EQ_128___d53) != DEF_tb_read_count_2_EQ_128___d53)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_read_count_2_EQ_128___d53, 1u);
	backing.DEF_tb_read_count_2_EQ_128___d53 = DEF_tb_read_count_2_EQ_128___d53;
      }
      ++num;
      if ((backing.DEF_v__h1224) != DEF_v__h1224)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1224, 32u);
	backing.DEF_v__h1224 = DEF_v__h1224;
      }
      ++num;
      if ((backing.DEF_v__h1304) != DEF_v__h1304)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1304, 8u);
	backing.DEF_v__h1304 = DEF_v__h1304;
      }
      ++num;
      if ((backing.DEF_v__h834) != DEF_v__h834)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h834, 32u);
	backing.DEF_v__h834 = DEF_v__h834;
      }
      ++num;
      if ((backing.DEF_v__h915) != DEF_v__h915)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h915, 8u);
	backing.DEF_v__h915 = DEF_v__h915;
      }
      ++num;
      if ((backing.DEF_x__h1671) != DEF_x__h1671)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1671, 32u);
	backing.DEF_x__h1671 = DEF_x__h1671;
      }
      ++num;
      if ((backing.DEF_x__h2176) != DEF_x__h2176)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2176, 32u);
	backing.DEF_x__h2176 = DEF_x__h2176;
      }
      ++num;
      if ((backing.DEF_x__h272) != DEF_x__h272)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h272, 8u);
	backing.DEF_x__h272 = DEF_x__h272;
      }
      ++num;
      if ((backing.DEF_x_wget__h1167) != DEF_x_wget__h1167)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1167, 8u);
	backing.DEF_x_wget__h1167 = DEF_x_wget__h1167;
      }
      ++num;
      if ((backing.DEF_x_wget__h777) != DEF_x_wget__h777)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h777, 8u);
	backing.DEF_x_wget__h777 = DEF_x_wget__h777;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_dut_mulStep, 1u);
      backing.DEF_CAN_FIRE_RL_dut_mulStep = DEF_CAN_FIRE_RL_dut_mulStep;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_feed, 1u);
      backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_read, 1u);
      backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33, 1u);
      backing.DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33 = DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d33;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34, 1u);
      backing.DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34 = DEF_IF_tb_randomB_zaz_whas__0_THEN_tb_randomB_zaz__ETC___d34;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_dut_mulStep, 1u);
      backing.DEF_WILL_FIRE_RL_dut_mulStep = DEF_WILL_FIRE_RL_dut_mulStep;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_feed, 1u);
      backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_read, 1u);
      backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF__read__h162, 4u);
      backing.DEF__read__h162 = DEF__read__h162;
      vcd_write_val(sim_hdl, num++, DEF__read__h97, 8u);
      backing.DEF__read__h97 = DEF__read__h97;
      vcd_write_val(sim_hdl, num++, DEF_tb_read_count_2_EQ_128___d53, 1u);
      backing.DEF_tb_read_count_2_EQ_128___d53 = DEF_tb_read_count_2_EQ_128___d53;
      vcd_write_val(sim_hdl, num++, DEF_v__h1224, 32u);
      backing.DEF_v__h1224 = DEF_v__h1224;
      vcd_write_val(sim_hdl, num++, DEF_v__h1304, 8u);
      backing.DEF_v__h1304 = DEF_v__h1304;
      vcd_write_val(sim_hdl, num++, DEF_v__h834, 32u);
      backing.DEF_v__h834 = DEF_v__h834;
      vcd_write_val(sim_hdl, num++, DEF_v__h915, 8u);
      backing.DEF_v__h915 = DEF_v__h915;
      vcd_write_val(sim_hdl, num++, DEF_x__h1671, 32u);
      backing.DEF_x__h1671 = DEF_x__h1671;
      vcd_write_val(sim_hdl, num++, DEF_x__h2176, 32u);
      backing.DEF_x__h2176 = DEF_x__h2176;
      vcd_write_val(sim_hdl, num++, DEF_x__h272, 8u);
      backing.DEF_x__h272 = DEF_x__h272;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1167, 8u);
      backing.DEF_x_wget__h1167 = DEF_x_wget__h1167;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h777, 8u);
      backing.DEF_x_wget__h777 = DEF_x_wget__h777;
    }
}

void MOD_mkTbEx5::vcd_prims(tVCDDumpType dt, MOD_mkTbEx5 &backing)
{
  INST_dut_a.dump_VCD(dt, backing.INST_dut_a);
  INST_dut_b.dump_VCD(dt, backing.INST_dut_b);
  INST_dut_i.dump_VCD(dt, backing.INST_dut_i);
  INST_dut_prod.dump_VCD(dt, backing.INST_dut_prod);
  INST_dut_tp.dump_VCD(dt, backing.INST_dut_tp);
  INST_tb_cycle.dump_VCD(dt, backing.INST_tb_cycle);
  INST_tb_feed_count.dump_VCD(dt, backing.INST_tb_feed_count);
  INST_tb_operands_fifo.dump_VCD(dt, backing.INST_tb_operands_fifo);
  INST_tb_randomA_ignore.dump_VCD(dt, backing.INST_tb_randomA_ignore);
  INST_tb_randomA_initialized.dump_VCD(dt, backing.INST_tb_randomA_initialized);
  INST_tb_randomA_zaz.dump_VCD(dt, backing.INST_tb_randomA_zaz);
  INST_tb_randomB_ignore.dump_VCD(dt, backing.INST_tb_randomB_ignore);
  INST_tb_randomB_initialized.dump_VCD(dt, backing.INST_tb_randomB_initialized);
  INST_tb_randomB_zaz.dump_VCD(dt, backing.INST_tb_randomB_zaz);
  INST_tb_read_count.dump_VCD(dt, backing.INST_tb_read_count);
}
