/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr  5 14:20:32 CST 2026
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbEx7a_h__
#define __mkTbEx7a_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbEx7a module */
class MOD_mkTbEx7a : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_dut_i;
  MOD_Reg<tUWide> INST_dut_m_neg;
  MOD_Reg<tUWide> INST_dut_m_pos;
  MOD_Reg<tUWide> INST_dut_p;
  MOD_Reg<tUInt32> INST_tb_cycle;
  MOD_Reg<tUInt32> INST_tb_feed_count;
  MOD_Fifo<tUInt64> INST_tb_operands_fifo;
  MOD_Wire<tUInt32> INST_tb_randomA_ignore;
  MOD_Reg<tUInt8> INST_tb_randomA_initialized;
  MOD_Wire<tUInt32> INST_tb_randomA_zaz;
  MOD_Wire<tUInt32> INST_tb_randomB_ignore;
  MOD_Reg<tUInt8> INST_tb_randomB_initialized;
  MOD_Wire<tUInt32> INST_tb_randomB_zaz;
  MOD_Reg<tUInt32> INST_tb_read_count;
 
 /* Constructor */
 public:
  MOD_mkTbEx7a(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_CAN_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_WILL_FIRE_RL_tb_read;
  tUInt8 DEF_CAN_FIRE_RL_tb_read;
  tUInt8 DEF_WILL_FIRE_RL_tb_feed;
  tUInt8 DEF_CAN_FIRE_RL_tb_feed;
  tUInt8 DEF_WILL_FIRE_RL_dut_mul_step;
  tUInt8 DEF_CAN_FIRE_RL_dut_mul_step;
  tUInt32 DEF_x__h2388;
  tUInt32 DEF_x__h1849;
  tUInt32 DEF_x_wget__h1309;
  tUInt32 DEF_x_wget__h882;
  tUInt8 DEF__read__h139;
  tUInt8 DEF_tb_randomA_zaz_whas____d20;
  tUInt8 DEF_dut_i_EQ_32___d56;
  tUInt32 DEF_v__h1057;
  tUInt32 DEF_v__h1483;
  tUInt8 DEF_tb_read_count_3_EQ_128___d54;
  tUInt8 DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29;
  tUInt8 DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30;
 
 /* Local definitions */
 private:
  tUInt32 DEF_new_value__h1445;
  tUInt32 DEF_new_value__h1018;
  tUWide DEF_dut_p__h1960;
  tUWide DEF_y__h270;
  tUWide DEF_y__h358;
  tUWide DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66;
  tUWide DEF_x__h344;
  tUWide DEF_x__h389;
  tUWide DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15;
  tUWide DEF_x__h241;
  tUWide DEF_x__h251;
  tUWide DEF_x__h354;
  tUWide DEF_x__h1808;
  tUWide DEF_x__h1793;
  tUWide DEF_x__h1768;
 
 /* Rules */
 public:
  void RL_dut_mul_step();
  void RL_tb_randomA_every();
  void RL_tb_randomA_every_1();
  void RL_tb_randomB_every();
  void RL_tb_randomB_every_1();
  void RL_tb_feed();
  void RL_tb_read();
  void RL_tb_monitor_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx7a &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbEx7a &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbEx7a &backing);
};

#endif /* ifndef __mkTbEx7a_h__ */
