/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr  5 14:20:33 CST 2026
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbEx9a_h__
#define __mkTbEx9a_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbEx9a module */
class MOD_mkTbEx9a : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_dut_i;
  MOD_Reg<tUWide> INST_dut_m_neg;
  MOD_Reg<tUWide> INST_dut_m_pos;
  MOD_Reg<tUWide> INST_dut_p;
  MOD_Reg<tUInt32> INST_tb_cycle;
  MOD_Reg<tUInt32> INST_tb_feed_count;
  MOD_Fifo<tUInt64> INST_tb_operands_fifo;
  MOD_Wire<tUInt32> INST_tb_randomA_ignore;
  MOD_Reg<tUInt8> INST_tb_randomA_initialized;
  MOD_Wire<tUInt32> INST_tb_randomA_zaz;
  MOD_Wire<tUInt32> INST_tb_randomB_ignore;
  MOD_Reg<tUInt8> INST_tb_randomB_initialized;
  MOD_Wire<tUInt32> INST_tb_randomB_zaz;
  MOD_Reg<tUInt32> INST_tb_read_count;
 
 /* Constructor */
 public:
  MOD_mkTbEx9a(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_CAN_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_WILL_FIRE_RL_tb_read;
  tUInt8 DEF_CAN_FIRE_RL_tb_read;
  tUInt8 DEF_WILL_FIRE_RL_tb_feed;
  tUInt8 DEF_CAN_FIRE_RL_tb_feed;
  tUInt8 DEF_WILL_FIRE_RL_dut_mul_step;
  tUInt8 DEF_CAN_FIRE_RL_dut_mul_step;
  tUInt32 DEF_x__h2833;
  tUInt32 DEF_x__h2294;
  tUInt32 DEF_x_wget__h1745;
  tUInt32 DEF_x_wget__h1318;
  tUInt8 DEF__read__h142;
  tUInt8 DEF_dut_i_EQ_16___d75;
  tUInt32 DEF_v__h1493;
  tUInt32 DEF_v__h1919;
  tUInt8 DEF_tb_read_count_2_EQ_128___d73;
  tUInt8 DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48;
  tUInt8 DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49;
 
 /* Local definitions */
 private:
  tUWide DEF_x__h462;
  tUInt32 DEF_new_value__h1881;
  tUInt32 DEF_new_value__h1454;
  tUWide DEF_dut_p__h2405;
  tUWide DEF_y__h332;
  tUWide DEF_y__h466;
  tUWide DEF_dut_m_pos_BITS_64_TO_0___h614;
  tUWide DEF_dut_m_neg_BITS_64_TO_0___h751;
  tUWide DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85;
  tUWide DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34;
  tUWide DEF_x__h303;
  tUWide DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33;
  tUWide DEF_x__h452;
  tUWide DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32;
  tUWide DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31;
  tUWide DEF_x__h733;
  tUWide DEF_x__h781;
  tUWide DEF_x__h586;
  tUWide DEF_x__h743;
  tUWide DEF_x__h596;
  tUWide DEF_x__h313;
  tUWide DEF_y__h747;
  tUWide DEF_y__h600;
  tUWide DEF_x__h2253;
  tUWide DEF_x__h2237;
  tUWide DEF_x__h2206;
 
 /* Rules */
 public:
  void RL_dut_mul_step();
  void RL_tb_randomA_every();
  void RL_tb_randomA_every_1();
  void RL_tb_randomB_every();
  void RL_tb_randomB_every_1();
  void RL_tb_feed();
  void RL_tb_read();
  void RL_tb_monitor_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx9a &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbEx9a &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbEx9a &backing);
};

#endif /* ifndef __mkTbEx9a_h__ */
