/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr  5 14:20:33 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbEx9a.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("    if signed: %0d * %0d DUT gave %0d", 37u);
static std::string const __str_literal_5("    if signed: %0d * %0d DUT gave %0d instead of %0d",
					 52u);
static std::string const __str_literal_3("    if unsigned: %0d * %0d DUT gave %0d", 39u);
static std::string const __str_literal_6("    if unsigned: %0d * %0d DUT gave %0d instead of %0d",
					 54u);
static std::string const __str_literal_4("FAILED case %0d", 15u);
static std::string const __str_literal_8("FAILED due to cycle limit", 25u);
static std::string const __str_literal_7("PASSED %0d test cases in %0d cycles", 35u);
static std::string const __str_literal_1("PASSED case %0d", 15u);


/* Constructor */
MOD_mkTbEx9a::MOD_mkTbEx9a(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_dut_i(simHdl, "dut_i", this, 6u, (tUInt8)17u, (tUInt8)0u),
    INST_dut_m_neg(simHdl, "dut_m_neg", this, 66u),
    INST_dut_m_pos(simHdl, "dut_m_pos", this, 66u),
    INST_dut_p(simHdl, "dut_p", this, 66u),
    INST_tb_cycle(simHdl, "tb_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_tb_feed_count(simHdl, "tb_feed_count", this, 32u, 0u, (tUInt8)0u),
    INST_tb_operands_fifo(simHdl, "tb_operands_fifo", this, 64u, 4u, 1u, 0u),
    INST_tb_randomA_ignore(simHdl, "tb_randomA_ignore", this, 32u, (tUInt8)0u),
    INST_tb_randomA_initialized(simHdl, "tb_randomA_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomA_zaz(simHdl, "tb_randomA_zaz", this, 32u, (tUInt8)0u),
    INST_tb_randomB_ignore(simHdl, "tb_randomB_ignore", this, 32u, (tUInt8)0u),
    INST_tb_randomB_initialized(simHdl, "tb_randomB_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomB_zaz(simHdl, "tb_randomB_zaz", this, 32u, (tUInt8)0u),
    INST_tb_read_count(simHdl, "tb_read_count", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_x__h462(66u),
    DEF_new_value__h1881(2863311530u),
    DEF_new_value__h1454(2863311530u),
    DEF_dut_p__h2405(66u),
    DEF_y__h332(66u),
    DEF_y__h466(66u),
    DEF_dut_m_pos_BITS_64_TO_0___h614(65u),
    DEF_dut_m_neg_BITS_64_TO_0___h751(65u),
    DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85(128u),
    DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34(66u),
    DEF_x__h303(66u),
    DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33(66u),
    DEF_x__h452(66u),
    DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32(66u),
    DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31(66u),
    DEF_x__h733(66u),
    DEF_x__h781(66u),
    DEF_x__h586(66u),
    DEF_x__h743(66u),
    DEF_x__h596(66u),
    DEF_x__h313(66u),
    DEF_y__h747(66u),
    DEF_y__h600(66u),
    DEF_x__h2253(66u),
    DEF_x__h2237(66u),
    DEF_x__h2206(66u)
{
  symbol_count = 45u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbEx9a::init_symbols_0()
{
  init_symbol(&symbols[0u], "_read__h142", SYM_DEF, &DEF__read__h142, 6u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_dut_mul_step", SYM_DEF, &DEF_CAN_FIRE_RL_dut_mul_step, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_tb_feed", SYM_DEF, &DEF_CAN_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_tb_read", SYM_DEF, &DEF_CAN_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[9u], "dut_i", SYM_MODULE, &INST_dut_i);
  init_symbol(&symbols[10u], "dut_m_neg", SYM_MODULE, &INST_dut_m_neg);
  init_symbol(&symbols[11u], "dut_m_pos", SYM_MODULE, &INST_dut_m_pos);
  init_symbol(&symbols[12u], "dut_p", SYM_MODULE, &INST_dut_p);
  init_symbol(&symbols[13u], "RL_dut_mul_step", SYM_RULE);
  init_symbol(&symbols[14u], "RL_tb_feed", SYM_RULE);
  init_symbol(&symbols[15u], "RL_tb_monitor_test", SYM_RULE);
  init_symbol(&symbols[16u], "RL_tb_randomA_every", SYM_RULE);
  init_symbol(&symbols[17u], "RL_tb_randomA_every_1", SYM_RULE);
  init_symbol(&symbols[18u], "RL_tb_randomB_every", SYM_RULE);
  init_symbol(&symbols[19u], "RL_tb_randomB_every_1", SYM_RULE);
  init_symbol(&symbols[20u], "RL_tb_read", SYM_RULE);
  init_symbol(&symbols[21u], "tb_cycle", SYM_MODULE, &INST_tb_cycle);
  init_symbol(&symbols[22u], "tb_feed_count", SYM_MODULE, &INST_tb_feed_count);
  init_symbol(&symbols[23u], "tb_operands_fifo", SYM_MODULE, &INST_tb_operands_fifo);
  init_symbol(&symbols[24u], "tb_randomA_ignore", SYM_MODULE, &INST_tb_randomA_ignore);
  init_symbol(&symbols[25u], "tb_randomA_initialized", SYM_MODULE, &INST_tb_randomA_initialized);
  init_symbol(&symbols[26u], "tb_randomA_zaz", SYM_MODULE, &INST_tb_randomA_zaz);
  init_symbol(&symbols[27u], "tb_randomB_ignore", SYM_MODULE, &INST_tb_randomB_ignore);
  init_symbol(&symbols[28u], "tb_randomB_initialized", SYM_MODULE, &INST_tb_randomB_initialized);
  init_symbol(&symbols[29u], "tb_randomB_zaz", SYM_MODULE, &INST_tb_randomB_zaz);
  init_symbol(&symbols[30u], "tb_read_count", SYM_MODULE, &INST_tb_read_count);
  init_symbol(&symbols[31u], "v__h1493", SYM_DEF, &DEF_v__h1493, 32u);
  init_symbol(&symbols[32u], "v__h1919", SYM_DEF, &DEF_v__h1919, 32u);
  init_symbol(&symbols[33u],
	      "WILL_FIRE_RL_dut_mul_step",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_dut_mul_step,
	      1u);
  init_symbol(&symbols[34u], "WILL_FIRE_RL_tb_feed", SYM_DEF, &DEF_WILL_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[35u],
	      "WILL_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[36u],
	      "WILL_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[37u],
	      "WILL_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[38u],
	      "WILL_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[39u],
	      "WILL_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[40u], "WILL_FIRE_RL_tb_read", SYM_DEF, &DEF_WILL_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[41u], "x__h2294", SYM_DEF, &DEF_x__h2294, 32u);
  init_symbol(&symbols[42u], "x__h2833", SYM_DEF, &DEF_x__h2833, 32u);
  init_symbol(&symbols[43u], "x_wget__h1318", SYM_DEF, &DEF_x_wget__h1318, 32u);
  init_symbol(&symbols[44u], "x_wget__h1745", SYM_DEF, &DEF_x_wget__h1745, 32u);
}


/* Rule actions */

void MOD_mkTbEx9a::RL_dut_mul_step()
{
  tUInt8 DEF_x__h898;
  tUInt8 DEF_y__h491;
  tUInt8 DEF_x__h490;
  tUInt8 DEF_x__h660;
  tUInt8 DEF_y__h638;
  tUInt8 DEF_y__h662;
  tUInt8 DEF_x__h661;
  tUInt8 DEF_x__h637;
  tUInt8 DEF_y__h358;
  DEF_dut_p__h2405 = INST_dut_p.METH_read();
  DEF_y__h332 = INST_dut_m_pos.METH_read();
  DEF_y__h466 = INST_dut_m_neg.METH_read();
  wop_add(DEF_dut_p__h2405, DEF_y__h466, DEF_x__h462);
  DEF__read__h142 = INST_dut_i.METH_read();
  wop_primExtractWide(65u, 66u, DEF_y__h332, 32u, 64u, 32u, 0u, DEF_dut_m_pos_BITS_64_TO_0___h614);
  wop_primExtractWide(65u, 66u, DEF_y__h466, 32u, 64u, 32u, 0u, DEF_dut_m_neg_BITS_64_TO_0___h751);
  DEF_x__h637 = DEF_dut_p__h2405.get_bits_in_word8(0u, 2u, 1u);
  DEF_x__h661 = DEF_dut_p__h2405.get_bits_in_word8(0u, 1u, 1u);
  DEF_y__h662 = DEF_dut_p__h2405.get_bits_in_word8(0u, 0u, 1u);
  DEF_y__h358 = DEF_x__h661 ^ DEF_y__h662;
  wop_primShiftRAWide(66u, 66u, DEF_x__h462, 32u, 2u, DEF_x__h452);
  wop_primShiftRAWide(66u, 66u, DEF_dut_p__h2405, 32u, 2u, DEF_x__h781);
  DEF_x__h660 = DEF_x__h661 | DEF_y__h662;
  DEF_y__h638 = (tUInt8)1u & ~DEF_x__h660;
  DEF_x__h490 = (tUInt8)1u & ~DEF_x__h637;
  wop_add(DEF_dut_p__h2405, DEF_y__h332, DEF_x__h313);
  wop_primShiftRAWide(66u, 66u, DEF_x__h313, 32u, 2u, DEF_x__h303);
  DEF_y__h491 = DEF_x__h661 & DEF_y__h662;
  DEF_y__h747.set_bits_in_word(primExtract8(2u,
					    65u,
					    DEF_dut_m_neg_BITS_64_TO_0___h751,
					    32u,
					    64u,
					    32u,
					    63u),
			       2u,
			       0u,
			       2u).set_whole_word(primExtract32(32u,
								65u,
								DEF_dut_m_neg_BITS_64_TO_0___h751,
								32u,
								62u,
								32u,
								31u),
						  1u).set_whole_word((DEF_dut_m_neg_BITS_64_TO_0___h751.get_bits_in_word32(0u,
															   0u,
															   31u) << 1u) | (tUInt32)((tUInt8)0u),
								     0u);
  wop_add(DEF_dut_p__h2405, DEF_y__h747, DEF_x__h743);
  wop_primShiftRAWide(66u, 66u, DEF_x__h743, 32u, 2u, DEF_x__h733);
  DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31 = DEF_x__h637 & DEF_y__h638 ? DEF_x__h733 : DEF_x__h781;
  DEF_y__h600.set_bits_in_word(primExtract8(2u,
					    65u,
					    DEF_dut_m_pos_BITS_64_TO_0___h614,
					    32u,
					    64u,
					    32u,
					    63u),
			       2u,
			       0u,
			       2u).set_whole_word(primExtract32(32u,
								65u,
								DEF_dut_m_pos_BITS_64_TO_0___h614,
								32u,
								62u,
								32u,
								31u),
						  1u).set_whole_word((DEF_dut_m_pos_BITS_64_TO_0___h614.get_bits_in_word32(0u,
															   0u,
															   31u) << 1u) | (tUInt32)((tUInt8)0u),
								     0u);
  wop_add(DEF_dut_p__h2405, DEF_y__h600, DEF_x__h596);
  wop_primShiftRAWide(66u, 66u, DEF_x__h596, 32u, 2u, DEF_x__h586);
  DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32 = DEF_x__h490 & DEF_y__h491 ? DEF_x__h586 : DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31;
  DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33 = DEF_x__h637 & DEF_y__h358 ? DEF_x__h452 : DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32;
  DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34 = DEF_x__h490 & DEF_y__h358 ? DEF_x__h303 : DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33;
  DEF_x__h898 = (tUInt8)63u & (DEF__read__h142 + (tUInt8)1u);
  INST_dut_p.METH_write(DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34);
  INST_dut_i.METH_write(DEF_x__h898);
}

void MOD_mkTbEx9a::RL_tb_randomA_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h1454 = rand32();
  }
  INST_tb_randomA_zaz.METH_wset(DEF_new_value__h1454);
}

void MOD_mkTbEx9a::RL_tb_randomA_every_1()
{
  DEF_x_wget__h1318 = INST_tb_randomA_zaz.METH_wget();
  DEF_v__h1493 = INST_tb_randomA_zaz.METH_whas() ? DEF_x_wget__h1318 : 0u;
  INST_tb_randomA_ignore.METH_wset(DEF_v__h1493);
}

void MOD_mkTbEx9a::RL_tb_randomB_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h1881 = rand32();
  }
  INST_tb_randomB_zaz.METH_wset(DEF_new_value__h1881);
}

void MOD_mkTbEx9a::RL_tb_randomB_every_1()
{
  DEF_x_wget__h1745 = INST_tb_randomB_zaz.METH_wget();
  DEF_v__h1919 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1745 : 0u;
  INST_tb_randomB_ignore.METH_wset(DEF_v__h1919);
}

void MOD_mkTbEx9a::RL_tb_feed()
{
  tUInt64 DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d64;
  tUInt32 DEF_x__h2275;
  tUInt64 DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65;
  tUInt8 DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63;
  DEF_x__h2294 = INST_tb_feed_count.METH_read();
  DEF_x_wget__h1745 = INST_tb_randomB_zaz.METH_wget();
  DEF_x_wget__h1318 = INST_tb_randomA_zaz.METH_wget();
  DEF_v__h1493 = INST_tb_randomA_zaz.METH_whas() ? DEF_x_wget__h1318 : 0u;
  DEF_v__h1919 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1745 : 0u;
  DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48 = DEF_v__h1493 == 2147483648u;
  DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49 = DEF_v__h1919 == 2147483648u;
  DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63 = !DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48 && !DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49;
  DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65 = primSignExt64(33u,
									       32u,
									       (tUInt32)(DEF_v__h1493));
  DEF_x__h2275 = DEF_x__h2294 + 1u;
  DEF_x__h2253.set_bits_in_word((tUInt8)(0llu),
				2u,
				0u,
				2u).set_whole_word((((tUInt32)(2147483647u & 0llu)) << 1u) | (tUInt32)((tUInt8)(DEF_v__h1919 >> 31u)),
						   1u).set_whole_word((((tUInt32)(2147483647u & DEF_v__h1919)) << 1u) | (tUInt32)((tUInt8)0u),
								      0u);
  DEF_x__h2237.set_bits_in_word((tUInt8)((8589934591llu & -DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65) >> 31u),
				2u,
				0u,
				2u).set_whole_word((((tUInt32)(2147483647u & (8589934591llu & -DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65))) << 1u) | (tUInt32)((tUInt8)(0llu)),
						   1u).set_whole_word((tUInt32)(0llu), 0u);
  DEF_x__h2206.set_bits_in_word((tUInt8)(DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65 >> 31u),
				2u,
				0u,
				2u).set_whole_word((((tUInt32)(2147483647u & DEF_SEXT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_ETC___d65)) << 1u) | (tUInt32)((tUInt8)(0llu)),
						   1u).set_whole_word((tUInt32)(0llu), 0u);
  DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d64 = (((tUInt64)(DEF_v__h1493)) << 32u) | (tUInt64)(DEF_v__h1919);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_tb_operands_fifo.METH_enq(DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d64);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_dut_i.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_dut_m_pos.METH_write(DEF_x__h2206);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_dut_m_neg.METH_write(DEF_x__h2237);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_dut_p.METH_write(DEF_x__h2253);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA__ETC___d63)
    INST_tb_feed_count.METH_write(DEF_x__h2275);
}

void MOD_mkTbEx9a::RL_tb_read()
{
  tUInt32 DEF_x__h2707;
  tUInt8 DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91;
  tUInt64 DEF_y_avValue__h2383;
  tUInt64 DEF_tb_operands_fifo_first____d80;
  tUInt32 DEF_b__h2314;
  tUInt32 DEF_signed_tb_operands_fifo_first__0_BITS_31_TO_0_3___d89;
  tUInt32 DEF_a__h2313;
  tUInt32 DEF_signed_tb_operands_fifo_first__0_BITS_63_TO_32_1___d88;
  tUInt64 DEF_v__h2344;
  tUInt64 DEF_signed_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_ETC___d90;
  tUInt64 DEF_expected__h2410;
  tUInt64 DEF_signed_SEXT_tb_operands_fifo_first__0_BITS_63_ETC___d92;
  tUInt8 DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87;
  DEF_dut_p__h2405 = INST_dut_p.METH_read();
  DEF_tb_operands_fifo_first____d80 = INST_tb_operands_fifo.METH_first();
  DEF_a__h2313 = (tUInt32)(DEF_tb_operands_fifo_first____d80 >> 32u);
  DEF_signed_tb_operands_fifo_first__0_BITS_63_TO_32_1___d88 = DEF_a__h2313;
  DEF_b__h2314 = (tUInt32)(DEF_tb_operands_fifo_first____d80);
  DEF_signed_tb_operands_fifo_first__0_BITS_31_TO_0_3___d89 = DEF_b__h2314;
  DEF_x__h2833 = INST_tb_read_count.METH_read();
  DEF__read__h142 = INST_dut_i.METH_read();
  wop_mul(WideData(64u, primSignExt64(64u, 32u, (tUInt32)(DEF_a__h2313))),
	  WideData(64u, primSignExt64(64u, 32u, (tUInt32)(DEF_b__h2314))),
	  DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85);
  DEF_expected__h2410 = primExtract64(64u,
				      128u,
				      DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85,
				      32u,
				      63u,
				      32u,
				      0u);
  DEF_signed_SEXT_tb_operands_fifo_first__0_BITS_63_ETC___d92 = DEF_expected__h2410;
  DEF_y_avValue__h2383 = primExtract64(64u, 66u, DEF_dut_p__h2405, 32u, 64u, 32u, 1u);
  DEF_dut_i_EQ_16___d75 = DEF__read__h142 == (tUInt8)16u;
  DEF_v__h2344 = DEF_dut_i_EQ_16___d75 ? DEF_y_avValue__h2383 : 0llu;
  DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87 = DEF_v__h2344 == DEF_expected__h2410;
  DEF_signed_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_ETC___d90 = DEF_v__h2344;
  DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91 = !DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87;
  DEF_x__h2707 = DEF_x__h2833 + 1u;
  INST_tb_operands_fifo.METH_deq();
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_x__h2833);
  INST_dut_i.METH_write((tUInt8)17u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32,-64",
		     &__str_literal_2,
		     DEF_signed_tb_operands_fifo_first__0_BITS_63_TO_32_1___d88,
		     DEF_signed_tb_operands_fifo_first__0_BITS_31_TO_0_3___d89,
		     DEF_signed_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_ETC___d90);
    if (DEF_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ELS_ETC___d87)
      dollar_display(sim_hdl,
		     this,
		     "s,32,32,64",
		     &__str_literal_3,
		     DEF_a__h2313,
		     DEF_b__h2314,
		     DEF_v__h2344);
    if (DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_4, DEF_x__h2833);
    if (DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32,-64,-64",
		     &__str_literal_5,
		     DEF_signed_tb_operands_fifo_first__0_BITS_63_TO_32_1___d88,
		     DEF_signed_tb_operands_fifo_first__0_BITS_31_TO_0_3___d89,
		     DEF_signed_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_ETC___d90,
		     DEF_signed_SEXT_tb_operands_fifo_first__0_BITS_63_ETC___d92);
    if (DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91)
      dollar_display(sim_hdl,
		     this,
		     "s,32,32,64,64",
		     &__str_literal_6,
		     DEF_a__h2313,
		     DEF_b__h2314,
		     DEF_v__h2344,
		     DEF_expected__h2410);
    if (DEF_NOT_IF_dut_i_EQ_16_5_THEN_dut_p_BITS_64_TO_1_8_ETC___d91)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_read_count.METH_write(DEF_x__h2707);
}

void MOD_mkTbEx9a::RL_tb_monitor_test()
{
  tUInt32 DEF_x__h3080;
  tUInt8 DEF_tb_cycle_4_EQ_0___d95;
  tUInt8 DEF_tb_cycle_4_EQ_16384___d96;
  tUInt32 DEF_x__h3084;
  DEF_x__h2833 = INST_tb_read_count.METH_read();
  DEF_x__h3084 = INST_tb_cycle.METH_read();
  DEF_tb_cycle_4_EQ_16384___d96 = DEF_x__h3084 == 16384u;
  DEF_tb_cycle_4_EQ_0___d95 = DEF_x__h3084 == 0u;
  DEF_tb_read_count_2_EQ_128___d73 = DEF_x__h2833 == 128u;
  DEF_x__h3080 = DEF_x__h3084 + 1u;
  if (DEF_tb_cycle_4_EQ_0___d95)
    INST_tb_randomA_initialized.METH_write((tUInt8)1u);
  if (DEF_tb_cycle_4_EQ_0___d95)
    INST_tb_randomB_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_tb_read_count_2_EQ_128___d73)
      dollar_display(sim_hdl, this, "s,32,32", &__str_literal_7, DEF_x__h2833, DEF_x__h3084);
    if (DEF_tb_read_count_2_EQ_128___d73)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_tb_cycle_4_EQ_16384___d96)
      dollar_display(sim_hdl, this, "s", &__str_literal_8);
    if (DEF_tb_cycle_4_EQ_16384___d96)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_cycle.METH_write(DEF_x__h3080);
}


/* Methods */


/* Reset routines */

void MOD_mkTbEx9a::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_tb_read_count.reset_RST(ARG_rst_in);
  INST_tb_randomB_initialized.reset_RST(ARG_rst_in);
  INST_tb_randomA_initialized.reset_RST(ARG_rst_in);
  INST_tb_operands_fifo.reset_RST(ARG_rst_in);
  INST_tb_feed_count.reset_RST(ARG_rst_in);
  INST_tb_cycle.reset_RST(ARG_rst_in);
  INST_dut_i.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbEx9a::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbEx9a::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_dut_i.dump_state(indent + 2u);
  INST_dut_m_neg.dump_state(indent + 2u);
  INST_dut_m_pos.dump_state(indent + 2u);
  INST_dut_p.dump_state(indent + 2u);
  INST_tb_cycle.dump_state(indent + 2u);
  INST_tb_feed_count.dump_state(indent + 2u);
  INST_tb_operands_fifo.dump_state(indent + 2u);
  INST_tb_randomA_ignore.dump_state(indent + 2u);
  INST_tb_randomA_initialized.dump_state(indent + 2u);
  INST_tb_randomA_zaz.dump_state(indent + 2u);
  INST_tb_randomB_ignore.dump_state(indent + 2u);
  INST_tb_randomB_initialized.dump_state(indent + 2u);
  INST_tb_randomB_zaz.dump_state(indent + 2u);
  INST_tb_read_count.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbEx9a::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 68u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_dut_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_dut_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h142", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_i_EQ_16___d75", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_m_neg_BITS_64_TO_0___h751", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_m_pos_BITS_64_TO_0___h614", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_p__h2405", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h1454", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h1881", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_read_count_2_EQ_128___d73", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1493", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1919", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2206", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2237", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2253", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2294", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2833", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h303", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h313", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h452", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h462", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h586", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h596", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h733", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h743", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h781", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1318", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1745", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h332", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h466", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h600", 66u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h747", 66u);
  num = INST_dut_i.dump_VCD_defs(num);
  num = INST_dut_m_neg.dump_VCD_defs(num);
  num = INST_dut_m_pos.dump_VCD_defs(num);
  num = INST_dut_p.dump_VCD_defs(num);
  num = INST_tb_cycle.dump_VCD_defs(num);
  num = INST_tb_feed_count.dump_VCD_defs(num);
  num = INST_tb_operands_fifo.dump_VCD_defs(num);
  num = INST_tb_randomA_ignore.dump_VCD_defs(num);
  num = INST_tb_randomA_initialized.dump_VCD_defs(num);
  num = INST_tb_randomA_zaz.dump_VCD_defs(num);
  num = INST_tb_randomB_ignore.dump_VCD_defs(num);
  num = INST_tb_randomB_initialized.dump_VCD_defs(num);
  num = INST_tb_randomB_zaz.dump_VCD_defs(num);
  num = INST_tb_read_count.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbEx9a::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx9a &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbEx9a::vcd_defs(tVCDDumpType dt, MOD_mkTbEx9a &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
    vcd_write_x(sim_hdl, num++, 66u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_dut_mul_step) != DEF_CAN_FIRE_RL_dut_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_dut_mul_step, 1u);
	backing.DEF_CAN_FIRE_RL_dut_mul_step = DEF_CAN_FIRE_RL_dut_mul_step;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_feed) != DEF_CAN_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_feed, 1u);
	backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_monitor_test) != DEF_CAN_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every) != DEF_CAN_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every_1) != DEF_CAN_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every) != DEF_CAN_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every_1) != DEF_CAN_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_read) != DEF_CAN_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_read, 1u);
	backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32) != DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32, 66u);
	backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32 = DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32;
      }
      ++num;
      if ((backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34) != DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34, 66u);
	backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34 = DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34;
      }
      ++num;
      if ((backing.DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31) != DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31, 66u);
	backing.DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31 = DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31;
      }
      ++num;
      if ((backing.DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33) != DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33, 66u);
	backing.DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33 = DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48) != DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48, 1u);
	backing.DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48 = DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49) != DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49, 1u);
	backing.DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49 = DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85) != DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85, 128u);
	backing.DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85 = DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_dut_mul_step) != DEF_WILL_FIRE_RL_dut_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_dut_mul_step, 1u);
	backing.DEF_WILL_FIRE_RL_dut_mul_step = DEF_WILL_FIRE_RL_dut_mul_step;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_feed) != DEF_WILL_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_feed, 1u);
	backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_monitor_test) != DEF_WILL_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every) != DEF_WILL_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every_1) != DEF_WILL_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every) != DEF_WILL_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every_1) != DEF_WILL_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_read) != DEF_WILL_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_read, 1u);
	backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF__read__h142) != DEF__read__h142)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h142, 6u);
	backing.DEF__read__h142 = DEF__read__h142;
      }
      ++num;
      if ((backing.DEF_dut_i_EQ_16___d75) != DEF_dut_i_EQ_16___d75)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_i_EQ_16___d75, 1u);
	backing.DEF_dut_i_EQ_16___d75 = DEF_dut_i_EQ_16___d75;
      }
      ++num;
      if ((backing.DEF_dut_m_neg_BITS_64_TO_0___h751) != DEF_dut_m_neg_BITS_64_TO_0___h751)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_m_neg_BITS_64_TO_0___h751, 65u);
	backing.DEF_dut_m_neg_BITS_64_TO_0___h751 = DEF_dut_m_neg_BITS_64_TO_0___h751;
      }
      ++num;
      if ((backing.DEF_dut_m_pos_BITS_64_TO_0___h614) != DEF_dut_m_pos_BITS_64_TO_0___h614)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_m_pos_BITS_64_TO_0___h614, 65u);
	backing.DEF_dut_m_pos_BITS_64_TO_0___h614 = DEF_dut_m_pos_BITS_64_TO_0___h614;
      }
      ++num;
      if ((backing.DEF_dut_p__h2405) != DEF_dut_p__h2405)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_p__h2405, 66u);
	backing.DEF_dut_p__h2405 = DEF_dut_p__h2405;
      }
      ++num;
      if ((backing.DEF_new_value__h1454) != DEF_new_value__h1454)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h1454, 32u);
	backing.DEF_new_value__h1454 = DEF_new_value__h1454;
      }
      ++num;
      if ((backing.DEF_new_value__h1881) != DEF_new_value__h1881)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h1881, 32u);
	backing.DEF_new_value__h1881 = DEF_new_value__h1881;
      }
      ++num;
      if ((backing.DEF_tb_read_count_2_EQ_128___d73) != DEF_tb_read_count_2_EQ_128___d73)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_read_count_2_EQ_128___d73, 1u);
	backing.DEF_tb_read_count_2_EQ_128___d73 = DEF_tb_read_count_2_EQ_128___d73;
      }
      ++num;
      if ((backing.DEF_v__h1493) != DEF_v__h1493)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1493, 32u);
	backing.DEF_v__h1493 = DEF_v__h1493;
      }
      ++num;
      if ((backing.DEF_v__h1919) != DEF_v__h1919)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1919, 32u);
	backing.DEF_v__h1919 = DEF_v__h1919;
      }
      ++num;
      if ((backing.DEF_x__h2206) != DEF_x__h2206)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2206, 66u);
	backing.DEF_x__h2206 = DEF_x__h2206;
      }
      ++num;
      if ((backing.DEF_x__h2237) != DEF_x__h2237)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2237, 66u);
	backing.DEF_x__h2237 = DEF_x__h2237;
      }
      ++num;
      if ((backing.DEF_x__h2253) != DEF_x__h2253)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2253, 66u);
	backing.DEF_x__h2253 = DEF_x__h2253;
      }
      ++num;
      if ((backing.DEF_x__h2294) != DEF_x__h2294)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2294, 32u);
	backing.DEF_x__h2294 = DEF_x__h2294;
      }
      ++num;
      if ((backing.DEF_x__h2833) != DEF_x__h2833)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2833, 32u);
	backing.DEF_x__h2833 = DEF_x__h2833;
      }
      ++num;
      if ((backing.DEF_x__h303) != DEF_x__h303)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h303, 66u);
	backing.DEF_x__h303 = DEF_x__h303;
      }
      ++num;
      if ((backing.DEF_x__h313) != DEF_x__h313)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h313, 66u);
	backing.DEF_x__h313 = DEF_x__h313;
      }
      ++num;
      if ((backing.DEF_x__h452) != DEF_x__h452)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h452, 66u);
	backing.DEF_x__h452 = DEF_x__h452;
      }
      ++num;
      if ((backing.DEF_x__h462) != DEF_x__h462)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h462, 66u);
	backing.DEF_x__h462 = DEF_x__h462;
      }
      ++num;
      if ((backing.DEF_x__h586) != DEF_x__h586)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h586, 66u);
	backing.DEF_x__h586 = DEF_x__h586;
      }
      ++num;
      if ((backing.DEF_x__h596) != DEF_x__h596)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h596, 66u);
	backing.DEF_x__h596 = DEF_x__h596;
      }
      ++num;
      if ((backing.DEF_x__h733) != DEF_x__h733)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h733, 66u);
	backing.DEF_x__h733 = DEF_x__h733;
      }
      ++num;
      if ((backing.DEF_x__h743) != DEF_x__h743)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h743, 66u);
	backing.DEF_x__h743 = DEF_x__h743;
      }
      ++num;
      if ((backing.DEF_x__h781) != DEF_x__h781)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h781, 66u);
	backing.DEF_x__h781 = DEF_x__h781;
      }
      ++num;
      if ((backing.DEF_x_wget__h1318) != DEF_x_wget__h1318)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1318, 32u);
	backing.DEF_x_wget__h1318 = DEF_x_wget__h1318;
      }
      ++num;
      if ((backing.DEF_x_wget__h1745) != DEF_x_wget__h1745)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1745, 32u);
	backing.DEF_x_wget__h1745 = DEF_x_wget__h1745;
      }
      ++num;
      if ((backing.DEF_y__h332) != DEF_y__h332)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h332, 66u);
	backing.DEF_y__h332 = DEF_y__h332;
      }
      ++num;
      if ((backing.DEF_y__h466) != DEF_y__h466)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h466, 66u);
	backing.DEF_y__h466 = DEF_y__h466;
      }
      ++num;
      if ((backing.DEF_y__h600) != DEF_y__h600)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h600, 66u);
	backing.DEF_y__h600 = DEF_y__h600;
      }
      ++num;
      if ((backing.DEF_y__h747) != DEF_y__h747)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h747, 66u);
	backing.DEF_y__h747 = DEF_y__h747;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_dut_mul_step, 1u);
      backing.DEF_CAN_FIRE_RL_dut_mul_step = DEF_CAN_FIRE_RL_dut_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_feed, 1u);
      backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_read, 1u);
      backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32, 66u);
      backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32 = DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_AND_dut_p_B_ETC___d32;
      vcd_write_val(sim_hdl, num++, DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34, 66u);
      backing.DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34 = DEF_IF_INV_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_B_ETC___d34;
      vcd_write_val(sim_hdl, num++, DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31, 66u);
      backing.DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31 = DEF_IF_dut_p_BIT_2_AND_INV_dut_p_BIT_1_OR_dut_p_BI_ETC___d31;
      vcd_write_val(sim_hdl, num++, DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33, 66u);
      backing.DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33 = DEF_IF_dut_p_BIT_2_AND_dut_p_BIT_1_XOR_dut_p_BIT_0_ETC___d33;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48, 1u);
      backing.DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48 = DEF_IF_tb_randomA_zaz_whas__9_THEN_tb_randomA_zaz__ETC___d48;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49, 1u);
      backing.DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49 = DEF_IF_tb_randomB_zaz_whas__5_THEN_tb_randomB_zaz__ETC___d49;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85, 128u);
      backing.DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85 = DEF_SEXT_tb_operands_fifo_first__0_BITS_63_TO_32_1_ETC___d85;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_dut_mul_step, 1u);
      backing.DEF_WILL_FIRE_RL_dut_mul_step = DEF_WILL_FIRE_RL_dut_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_feed, 1u);
      backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_read, 1u);
      backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF__read__h142, 6u);
      backing.DEF__read__h142 = DEF__read__h142;
      vcd_write_val(sim_hdl, num++, DEF_dut_i_EQ_16___d75, 1u);
      backing.DEF_dut_i_EQ_16___d75 = DEF_dut_i_EQ_16___d75;
      vcd_write_val(sim_hdl, num++, DEF_dut_m_neg_BITS_64_TO_0___h751, 65u);
      backing.DEF_dut_m_neg_BITS_64_TO_0___h751 = DEF_dut_m_neg_BITS_64_TO_0___h751;
      vcd_write_val(sim_hdl, num++, DEF_dut_m_pos_BITS_64_TO_0___h614, 65u);
      backing.DEF_dut_m_pos_BITS_64_TO_0___h614 = DEF_dut_m_pos_BITS_64_TO_0___h614;
      vcd_write_val(sim_hdl, num++, DEF_dut_p__h2405, 66u);
      backing.DEF_dut_p__h2405 = DEF_dut_p__h2405;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h1454, 32u);
      backing.DEF_new_value__h1454 = DEF_new_value__h1454;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h1881, 32u);
      backing.DEF_new_value__h1881 = DEF_new_value__h1881;
      vcd_write_val(sim_hdl, num++, DEF_tb_read_count_2_EQ_128___d73, 1u);
      backing.DEF_tb_read_count_2_EQ_128___d73 = DEF_tb_read_count_2_EQ_128___d73;
      vcd_write_val(sim_hdl, num++, DEF_v__h1493, 32u);
      backing.DEF_v__h1493 = DEF_v__h1493;
      vcd_write_val(sim_hdl, num++, DEF_v__h1919, 32u);
      backing.DEF_v__h1919 = DEF_v__h1919;
      vcd_write_val(sim_hdl, num++, DEF_x__h2206, 66u);
      backing.DEF_x__h2206 = DEF_x__h2206;
      vcd_write_val(sim_hdl, num++, DEF_x__h2237, 66u);
      backing.DEF_x__h2237 = DEF_x__h2237;
      vcd_write_val(sim_hdl, num++, DEF_x__h2253, 66u);
      backing.DEF_x__h2253 = DEF_x__h2253;
      vcd_write_val(sim_hdl, num++, DEF_x__h2294, 32u);
      backing.DEF_x__h2294 = DEF_x__h2294;
      vcd_write_val(sim_hdl, num++, DEF_x__h2833, 32u);
      backing.DEF_x__h2833 = DEF_x__h2833;
      vcd_write_val(sim_hdl, num++, DEF_x__h303, 66u);
      backing.DEF_x__h303 = DEF_x__h303;
      vcd_write_val(sim_hdl, num++, DEF_x__h313, 66u);
      backing.DEF_x__h313 = DEF_x__h313;
      vcd_write_val(sim_hdl, num++, DEF_x__h452, 66u);
      backing.DEF_x__h452 = DEF_x__h452;
      vcd_write_val(sim_hdl, num++, DEF_x__h462, 66u);
      backing.DEF_x__h462 = DEF_x__h462;
      vcd_write_val(sim_hdl, num++, DEF_x__h586, 66u);
      backing.DEF_x__h586 = DEF_x__h586;
      vcd_write_val(sim_hdl, num++, DEF_x__h596, 66u);
      backing.DEF_x__h596 = DEF_x__h596;
      vcd_write_val(sim_hdl, num++, DEF_x__h733, 66u);
      backing.DEF_x__h733 = DEF_x__h733;
      vcd_write_val(sim_hdl, num++, DEF_x__h743, 66u);
      backing.DEF_x__h743 = DEF_x__h743;
      vcd_write_val(sim_hdl, num++, DEF_x__h781, 66u);
      backing.DEF_x__h781 = DEF_x__h781;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1318, 32u);
      backing.DEF_x_wget__h1318 = DEF_x_wget__h1318;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1745, 32u);
      backing.DEF_x_wget__h1745 = DEF_x_wget__h1745;
      vcd_write_val(sim_hdl, num++, DEF_y__h332, 66u);
      backing.DEF_y__h332 = DEF_y__h332;
      vcd_write_val(sim_hdl, num++, DEF_y__h466, 66u);
      backing.DEF_y__h466 = DEF_y__h466;
      vcd_write_val(sim_hdl, num++, DEF_y__h600, 66u);
      backing.DEF_y__h600 = DEF_y__h600;
      vcd_write_val(sim_hdl, num++, DEF_y__h747, 66u);
      backing.DEF_y__h747 = DEF_y__h747;
    }
}

void MOD_mkTbEx9a::vcd_prims(tVCDDumpType dt, MOD_mkTbEx9a &backing)
{
  INST_dut_i.dump_VCD(dt, backing.INST_dut_i);
  INST_dut_m_neg.dump_VCD(dt, backing.INST_dut_m_neg);
  INST_dut_m_pos.dump_VCD(dt, backing.INST_dut_m_pos);
  INST_dut_p.dump_VCD(dt, backing.INST_dut_p);
  INST_tb_cycle.dump_VCD(dt, backing.INST_tb_cycle);
  INST_tb_feed_count.dump_VCD(dt, backing.INST_tb_feed_count);
  INST_tb_operands_fifo.dump_VCD(dt, backing.INST_tb_operands_fifo);
  INST_tb_randomA_ignore.dump_VCD(dt, backing.INST_tb_randomA_ignore);
  INST_tb_randomA_initialized.dump_VCD(dt, backing.INST_tb_randomA_initialized);
  INST_tb_randomA_zaz.dump_VCD(dt, backing.INST_tb_randomA_zaz);
  INST_tb_randomB_ignore.dump_VCD(dt, backing.INST_tb_randomB_ignore);
  INST_tb_randomB_initialized.dump_VCD(dt, backing.INST_tb_randomB_initialized);
  INST_tb_randomB_zaz.dump_VCD(dt, backing.INST_tb_randomB_zaz);
  INST_tb_read_count.dump_VCD(dt, backing.INST_tb_read_count);
}
