/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr  5 14:20:32 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbEx7a.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("    if signed: %0d * %0d DUT gave %0d", 37u);
static std::string const __str_literal_5("    if signed: %0d * %0d DUT gave %0d instead of %0d",
					 52u);
static std::string const __str_literal_3("    if unsigned: %0d * %0d DUT gave %0d", 39u);
static std::string const __str_literal_6("    if unsigned: %0d * %0d DUT gave %0d instead of %0d",
					 54u);
static std::string const __str_literal_4("FAILED case %0d", 15u);
static std::string const __str_literal_8("FAILED due to cycle limit", 25u);
static std::string const __str_literal_7("PASSED %0d test cases in %0d cycles", 35u);
static std::string const __str_literal_1("PASSED case %0d", 15u);


/* Constructor */
MOD_mkTbEx7a::MOD_mkTbEx7a(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_dut_i(simHdl, "dut_i", this, 6u, (tUInt8)33u, (tUInt8)0u),
    INST_dut_m_neg(simHdl, "dut_m_neg", this, 65u),
    INST_dut_m_pos(simHdl, "dut_m_pos", this, 65u),
    INST_dut_p(simHdl, "dut_p", this, 65u),
    INST_tb_cycle(simHdl, "tb_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_tb_feed_count(simHdl, "tb_feed_count", this, 32u, 0u, (tUInt8)0u),
    INST_tb_operands_fifo(simHdl, "tb_operands_fifo", this, 64u, 4u, 1u, 0u),
    INST_tb_randomA_ignore(simHdl, "tb_randomA_ignore", this, 32u, (tUInt8)0u),
    INST_tb_randomA_initialized(simHdl, "tb_randomA_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomA_zaz(simHdl, "tb_randomA_zaz", this, 32u, (tUInt8)0u),
    INST_tb_randomB_ignore(simHdl, "tb_randomB_ignore", this, 32u, (tUInt8)0u),
    INST_tb_randomB_initialized(simHdl, "tb_randomB_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tb_randomB_zaz(simHdl, "tb_randomB_zaz", this, 32u, (tUInt8)0u),
    INST_tb_read_count(simHdl, "tb_read_count", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_new_value__h1445(2863311530u),
    DEF_new_value__h1018(2863311530u),
    DEF_dut_p__h1960(65u),
    DEF_y__h270(65u),
    DEF_y__h358(65u),
    DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66(128u),
    DEF_x__h344(65u),
    DEF_x__h389(65u),
    DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15(65u),
    DEF_x__h241(65u),
    DEF_x__h251(65u),
    DEF_x__h354(65u),
    DEF_x__h1808(65u),
    DEF_x__h1793(65u),
    DEF_x__h1768(65u)
{
  symbol_count = 45u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbEx7a::init_symbols_0()
{
  init_symbol(&symbols[0u], "_read__h139", SYM_DEF, &DEF__read__h139, 6u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_dut_mul_step", SYM_DEF, &DEF_CAN_FIRE_RL_dut_mul_step, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_tb_feed", SYM_DEF, &DEF_CAN_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_tb_read", SYM_DEF, &DEF_CAN_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[9u], "dut_i", SYM_MODULE, &INST_dut_i);
  init_symbol(&symbols[10u], "dut_m_neg", SYM_MODULE, &INST_dut_m_neg);
  init_symbol(&symbols[11u], "dut_m_pos", SYM_MODULE, &INST_dut_m_pos);
  init_symbol(&symbols[12u], "dut_p", SYM_MODULE, &INST_dut_p);
  init_symbol(&symbols[13u], "RL_dut_mul_step", SYM_RULE);
  init_symbol(&symbols[14u], "RL_tb_feed", SYM_RULE);
  init_symbol(&symbols[15u], "RL_tb_monitor_test", SYM_RULE);
  init_symbol(&symbols[16u], "RL_tb_randomA_every", SYM_RULE);
  init_symbol(&symbols[17u], "RL_tb_randomA_every_1", SYM_RULE);
  init_symbol(&symbols[18u], "RL_tb_randomB_every", SYM_RULE);
  init_symbol(&symbols[19u], "RL_tb_randomB_every_1", SYM_RULE);
  init_symbol(&symbols[20u], "RL_tb_read", SYM_RULE);
  init_symbol(&symbols[21u], "tb_cycle", SYM_MODULE, &INST_tb_cycle);
  init_symbol(&symbols[22u], "tb_feed_count", SYM_MODULE, &INST_tb_feed_count);
  init_symbol(&symbols[23u], "tb_operands_fifo", SYM_MODULE, &INST_tb_operands_fifo);
  init_symbol(&symbols[24u], "tb_randomA_ignore", SYM_MODULE, &INST_tb_randomA_ignore);
  init_symbol(&symbols[25u], "tb_randomA_initialized", SYM_MODULE, &INST_tb_randomA_initialized);
  init_symbol(&symbols[26u], "tb_randomA_zaz", SYM_MODULE, &INST_tb_randomA_zaz);
  init_symbol(&symbols[27u], "tb_randomB_ignore", SYM_MODULE, &INST_tb_randomB_ignore);
  init_symbol(&symbols[28u], "tb_randomB_initialized", SYM_MODULE, &INST_tb_randomB_initialized);
  init_symbol(&symbols[29u], "tb_randomB_zaz", SYM_MODULE, &INST_tb_randomB_zaz);
  init_symbol(&symbols[30u], "tb_read_count", SYM_MODULE, &INST_tb_read_count);
  init_symbol(&symbols[31u], "v__h1057", SYM_DEF, &DEF_v__h1057, 32u);
  init_symbol(&symbols[32u], "v__h1483", SYM_DEF, &DEF_v__h1483, 32u);
  init_symbol(&symbols[33u],
	      "WILL_FIRE_RL_dut_mul_step",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_dut_mul_step,
	      1u);
  init_symbol(&symbols[34u], "WILL_FIRE_RL_tb_feed", SYM_DEF, &DEF_WILL_FIRE_RL_tb_feed, 1u);
  init_symbol(&symbols[35u],
	      "WILL_FIRE_RL_tb_monitor_test",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_monitor_test,
	      1u);
  init_symbol(&symbols[36u],
	      "WILL_FIRE_RL_tb_randomA_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every,
	      1u);
  init_symbol(&symbols[37u],
	      "WILL_FIRE_RL_tb_randomA_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomA_every_1,
	      1u);
  init_symbol(&symbols[38u],
	      "WILL_FIRE_RL_tb_randomB_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every,
	      1u);
  init_symbol(&symbols[39u],
	      "WILL_FIRE_RL_tb_randomB_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_tb_randomB_every_1,
	      1u);
  init_symbol(&symbols[40u], "WILL_FIRE_RL_tb_read", SYM_DEF, &DEF_WILL_FIRE_RL_tb_read, 1u);
  init_symbol(&symbols[41u], "x__h1849", SYM_DEF, &DEF_x__h1849, 32u);
  init_symbol(&symbols[42u], "x__h2388", SYM_DEF, &DEF_x__h2388, 32u);
  init_symbol(&symbols[43u], "x_wget__h1309", SYM_DEF, &DEF_x_wget__h1309, 32u);
  init_symbol(&symbols[44u], "x_wget__h882", SYM_DEF, &DEF_x_wget__h882, 32u);
}


/* Rule actions */

void MOD_mkTbEx7a::RL_dut_mul_step()
{
  tUInt8 DEF_x__h462;
  tUInt8 DEF_x__h293;
  DEF_dut_p__h1960 = INST_dut_p.METH_read();
  DEF_y__h270 = INST_dut_m_pos.METH_read();
  DEF_y__h358 = INST_dut_m_neg.METH_read();
  DEF__read__h139 = INST_dut_i.METH_read();
  DEF_x__h293 = DEF_dut_p__h1960.get_bits_in_word8(0u, 0u, 2u);
  wop_primShiftRAWide(65u, 65u, DEF_dut_p__h1960, 32u, 1u, DEF_x__h389);
  wop_add(DEF_dut_p__h1960, DEF_y__h270, DEF_x__h251);
  wop_primShiftRAWide(65u, 65u, DEF_x__h251, 32u, 1u, DEF_x__h241);
  wop_add(DEF_dut_p__h1960, DEF_y__h358, DEF_x__h354);
  wop_primShiftRAWide(65u, 65u, DEF_x__h354, 32u, 1u, DEF_x__h344);
  switch (DEF_x__h293) {
  case (tUInt8)1u:
    DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15 = DEF_x__h241;
    break;
  case (tUInt8)2u:
    DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15 = DEF_x__h344;
    break;
  default:
    DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15 = DEF_x__h389;
  }
  DEF_x__h462 = (tUInt8)63u & (DEF__read__h139 + (tUInt8)1u);
  INST_dut_p.METH_write(DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15);
  INST_dut_i.METH_write(DEF_x__h462);
}

void MOD_mkTbEx7a::RL_tb_randomA_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h1018 = rand32();
  }
  INST_tb_randomA_zaz.METH_wset(DEF_new_value__h1018);
}

void MOD_mkTbEx7a::RL_tb_randomA_every_1()
{
  DEF_x_wget__h882 = INST_tb_randomA_zaz.METH_wget();
  DEF_tb_randomA_zaz_whas____d20 = INST_tb_randomA_zaz.METH_whas();
  DEF_v__h1057 = DEF_tb_randomA_zaz_whas____d20 ? DEF_x_wget__h882 : 0u;
  INST_tb_randomA_ignore.METH_wset(DEF_v__h1057);
}

void MOD_mkTbEx7a::RL_tb_randomB_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h1445 = rand32();
  }
  INST_tb_randomB_zaz.METH_wset(DEF_new_value__h1445);
}

void MOD_mkTbEx7a::RL_tb_randomB_every_1()
{
  DEF_x_wget__h1309 = INST_tb_randomB_zaz.METH_wget();
  DEF_v__h1483 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1309 : 0u;
  INST_tb_randomB_ignore.METH_wset(DEF_v__h1483);
}

void MOD_mkTbEx7a::RL_tb_feed()
{
  tUInt64 DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d45;
  tUInt32 DEF_x__h1830;
  tUInt8 DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44;
  DEF_x__h1849 = INST_tb_feed_count.METH_read();
  DEF_x_wget__h1309 = INST_tb_randomB_zaz.METH_wget();
  DEF_x_wget__h882 = INST_tb_randomA_zaz.METH_wget();
  DEF_tb_randomA_zaz_whas____d20 = INST_tb_randomA_zaz.METH_whas();
  DEF_v__h1057 = DEF_tb_randomA_zaz_whas____d20 ? DEF_x_wget__h882 : 0u;
  DEF_v__h1483 = INST_tb_randomB_zaz.METH_whas() ? DEF_x_wget__h1309 : 0u;
  DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29 = DEF_v__h1057 == 2147483648u;
  DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30 = DEF_v__h1483 == 2147483648u;
  DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44 = !DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29 && !DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30;
  DEF_x__h1830 = DEF_x__h1849 + 1u;
  DEF_x__h1808.set_bits_in_word((tUInt8)(0u),
				2u,
				0u,
				1u).set_whole_word((((tUInt32)(2147483647u & 0u)) << 1u) | (tUInt32)((tUInt8)(DEF_v__h1483 >> 31u)),
						   1u).set_whole_word((((tUInt32)(2147483647u & DEF_v__h1483)) << 1u) | (tUInt32)((tUInt8)0u),
								      0u);
  DEF_x__h1768.set_bits_in_word((tUInt8)(DEF_v__h1057 >> 31u),
				2u,
				0u,
				1u).set_whole_word((((tUInt32)(2147483647u & DEF_v__h1057)) << 1u) | (tUInt32)((tUInt8)(0llu)),
						   1u).set_whole_word((tUInt32)(0llu), 0u);
  DEF_x__h1793.set_bits_in_word((tUInt8)((DEF_tb_randomA_zaz_whas____d20 ? -DEF_x_wget__h882 : 0u) >> 31u),
				2u,
				0u,
				1u).set_whole_word((((tUInt32)(2147483647u & (DEF_tb_randomA_zaz_whas____d20 ? -DEF_x_wget__h882 : 0u))) << 1u) | (tUInt32)((tUInt8)(0llu)),
						   1u).set_whole_word((tUInt32)(0llu), 0u);
  DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d45 = (((tUInt64)(DEF_v__h1057)) << 32u) | (tUInt64)(DEF_v__h1483);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_tb_operands_fifo.METH_enq(DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d45);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_dut_i.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_dut_m_pos.METH_write(DEF_x__h1768);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_dut_m_neg.METH_write(DEF_x__h1793);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_dut_p.METH_write(DEF_x__h1808);
  if (DEF_NOT_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA__ETC___d44)
    INST_tb_feed_count.METH_write(DEF_x__h1830);
}

void MOD_mkTbEx7a::RL_tb_read()
{
  tUInt32 DEF_x__h2262;
  tUInt8 DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72;
  tUInt64 DEF_y_avValue__h1938;
  tUInt64 DEF_tb_operands_fifo_first____d61;
  tUInt32 DEF_b__h1869;
  tUInt32 DEF_signed_tb_operands_fifo_first__1_BITS_31_TO_0_4___d70;
  tUInt32 DEF_a__h1868;
  tUInt32 DEF_signed_tb_operands_fifo_first__1_BITS_63_TO_32_2___d69;
  tUInt64 DEF_v__h1899;
  tUInt64 DEF_signed_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_ETC___d71;
  tUInt64 DEF_expected__h1965;
  tUInt64 DEF_signed_SEXT_tb_operands_fifo_first__1_BITS_63_ETC___d73;
  tUInt8 DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68;
  DEF_dut_p__h1960 = INST_dut_p.METH_read();
  DEF_tb_operands_fifo_first____d61 = INST_tb_operands_fifo.METH_first();
  DEF_a__h1868 = (tUInt32)(DEF_tb_operands_fifo_first____d61 >> 32u);
  DEF_signed_tb_operands_fifo_first__1_BITS_63_TO_32_2___d69 = DEF_a__h1868;
  DEF_b__h1869 = (tUInt32)(DEF_tb_operands_fifo_first____d61);
  DEF_signed_tb_operands_fifo_first__1_BITS_31_TO_0_4___d70 = DEF_b__h1869;
  DEF_x__h2388 = INST_tb_read_count.METH_read();
  DEF__read__h139 = INST_dut_i.METH_read();
  wop_mul(WideData(64u, primSignExt64(64u, 32u, (tUInt32)(DEF_a__h1868))),
	  WideData(64u, primSignExt64(64u, 32u, (tUInt32)(DEF_b__h1869))),
	  DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66);
  DEF_expected__h1965 = primExtract64(64u,
				      128u,
				      DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66,
				      32u,
				      63u,
				      32u,
				      0u);
  DEF_signed_SEXT_tb_operands_fifo_first__1_BITS_63_ETC___d73 = DEF_expected__h1965;
  DEF_y_avValue__h1938 = primExtract64(64u, 65u, DEF_dut_p__h1960, 32u, 64u, 32u, 1u);
  DEF_dut_i_EQ_32___d56 = DEF__read__h139 == (tUInt8)32u;
  DEF_v__h1899 = DEF_dut_i_EQ_32___d56 ? DEF_y_avValue__h1938 : 0llu;
  DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68 = DEF_v__h1899 == DEF_expected__h1965;
  DEF_signed_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_ETC___d71 = DEF_v__h1899;
  DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72 = !DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68;
  DEF_x__h2262 = DEF_x__h2388 + 1u;
  INST_tb_operands_fifo.METH_deq();
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_x__h2388);
  INST_dut_i.METH_write((tUInt8)33u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32,-64",
		     &__str_literal_2,
		     DEF_signed_tb_operands_fifo_first__1_BITS_63_TO_32_2___d69,
		     DEF_signed_tb_operands_fifo_first__1_BITS_31_TO_0_4___d70,
		     DEF_signed_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_ETC___d71);
    if (DEF_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ELS_ETC___d68)
      dollar_display(sim_hdl,
		     this,
		     "s,32,32,64",
		     &__str_literal_3,
		     DEF_a__h1868,
		     DEF_b__h1869,
		     DEF_v__h1899);
    if (DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_4, DEF_x__h2388);
    if (DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32,-64,-64",
		     &__str_literal_5,
		     DEF_signed_tb_operands_fifo_first__1_BITS_63_TO_32_2___d69,
		     DEF_signed_tb_operands_fifo_first__1_BITS_31_TO_0_4___d70,
		     DEF_signed_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_ETC___d71,
		     DEF_signed_SEXT_tb_operands_fifo_first__1_BITS_63_ETC___d73);
    if (DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72)
      dollar_display(sim_hdl,
		     this,
		     "s,32,32,64,64",
		     &__str_literal_6,
		     DEF_a__h1868,
		     DEF_b__h1869,
		     DEF_v__h1899,
		     DEF_expected__h1965);
    if (DEF_NOT_IF_dut_i_EQ_32_6_THEN_dut_p_BITS_64_TO_1_9_ETC___d72)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_read_count.METH_write(DEF_x__h2262);
}

void MOD_mkTbEx7a::RL_tb_monitor_test()
{
  tUInt32 DEF_x__h2635;
  tUInt8 DEF_tb_cycle_5_EQ_0___d76;
  tUInt8 DEF_tb_cycle_5_EQ_16384___d77;
  tUInt32 DEF_x__h2639;
  DEF_x__h2388 = INST_tb_read_count.METH_read();
  DEF_x__h2639 = INST_tb_cycle.METH_read();
  DEF_tb_cycle_5_EQ_16384___d77 = DEF_x__h2639 == 16384u;
  DEF_tb_cycle_5_EQ_0___d76 = DEF_x__h2639 == 0u;
  DEF_tb_read_count_3_EQ_128___d54 = DEF_x__h2388 == 128u;
  DEF_x__h2635 = DEF_x__h2639 + 1u;
  if (DEF_tb_cycle_5_EQ_0___d76)
    INST_tb_randomA_initialized.METH_write((tUInt8)1u);
  if (DEF_tb_cycle_5_EQ_0___d76)
    INST_tb_randomB_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_tb_read_count_3_EQ_128___d54)
      dollar_display(sim_hdl, this, "s,32,32", &__str_literal_7, DEF_x__h2388, DEF_x__h2639);
    if (DEF_tb_read_count_3_EQ_128___d54)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_tb_cycle_5_EQ_16384___d77)
      dollar_display(sim_hdl, this, "s", &__str_literal_8);
    if (DEF_tb_cycle_5_EQ_16384___d77)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_tb_cycle.METH_write(DEF_x__h2635);
}


/* Methods */


/* Reset routines */

void MOD_mkTbEx7a::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_tb_read_count.reset_RST(ARG_rst_in);
  INST_tb_randomB_initialized.reset_RST(ARG_rst_in);
  INST_tb_randomA_initialized.reset_RST(ARG_rst_in);
  INST_tb_operands_fifo.reset_RST(ARG_rst_in);
  INST_tb_feed_count.reset_RST(ARG_rst_in);
  INST_tb_cycle.reset_RST(ARG_rst_in);
  INST_dut_i.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbEx7a::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbEx7a::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_dut_i.dump_state(indent + 2u);
  INST_dut_m_neg.dump_state(indent + 2u);
  INST_dut_m_pos.dump_state(indent + 2u);
  INST_dut_p.dump_state(indent + 2u);
  INST_tb_cycle.dump_state(indent + 2u);
  INST_tb_feed_count.dump_state(indent + 2u);
  INST_tb_operands_fifo.dump_state(indent + 2u);
  INST_tb_randomA_ignore.dump_state(indent + 2u);
  INST_tb_randomA_initialized.dump_state(indent + 2u);
  INST_tb_randomA_zaz.dump_state(indent + 2u);
  INST_tb_randomB_ignore.dump_state(indent + 2u);
  INST_tb_randomB_initialized.dump_state(indent + 2u);
  INST_tb_randomB_zaz.dump_state(indent + 2u);
  INST_tb_read_count.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbEx7a::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 58u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_dut_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_dut_mul_step", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_feed", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_monitor_test", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_tb_read", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h139", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_i_EQ_32___d56", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dut_p__h1960", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h1018", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h1445", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_randomA_zaz_whas____d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "tb_read_count_3_EQ_128___d54", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1057", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1483", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1768", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1793", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1808", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1849", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2388", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h241", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h251", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h344", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h354", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h389", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1309", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h882", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h270", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h358", 65u);
  num = INST_dut_i.dump_VCD_defs(num);
  num = INST_dut_m_neg.dump_VCD_defs(num);
  num = INST_dut_m_pos.dump_VCD_defs(num);
  num = INST_dut_p.dump_VCD_defs(num);
  num = INST_tb_cycle.dump_VCD_defs(num);
  num = INST_tb_feed_count.dump_VCD_defs(num);
  num = INST_tb_operands_fifo.dump_VCD_defs(num);
  num = INST_tb_randomA_ignore.dump_VCD_defs(num);
  num = INST_tb_randomA_initialized.dump_VCD_defs(num);
  num = INST_tb_randomA_zaz.dump_VCD_defs(num);
  num = INST_tb_randomB_ignore.dump_VCD_defs(num);
  num = INST_tb_randomB_initialized.dump_VCD_defs(num);
  num = INST_tb_randomB_zaz.dump_VCD_defs(num);
  num = INST_tb_read_count.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbEx7a::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx7a &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbEx7a::vcd_defs(tVCDDumpType dt, MOD_mkTbEx7a &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_dut_mul_step) != DEF_CAN_FIRE_RL_dut_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_dut_mul_step, 1u);
	backing.DEF_CAN_FIRE_RL_dut_mul_step = DEF_CAN_FIRE_RL_dut_mul_step;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_feed) != DEF_CAN_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_feed, 1u);
	backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_monitor_test) != DEF_CAN_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every) != DEF_CAN_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomA_every_1) != DEF_CAN_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every) != DEF_CAN_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_randomB_every_1) != DEF_CAN_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_tb_read) != DEF_CAN_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_tb_read, 1u);
	backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15) != DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15, 65u);
	backing.DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15 = DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29) != DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29, 1u);
	backing.DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29 = DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29;
      }
      ++num;
      if ((backing.DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30) != DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30, 1u);
	backing.DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30 = DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66) != DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66, 128u);
	backing.DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66 = DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_dut_mul_step) != DEF_WILL_FIRE_RL_dut_mul_step)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_dut_mul_step, 1u);
	backing.DEF_WILL_FIRE_RL_dut_mul_step = DEF_WILL_FIRE_RL_dut_mul_step;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_feed) != DEF_WILL_FIRE_RL_tb_feed)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_feed, 1u);
	backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_monitor_test) != DEF_WILL_FIRE_RL_tb_monitor_test)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
	backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every) != DEF_WILL_FIRE_RL_tb_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomA_every_1) != DEF_WILL_FIRE_RL_tb_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every) != DEF_WILL_FIRE_RL_tb_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_randomB_every_1) != DEF_WILL_FIRE_RL_tb_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_tb_read) != DEF_WILL_FIRE_RL_tb_read)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_tb_read, 1u);
	backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      }
      ++num;
      if ((backing.DEF__read__h139) != DEF__read__h139)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h139, 6u);
	backing.DEF__read__h139 = DEF__read__h139;
      }
      ++num;
      if ((backing.DEF_dut_i_EQ_32___d56) != DEF_dut_i_EQ_32___d56)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_i_EQ_32___d56, 1u);
	backing.DEF_dut_i_EQ_32___d56 = DEF_dut_i_EQ_32___d56;
      }
      ++num;
      if ((backing.DEF_dut_p__h1960) != DEF_dut_p__h1960)
      {
	vcd_write_val(sim_hdl, num, DEF_dut_p__h1960, 65u);
	backing.DEF_dut_p__h1960 = DEF_dut_p__h1960;
      }
      ++num;
      if ((backing.DEF_new_value__h1018) != DEF_new_value__h1018)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h1018, 32u);
	backing.DEF_new_value__h1018 = DEF_new_value__h1018;
      }
      ++num;
      if ((backing.DEF_new_value__h1445) != DEF_new_value__h1445)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h1445, 32u);
	backing.DEF_new_value__h1445 = DEF_new_value__h1445;
      }
      ++num;
      if ((backing.DEF_tb_randomA_zaz_whas____d20) != DEF_tb_randomA_zaz_whas____d20)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_randomA_zaz_whas____d20, 1u);
	backing.DEF_tb_randomA_zaz_whas____d20 = DEF_tb_randomA_zaz_whas____d20;
      }
      ++num;
      if ((backing.DEF_tb_read_count_3_EQ_128___d54) != DEF_tb_read_count_3_EQ_128___d54)
      {
	vcd_write_val(sim_hdl, num, DEF_tb_read_count_3_EQ_128___d54, 1u);
	backing.DEF_tb_read_count_3_EQ_128___d54 = DEF_tb_read_count_3_EQ_128___d54;
      }
      ++num;
      if ((backing.DEF_v__h1057) != DEF_v__h1057)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1057, 32u);
	backing.DEF_v__h1057 = DEF_v__h1057;
      }
      ++num;
      if ((backing.DEF_v__h1483) != DEF_v__h1483)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1483, 32u);
	backing.DEF_v__h1483 = DEF_v__h1483;
      }
      ++num;
      if ((backing.DEF_x__h1768) != DEF_x__h1768)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1768, 65u);
	backing.DEF_x__h1768 = DEF_x__h1768;
      }
      ++num;
      if ((backing.DEF_x__h1793) != DEF_x__h1793)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1793, 65u);
	backing.DEF_x__h1793 = DEF_x__h1793;
      }
      ++num;
      if ((backing.DEF_x__h1808) != DEF_x__h1808)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1808, 65u);
	backing.DEF_x__h1808 = DEF_x__h1808;
      }
      ++num;
      if ((backing.DEF_x__h1849) != DEF_x__h1849)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1849, 32u);
	backing.DEF_x__h1849 = DEF_x__h1849;
      }
      ++num;
      if ((backing.DEF_x__h2388) != DEF_x__h2388)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2388, 32u);
	backing.DEF_x__h2388 = DEF_x__h2388;
      }
      ++num;
      if ((backing.DEF_x__h241) != DEF_x__h241)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h241, 65u);
	backing.DEF_x__h241 = DEF_x__h241;
      }
      ++num;
      if ((backing.DEF_x__h251) != DEF_x__h251)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h251, 65u);
	backing.DEF_x__h251 = DEF_x__h251;
      }
      ++num;
      if ((backing.DEF_x__h344) != DEF_x__h344)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h344, 65u);
	backing.DEF_x__h344 = DEF_x__h344;
      }
      ++num;
      if ((backing.DEF_x__h354) != DEF_x__h354)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h354, 65u);
	backing.DEF_x__h354 = DEF_x__h354;
      }
      ++num;
      if ((backing.DEF_x__h389) != DEF_x__h389)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h389, 65u);
	backing.DEF_x__h389 = DEF_x__h389;
      }
      ++num;
      if ((backing.DEF_x_wget__h1309) != DEF_x_wget__h1309)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1309, 32u);
	backing.DEF_x_wget__h1309 = DEF_x_wget__h1309;
      }
      ++num;
      if ((backing.DEF_x_wget__h882) != DEF_x_wget__h882)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h882, 32u);
	backing.DEF_x_wget__h882 = DEF_x_wget__h882;
      }
      ++num;
      if ((backing.DEF_y__h270) != DEF_y__h270)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h270, 65u);
	backing.DEF_y__h270 = DEF_y__h270;
      }
      ++num;
      if ((backing.DEF_y__h358) != DEF_y__h358)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h358, 65u);
	backing.DEF_y__h358 = DEF_y__h358;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_dut_mul_step, 1u);
      backing.DEF_CAN_FIRE_RL_dut_mul_step = DEF_CAN_FIRE_RL_dut_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_feed, 1u);
      backing.DEF_CAN_FIRE_RL_tb_feed = DEF_CAN_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_CAN_FIRE_RL_tb_monitor_test = DEF_CAN_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every = DEF_CAN_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomA_every_1 = DEF_CAN_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every = DEF_CAN_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_tb_randomB_every_1 = DEF_CAN_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_tb_read, 1u);
      backing.DEF_CAN_FIRE_RL_tb_read = DEF_CAN_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15, 65u);
      backing.DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15 = DEF_IF_dut_p_BITS_1_TO_0_EQ_0b1_THEN_dut_p_PLUS_du_ETC___d15;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29, 1u);
      backing.DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29 = DEF_IF_tb_randomA_zaz_whas__0_THEN_tb_randomA_zaz__ETC___d29;
      vcd_write_val(sim_hdl, num++, DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30, 1u);
      backing.DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30 = DEF_IF_tb_randomB_zaz_whas__6_THEN_tb_randomB_zaz__ETC___d30;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66, 128u);
      backing.DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66 = DEF_SEXT_tb_operands_fifo_first__1_BITS_63_TO_32_2_ETC___d66;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_dut_mul_step, 1u);
      backing.DEF_WILL_FIRE_RL_dut_mul_step = DEF_WILL_FIRE_RL_dut_mul_step;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_feed, 1u);
      backing.DEF_WILL_FIRE_RL_tb_feed = DEF_WILL_FIRE_RL_tb_feed;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_monitor_test, 1u);
      backing.DEF_WILL_FIRE_RL_tb_monitor_test = DEF_WILL_FIRE_RL_tb_monitor_test;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every = DEF_WILL_FIRE_RL_tb_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomA_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomA_every_1 = DEF_WILL_FIRE_RL_tb_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every = DEF_WILL_FIRE_RL_tb_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_randomB_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_tb_randomB_every_1 = DEF_WILL_FIRE_RL_tb_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_tb_read, 1u);
      backing.DEF_WILL_FIRE_RL_tb_read = DEF_WILL_FIRE_RL_tb_read;
      vcd_write_val(sim_hdl, num++, DEF__read__h139, 6u);
      backing.DEF__read__h139 = DEF__read__h139;
      vcd_write_val(sim_hdl, num++, DEF_dut_i_EQ_32___d56, 1u);
      backing.DEF_dut_i_EQ_32___d56 = DEF_dut_i_EQ_32___d56;
      vcd_write_val(sim_hdl, num++, DEF_dut_p__h1960, 65u);
      backing.DEF_dut_p__h1960 = DEF_dut_p__h1960;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h1018, 32u);
      backing.DEF_new_value__h1018 = DEF_new_value__h1018;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h1445, 32u);
      backing.DEF_new_value__h1445 = DEF_new_value__h1445;
      vcd_write_val(sim_hdl, num++, DEF_tb_randomA_zaz_whas____d20, 1u);
      backing.DEF_tb_randomA_zaz_whas____d20 = DEF_tb_randomA_zaz_whas____d20;
      vcd_write_val(sim_hdl, num++, DEF_tb_read_count_3_EQ_128___d54, 1u);
      backing.DEF_tb_read_count_3_EQ_128___d54 = DEF_tb_read_count_3_EQ_128___d54;
      vcd_write_val(sim_hdl, num++, DEF_v__h1057, 32u);
      backing.DEF_v__h1057 = DEF_v__h1057;
      vcd_write_val(sim_hdl, num++, DEF_v__h1483, 32u);
      backing.DEF_v__h1483 = DEF_v__h1483;
      vcd_write_val(sim_hdl, num++, DEF_x__h1768, 65u);
      backing.DEF_x__h1768 = DEF_x__h1768;
      vcd_write_val(sim_hdl, num++, DEF_x__h1793, 65u);
      backing.DEF_x__h1793 = DEF_x__h1793;
      vcd_write_val(sim_hdl, num++, DEF_x__h1808, 65u);
      backing.DEF_x__h1808 = DEF_x__h1808;
      vcd_write_val(sim_hdl, num++, DEF_x__h1849, 32u);
      backing.DEF_x__h1849 = DEF_x__h1849;
      vcd_write_val(sim_hdl, num++, DEF_x__h2388, 32u);
      backing.DEF_x__h2388 = DEF_x__h2388;
      vcd_write_val(sim_hdl, num++, DEF_x__h241, 65u);
      backing.DEF_x__h241 = DEF_x__h241;
      vcd_write_val(sim_hdl, num++, DEF_x__h251, 65u);
      backing.DEF_x__h251 = DEF_x__h251;
      vcd_write_val(sim_hdl, num++, DEF_x__h344, 65u);
      backing.DEF_x__h344 = DEF_x__h344;
      vcd_write_val(sim_hdl, num++, DEF_x__h354, 65u);
      backing.DEF_x__h354 = DEF_x__h354;
      vcd_write_val(sim_hdl, num++, DEF_x__h389, 65u);
      backing.DEF_x__h389 = DEF_x__h389;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1309, 32u);
      backing.DEF_x_wget__h1309 = DEF_x_wget__h1309;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h882, 32u);
      backing.DEF_x_wget__h882 = DEF_x_wget__h882;
      vcd_write_val(sim_hdl, num++, DEF_y__h270, 65u);
      backing.DEF_y__h270 = DEF_y__h270;
      vcd_write_val(sim_hdl, num++, DEF_y__h358, 65u);
      backing.DEF_y__h358 = DEF_y__h358;
    }
}

void MOD_mkTbEx7a::vcd_prims(tVCDDumpType dt, MOD_mkTbEx7a &backing)
{
  INST_dut_i.dump_VCD(dt, backing.INST_dut_i);
  INST_dut_m_neg.dump_VCD(dt, backing.INST_dut_m_neg);
  INST_dut_m_pos.dump_VCD(dt, backing.INST_dut_m_pos);
  INST_dut_p.dump_VCD(dt, backing.INST_dut_p);
  INST_tb_cycle.dump_VCD(dt, backing.INST_tb_cycle);
  INST_tb_feed_count.dump_VCD(dt, backing.INST_tb_feed_count);
  INST_tb_operands_fifo.dump_VCD(dt, backing.INST_tb_operands_fifo);
  INST_tb_randomA_ignore.dump_VCD(dt, backing.INST_tb_randomA_ignore);
  INST_tb_randomA_initialized.dump_VCD(dt, backing.INST_tb_randomA_initialized);
  INST_tb_randomA_zaz.dump_VCD(dt, backing.INST_tb_randomA_zaz);
  INST_tb_randomB_ignore.dump_VCD(dt, backing.INST_tb_randomB_ignore);
  INST_tb_randomB_initialized.dump_VCD(dt, backing.INST_tb_randomB_initialized);
  INST_tb_randomB_zaz.dump_VCD(dt, backing.INST_tb_randomB_zaz);
  INST_tb_read_count.dump_VCD(dt, backing.INST_tb_read_count);
}
