/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Apr  4 10:38:17 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbEx7b.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbEx7b::MODEL_mkTbEx7b()
{
  mkTbEx7b_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbEx7b()
{
  MODEL_mkTbEx7b *model = new MODEL_mkTbEx7b();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbEx7b &INST_top = *((MOD_mkTbEx7b *)(instance_ptr));
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbEx7b::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbEx7b_instance = new MOD_mkTbEx7b(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbEx7b_instance->set_clk_0)("CLK");
}
void MODEL_mkTbEx7b::destroy_model()
{
  delete mkTbEx7b_instance;
  mkTbEx7b_instance = NULL;
}
void MODEL_mkTbEx7b::reset_model(bool asserted)
{
  (mkTbEx7b_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbEx7b::get_instance()
{
  return mkTbEx7b_instance;
}

/* Fill in version numbers */
void MODEL_mkTbEx7b::get_version(unsigned int *year,
				 unsigned int *month,
				 char const **annotation,
				 char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "14ff62d";
}

/* Get the model creation time */
time_t MODEL_mkTbEx7b::get_creation_time()
{
  
  /* Sat Apr  4 02:38:17 UTC 2026 */
  return 1775270297llu;
}

/* State dumping function */
void MODEL_mkTbEx7b::dump_state()
{
  (mkTbEx7b_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbEx7b & mkTbEx7b_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbEx7b *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbEx7b(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbEx7b::dump_VCD_defs()
{
  (mkTbEx7b_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbEx7b::dump_VCD(tVCDDumpType dt)
{
  (mkTbEx7b_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbEx7b_backing(sim_hdl));
}
