/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr 26 09:32:47 CST 2026
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbBypassFunctional_h__
#define __mkTbBypassFunctional_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbBypassFunctional module */
class MOD_mkTbBypassFunctional : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_fifo_data_0_m_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_data_0_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_0_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_data_0_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_data_0_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo_data_0_m_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_0_m_wires_1;
  MOD_Reg<tUInt8> INST_fifo_data_1_m_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_data_1_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_1_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_data_1_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_data_1_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo_data_1_m_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_1_m_wires_1;
  MOD_Reg<tUInt8> INST_fifo_data_2_m_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_data_2_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_2_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_data_2_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_data_2_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo_data_2_m_wires_0;
  MOD_Wire<tUInt8> INST_fifo_data_2_m_wires_1;
  MOD_Reg<tUInt8> INST_fifo_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_deqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo_deqP_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqP_wires_1;
  MOD_Reg<tUInt8> INST_fifo_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_2;
  MOD_Reg<tUInt8> INST_fifo_last_write_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_last_write_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_last_write_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_last_write_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_last_write_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_last_write_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_last_write_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_last_write_wires_0;
  MOD_Wire<tUInt8> INST_fifo_last_write_wires_1;
  MOD_Wire<tUInt8> INST_fifo_last_write_wires_2;
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt32> INST_m_input_count;
  MOD_Reg<tUInt32> INST_m_output_count;
  MOD_Wire<tUInt8> INST_m_randomA_ignore;
  MOD_Reg<tUInt8> INST_m_randomA_initialized;
  MOD_Wire<tUInt8> INST_m_randomA_zaz;
  MOD_Wire<tUInt8> INST_m_randomB_ignore;
  MOD_Reg<tUInt8> INST_m_randomB_initialized;
  MOD_Wire<tUInt8> INST_m_randomB_zaz;
  MOD_Wire<tUInt8> INST_m_randomC_ignore;
  MOD_Reg<tUInt8> INST_m_randomC_initialized;
  MOD_Wire<tUInt8> INST_m_randomC_zaz;
  MOD_Wire<tUInt8> INST_m_randomData_ignore;
  MOD_Reg<tUInt8> INST_m_randomData_initialized;
  MOD_Wire<tUInt8> INST_m_randomData_zaz;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_ehrReg;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_2;
  MOD_Reg<tUInt32> INST_m_ref_fifo_enq_req_ehrReg;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_2;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_0;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_2;
  MOD_Reg<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ehrReg;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1;
  MOD_Fifo<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_2_1;
 
 /* Constructor */
 public:
  MOD_mkTbBypassFunctional(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_WILL_FIRE_RL_m_stop_tb;
  tUInt8 DEF_CAN_FIRE_RL_m_stop_tb;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_WILL_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_CAN_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_WILL_FIRE_RL_m_check_outputs;
  tUInt8 DEF_CAN_FIRE_RL_m_check_outputs;
  tUInt8 DEF_WILL_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_CAN_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_WILL_FIRE_RL_m_init;
  tUInt8 DEF_CAN_FIRE_RL_m_init;
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_print;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_print;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_last_write_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_last_write_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_enqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_data_2_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_data_2_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_data_1_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_data_1_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_data_0_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_data_0_m_canonicalize;
  tUInt8 DEF_IF_fifo_enqP_virtual_reg_2_read__40_OR_fifo_en_ETC___d292;
  tUInt8 DEF_fifo_last_write_ehrReg__h5600;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d108;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d284;
  tUInt8 DEF_v__h17128;
  tUInt8 DEF_fifo_last_write_virtual_reg_1_read____d255;
  tUInt8 DEF_fifo_last_write_virtual_reg_2_read____d254;
  tUInt8 DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d181;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d115;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d114;
  tUInt32 DEF_x__h25318;
  tUInt32 DEF_x__h25466;
  tUInt32 DEF_m_ref_fifo_enq_req_wires_1_wget____d155;
  tUInt32 DEF_m_ref_fifo_enq_req_wires_0_wget____d158;
  tUInt32 DEF_m_ref_fifo_enq_req_ehrReg___d160;
  tUInt32 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d56;
  tUInt32 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d58;
  tUInt8 DEF_def__h24929;
  tUInt8 DEF_def__h24553;
  tUInt8 DEF_def__h24397;
  tUInt8 DEF_x_wget__h17380;
  tUInt8 DEF_x_wget__h16991;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_1_whas____d154;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_0_whas____d157;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d280;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d105;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d106;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h10780;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h9944;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d120;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d121;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d83;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d84;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d85;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d55;
  tUInt8 DEF_fifo_enqP_virtual_reg_2_read____d240;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d226;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d227;
  tUInt8 DEF_fifo_last_write_wires_0_whas____d43;
  tUInt8 DEF_fifo_last_write_wires_0_wget____d44;
  tUInt8 DEF_fifo_enqP_virtual_reg_1_read____d241;
  tUInt8 DEF_m_ref_fifo_enq_req_ehrReg_60_BIT_8___d161;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_0_wget__58_BIT_8___d159;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_1_wget__55_BIT_8___d156;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_8_BIT_8___d59;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__6_BIT_8___d57;
  tUInt8 DEF_y__h22073;
  tUInt8 DEF_x__h22072;
  tUInt8 DEF_IF_fifo_enqP_wires_0_whas__6_THEN_fifo_enqP_wi_ETC___d29;
  tUInt8 DEF_n__read__h23126;
  tUInt8 DEF_IF_m_ref_fifo_elem_count_wires_0_whas__45_THEN_ETC___d148;
  tUInt8 DEF_n__read__h21386;
  tUInt8 DEF_v__h17517;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d101;
  tUInt8 DEF_NOT_fifo_last_write_ehrReg_5___d257;
  tUInt8 DEF_m_input_count_37_EQ_1024___d355;
  tUInt8 DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__2_ETC___d278;
  tUInt8 DEF_IF_m_randomB_zaz_whas__06_THEN_m_randomB_zaz_w_ETC___d275;
  tUInt8 DEF_IF_m_randomA_zaz_whas__99_THEN_m_randomA_zaz_w_ETC___d225;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d279;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d233;
  tUInt8 DEF_IF_fifo_enqP_virtual_reg_2_read__40_OR_fifo_en_ETC___d347;
 
 /* Local definitions */
 private:
  tUInt8 DEF_NOT_IF_fifo_enqP_virtual_reg_2_read__40_OR_fif_ETC___d298;
  tUInt8 DEF_NOT_IF_fifo_enqP_virtual_reg_2_read__40_OR_fif_ETC___d261;
  tUInt8 DEF_IF_fifo_enqP_virtual_reg_2_read__40_OR_fifo_en_ETC___d252;
  tUInt8 DEF_NOT_m_ref_fifo_fake_bypass_fifo_virtual_reg_1__ETC___d312;
  tUInt8 DEF_x__h19473;
  tUInt8 DEF_fifo_last_write_virtual_reg_0_read____d256;
  tUInt32 DEF_v__h18214;
  tUInt32 DEF_v__h17824;
  tUInt32 DEF_v__h17437;
  tUInt32 DEF_v__h17048;
  tUInt32 DEF_x__h24196;
  tUInt8 DEF_def__h23958;
  tUInt8 DEF_def__h23085;
  tUInt8 DEF_def__h23020;
  tUInt8 DEF_def__h22955;
  tUInt8 DEF_x_wget__h18157;
  tUInt8 DEF_x_wget__h17767;
  tUInt8 DEF_x__h15643;
  tUInt8 DEF_x__h15644;
  tUInt8 DEF_x__h15645;
  tUInt8 DEF_x__h7011;
  tUInt8 DEF_x__h7012;
  tUInt8 DEF_n__read__h22902;
  tUInt8 DEF_n__read__h22904;
  tUInt8 DEF_n__read__h22906;
  tUInt8 DEF_b__h22052;
  tUInt8 DEF_IF_m_ref_fifo_enq_req_wires_0_whas__57_THEN_m__ETC___d176;
  tUInt8 DEF_x_first__h13353;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_2_whas__ETC___d94;
  tUInt8 DEF_x_first__h16690;
  tUInt8 DEF_IF_fifo_data_2_m_wires_0_whas__7_THEN_fifo_dat_ETC___d20;
  tUInt8 DEF_IF_fifo_data_1_m_wires_0_whas__0_THEN_fifo_dat_ETC___d13;
  tUInt8 DEF_IF_fifo_data_0_m_wires_0_whas_THEN_fifo_data_0_ETC___d6;
  tUInt8 DEF_v__h18294;
  tUInt8 DEF_IF_m_ref_fifo_enq_req_wires_1_whas__54_THEN_m__ETC___d177;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_whas__5_ETC___d74;
  tUInt8 DEF_v__h17904;
  tUInt8 DEF_x__h24882;
  tUInt8 DEF_x__h24526;
  tUInt8 DEF_x__h24350;
  tUInt8 DEF_IF_m_ref_fifo_enq_req_wires_1_whas__54_THEN_m__ETC___d163;
  tUInt8 DEF_IF_m_ref_fifo_enq_req_wires_0_whas__57_THEN_m__ETC___d162;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas__ETC___d86;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_whas__5_ETC___d60;
  tUInt8 DEF_IF_fifo_last_write_wires_1_whas__1_THEN_fifo_l_ETC___d47;
  tUInt8 DEF_IF_fifo_last_write_wires_0_whas__3_THEN_fifo_l_ETC___d46;
  tUInt32 DEF__0_CONCAT_DONTCARE___d138;
  tUInt8 DEF_NOT_fifo_last_write_virtual_reg_2_read__54___d294;
  tUInt8 DEF_NOT_fifo_last_write_virtual_reg_1_read__55___d295;
 
 /* Rules */
 public:
  void RL_fifo_data_0_m_canonicalize();
  void RL_fifo_data_1_m_canonicalize();
  void RL_fifo_data_2_m_canonicalize();
  void RL_fifo_enqP_canonicalize();
  void RL_fifo_deqP_canonicalize();
  void RL_fifo_last_write_canonicalize();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4();
  void RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one();
  void RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two();
  void RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize();
  void RL_m_ref_fifo_elem_count_canonicalize();
  void RL_m_ref_fifo_enq_req_canonicalize();
  void RL_m_ref_fifo_canonicalize();
  void RL_m_randomA_every();
  void RL_m_randomA_every_1();
  void RL_m_randomB_every();
  void RL_m_randomB_every_1();
  void RL_m_randomC_every();
  void RL_m_randomC_every_1();
  void RL_m_randomData_every();
  void RL_m_randomData_every_1();
  void RL_m_cycle_print();
  void RL_m_init();
  void RL_m_feed_inputs();
  void RL_m_check_outputs();
  void RL_m_maybe_clear();
  void RL_m_check_fifos_not_full();
  void RL_m_check_fifos_not_empty();
  void RL_m_check_fifos_first();
  void RL_m_stop_tb();
  void RL_m_cycle_inc();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbBypassFunctional &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbBypassFunctional &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbBypassFunctional &backing);
};

#endif /* ifndef __mkTbBypassFunctional_h__ */
