/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr 19 23:50:48 CST 2026
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbCFScheduling_h__
#define __mkTbCFScheduling_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbCFScheduling module */
class MOD_mkTbCFScheduling : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_deq_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_deq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_deq_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_deq_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_deq_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_ehrReg;
  MOD_Reg<tUInt32> INST_m_fifo_1_ehr_enq_ehrReg;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_ignored_wires_1;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_enq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_enq_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_enq_virtual_reg_2;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_wires_1;
  MOD_Wire<tUInt32> INST_m_fifo_1_ehr_enq_wires_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_deq_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_deq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_deq_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_deq_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_deq_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_ehrReg;
  MOD_Reg<tUInt32> INST_m_fifo_2_ehr_enq_ehrReg;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_ignored_wires_1;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_enq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_enq_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_enq_virtual_reg_2;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_wires_1;
  MOD_Wire<tUInt32> INST_m_fifo_2_ehr_enq_wires_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_2;
 
 /* Constructor */
 public:
  MOD_mkTbCFScheduling(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_WILL_FIRE_RL_m_enq_fifo_2;
  tUInt8 DEF_CAN_FIRE_RL_m_enq_fifo_2;
  tUInt8 DEF_WILL_FIRE_RL_m_deq_fifo_2;
  tUInt8 DEF_CAN_FIRE_RL_m_deq_fifo_2;
  tUInt8 DEF_WILL_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_ehr_deq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_ehr_deq_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_ehr_enq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_ehr_enq_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_ehr_deq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_ehr_deq_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_ehr_enq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_ehr_enq_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize;
 
 /* Local definitions */
 private:
  tUInt8 DEF_IF_m_fifo_2_ehr_enq_wires_1_whas__18_THEN_m_fi_ETC___d127;
  tUInt8 DEF_IF_m_fifo_2_ehr_deq_wires_1_whas__47_THEN_m_fi_ETC___d153;
  tUInt8 DEF_IF_m_fifo_1_ehr_enq_wires_1_whas__8_THEN_m_fif_ETC___d37;
  tUInt8 DEF_IF_m_fifo_1_ehr_deq_wires_1_whas__7_THEN_m_fif_ETC___d63;
  tUInt32 DEF_m_fifo_2_ehr_enq_wires_1_wget____d119;
  tUInt32 DEF_m_fifo_2_ehr_enq_wires_0_wget____d122;
  tUInt32 DEF_m_fifo_2_ehr_enq_ehrReg___d124;
  tUInt32 DEF_m_fifo_1_ehr_enq_wires_1_wget____d29;
  tUInt32 DEF_m_fifo_1_ehr_enq_wires_0_wget____d32;
  tUInt32 DEF_m_fifo_1_ehr_enq_ehrReg___d34;
  tUInt8 DEF_def__h23393;
  tUInt8 DEF_def__h21777;
  tUInt8 DEF_m_fifo_2_deqP_ehrReg___d102;
  tUInt8 DEF_m_fifo_2_enqP_ehrReg___d95;
  tUInt8 DEF_m_fifo_1_deqP_ehrReg___d12;
  tUInt8 DEF_m_fifo_1_enqP_ehrReg___d5;
  tUInt8 DEF_m_fifo_2_ehr_deq_ehrReg__h14257;
  tUInt8 DEF_m_fifo_2_ehr_enq_wires_1_whas____d118;
  tUInt8 DEF_m_fifo_2_ehr_enq_wires_0_whas____d121;
  tUInt8 DEF_m_fifo_1_ehr_deq_ehrReg__h5351;
  tUInt8 DEF_m_fifo_1_ehr_enq_wires_1_whas____d28;
  tUInt8 DEF_m_fifo_1_ehr_enq_wires_0_whas____d31;
  tUInt8 DEF_m_fifo_2_ehr_virtual_reg_2_read____d242;
  tUInt8 DEF_m_fifo_2_ehr_virtual_reg_1_read____d243;
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_2_read____d200;
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_1_read____d201;
  tUInt8 DEF_m_fifo_2_last_write_virtual_reg_2_read____d257;
  tUInt8 DEF_m_fifo_2_last_write_virtual_reg_1_read____d259;
  tUInt8 DEF_m_fifo_2_last_write_virtual_reg_0_read____d261;
  tUInt8 DEF_m_fifo_2_last_write_ehrReg__h11896;
  tUInt8 DEF_m_fifo_2_deqP_virtual_reg_1_read____d173;
  tUInt8 DEF_m_fifo_2_enqP_virtual_reg_1_read____d155;
  tUInt8 DEF_m_fifo_1_last_write_virtual_reg_2_read____d215;
  tUInt8 DEF_m_fifo_1_last_write_virtual_reg_1_read____d216;
  tUInt8 DEF_m_fifo_1_last_write_virtual_reg_0_read____d217;
  tUInt8 DEF_m_fifo_1_last_write_ehrReg__h2988;
  tUInt8 DEF_m_fifo_1_deqP_virtual_reg_1_read____d83;
  tUInt8 DEF_m_fifo_1_enqP_virtual_reg_1_read____d65;
  tUInt8 DEF_x__h13163;
  tUInt8 DEF_x__h13164;
  tUInt8 DEF_x__h13165;
  tUInt8 DEF_x__h4257;
  tUInt8 DEF_x__h4258;
  tUInt8 DEF_x__h4259;
  tUInt8 DEF_m_fifo_2_ehr_enq_ehrReg_24_BIT_8___d125;
  tUInt8 DEF_m_fifo_1_ehr_enq_ehrReg_4_BIT_8___d35;
  tUInt8 DEF_n__read__h20656;
  tUInt8 DEF_n__read__h22277;
  tUInt8 DEF_IF_m_fifo_2_ehr_enq_wires_1_whas__18_THEN_m_fi_ETC___d141;
  tUInt8 DEF_IF_m_fifo_1_ehr_enq_wires_1_whas__8_THEN_m_fif_ETC___d51;
  tUInt8 DEF_IF_m_fifo_2_ehr_wires_0_whas__94_THEN_m_fifo_2_ETC___d197;
  tUInt8 DEF_n__read__h22210;
  tUInt8 DEF_IF_m_fifo_1_ehr_wires_0_whas__84_THEN_m_fifo_1_ETC___d187;
  tUInt8 DEF_n__read__h20589;
  tUInt8 DEF_IF_m_fifo_2_deqP_wires_0_whas__00_THEN_m_fifo__ETC___d103;
  tUInt8 DEF_IF_m_fifo_2_enqP_wires_0_whas__3_THEN_m_fifo_2_ETC___d96;
  tUInt8 DEF_IF_m_fifo_1_deqP_wires_0_whas__0_THEN_m_fifo_1_ETC___d13;
  tUInt8 DEF_IF_m_fifo_1_enqP_wires_0_whas_THEN_m_fifo_1_en_ETC___d6;
  tUInt8 DEF_IF_m_fifo_2_last_write_wires_1_whas__07_THEN_m_ETC___d113;
  tUInt8 DEF_IF_m_fifo_2_last_write_wires_0_whas__09_THEN_m_ETC___d112;
  tUInt8 DEF_IF_m_fifo_1_last_write_wires_1_whas__7_THEN_m__ETC___d23;
  tUInt8 DEF_IF_m_fifo_1_last_write_wires_0_whas__9_THEN_m__ETC___d22;
  tUInt32 DEF__0_CONCAT_DONTCARE___d88;
  tUInt8 DEF_NOT_IF_m_fifo_2_enqP_virtual_reg_1_read__55_OR_ETC___d256;
  tUInt8 DEF_NOT_IF_m_fifo_1_enqP_virtual_reg_1_read__5_OR__ETC___d214;
 
 /* Rules */
 public:
  void RL_m_fifo_1_enqP_canonicalize();
  void RL_m_fifo_1_deqP_canonicalize();
  void RL_m_fifo_1_last_write_canonicalize();
  void RL_m_fifo_1_ehr_enq_canonicalize();
  void RL_m_fifo_1_ehr_deq_canonicalize();
  void RL_m_fifo_1_canonicalize();
  void RL_m_fifo_2_enqP_canonicalize();
  void RL_m_fifo_2_deqP_canonicalize();
  void RL_m_fifo_2_last_write_canonicalize();
  void RL_m_fifo_2_ehr_enq_canonicalize();
  void RL_m_fifo_2_ehr_deq_canonicalize();
  void RL_m_fifo_2_canonicalize();
  void RL_m_fifo_1_ehr_canonicalize();
  void RL_m_fifo_2_ehr_canonicalize();
  void RL_m_enq_fifo_1();
  void RL_m_deq_fifo_1();
  void RL_m_deq_fifo_2();
  void RL_m_enq_fifo_2();
  void RL_m_cycle_stuff();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCFScheduling &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbCFScheduling &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbCFScheduling &backing);
};

#endif /* ifndef __mkTbCFScheduling_h__ */
