/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr 26 09:32:46 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbPipelineScheduling.h"


/* String declarations */
static std::string const __str_literal_4("See the lab documentation and the source code for more details.",
					 63u);
static std::string const __str_literal_2("This testbench is not designed to be run. Instead it is intended to produce",
					 75u);
static std::string const __str_literal_3("compiler warnings based on the scheduling properities of the specified fifo.",
					 76u);
static std::string const __str_literal_1("fifo_2 had %0d", 14u);


/* Constructor */
MOD_mkTbPipelineScheduling::MOD_mkTbPipelineScheduling(tSimStateHdl simHdl,
						       char const *name,
						       Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_m_cycle(simHdl, "m_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_m_fifo_1_data_0(simHdl, "m_fifo_1_data_0", this, 8u),
    INST_m_fifo_1_data_1(simHdl, "m_fifo_1_data_1", this, 8u),
    INST_m_fifo_1_data_2(simHdl, "m_fifo_1_data_2", this, 8u),
    INST_m_fifo_1_deqP_ehrReg(simHdl, "m_fifo_1_deqP_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_1_deqP_ignored_wires_0(simHdl, "m_fifo_1_deqP_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_deqP_ignored_wires_1(simHdl, "m_fifo_1_deqP_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_deqP_ignored_wires_2(simHdl, "m_fifo_1_deqP_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_deqP_virtual_reg_0(simHdl, "m_fifo_1_deqP_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_deqP_virtual_reg_1(simHdl, "m_fifo_1_deqP_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_deqP_virtual_reg_2(simHdl, "m_fifo_1_deqP_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_deqP_wires_0(simHdl, "m_fifo_1_deqP_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_deqP_wires_1(simHdl, "m_fifo_1_deqP_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_deqP_wires_2(simHdl, "m_fifo_1_deqP_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ehrReg(simHdl, "m_fifo_1_ehr_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_0(simHdl, "m_fifo_1_ehr_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_1(simHdl, "m_fifo_1_ehr_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_2(simHdl, "m_fifo_1_ehr_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_0(simHdl, "m_fifo_1_ehr_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_1(simHdl, "m_fifo_1_ehr_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_2(simHdl, "m_fifo_1_ehr_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_0(simHdl, "m_fifo_1_ehr_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_1(simHdl, "m_fifo_1_ehr_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_2(simHdl, "m_fifo_1_ehr_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_enqP_ehrReg(simHdl, "m_fifo_1_enqP_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_1_enqP_ignored_wires_0(simHdl, "m_fifo_1_enqP_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_enqP_ignored_wires_1(simHdl, "m_fifo_1_enqP_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_enqP_virtual_reg_0(simHdl, "m_fifo_1_enqP_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_enqP_virtual_reg_1(simHdl, "m_fifo_1_enqP_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_enqP_wires_0(simHdl, "m_fifo_1_enqP_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_enqP_wires_1(simHdl, "m_fifo_1_enqP_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_last_write_ehrReg(simHdl,
				    "m_fifo_1_last_write_ehrReg",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_m_fifo_1_last_write_ignored_wires_0(simHdl,
					     "m_fifo_1_last_write_ignored_wires_0",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_1_last_write_ignored_wires_1(simHdl,
					     "m_fifo_1_last_write_ignored_wires_1",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_1_last_write_ignored_wires_2(simHdl,
					     "m_fifo_1_last_write_ignored_wires_2",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_1_last_write_virtual_reg_0(simHdl,
					   "m_fifo_1_last_write_virtual_reg_0",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_1_last_write_virtual_reg_1(simHdl,
					   "m_fifo_1_last_write_virtual_reg_1",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_1_last_write_virtual_reg_2(simHdl,
					   "m_fifo_1_last_write_virtual_reg_2",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_1_last_write_wires_0(simHdl, "m_fifo_1_last_write_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_last_write_wires_1(simHdl, "m_fifo_1_last_write_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_last_write_wires_2(simHdl, "m_fifo_1_last_write_wires_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_data_0(simHdl, "m_fifo_2_data_0", this, 8u),
    INST_m_fifo_2_data_1(simHdl, "m_fifo_2_data_1", this, 8u),
    INST_m_fifo_2_data_2(simHdl, "m_fifo_2_data_2", this, 8u),
    INST_m_fifo_2_deqP_ehrReg(simHdl, "m_fifo_2_deqP_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_2_deqP_ignored_wires_0(simHdl, "m_fifo_2_deqP_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_deqP_ignored_wires_1(simHdl, "m_fifo_2_deqP_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_deqP_ignored_wires_2(simHdl, "m_fifo_2_deqP_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_deqP_virtual_reg_0(simHdl, "m_fifo_2_deqP_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_deqP_virtual_reg_1(simHdl, "m_fifo_2_deqP_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_deqP_virtual_reg_2(simHdl, "m_fifo_2_deqP_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_deqP_wires_0(simHdl, "m_fifo_2_deqP_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_deqP_wires_1(simHdl, "m_fifo_2_deqP_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_deqP_wires_2(simHdl, "m_fifo_2_deqP_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ehrReg(simHdl, "m_fifo_2_ehr_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_0(simHdl, "m_fifo_2_ehr_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_1(simHdl, "m_fifo_2_ehr_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_2(simHdl, "m_fifo_2_ehr_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_0(simHdl, "m_fifo_2_ehr_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_1(simHdl, "m_fifo_2_ehr_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_2(simHdl, "m_fifo_2_ehr_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_0(simHdl, "m_fifo_2_ehr_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_1(simHdl, "m_fifo_2_ehr_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_2(simHdl, "m_fifo_2_ehr_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_enqP_ehrReg(simHdl, "m_fifo_2_enqP_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_2_enqP_ignored_wires_0(simHdl, "m_fifo_2_enqP_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_enqP_ignored_wires_1(simHdl, "m_fifo_2_enqP_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_enqP_virtual_reg_0(simHdl, "m_fifo_2_enqP_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_enqP_virtual_reg_1(simHdl, "m_fifo_2_enqP_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_enqP_wires_0(simHdl, "m_fifo_2_enqP_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_enqP_wires_1(simHdl, "m_fifo_2_enqP_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_last_write_ehrReg(simHdl,
				    "m_fifo_2_last_write_ehrReg",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_m_fifo_2_last_write_ignored_wires_0(simHdl,
					     "m_fifo_2_last_write_ignored_wires_0",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_2_last_write_ignored_wires_1(simHdl,
					     "m_fifo_2_last_write_ignored_wires_1",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_2_last_write_ignored_wires_2(simHdl,
					     "m_fifo_2_last_write_ignored_wires_2",
					     this,
					     1u,
					     (tUInt8)0u),
    INST_m_fifo_2_last_write_virtual_reg_0(simHdl,
					   "m_fifo_2_last_write_virtual_reg_0",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_2_last_write_virtual_reg_1(simHdl,
					   "m_fifo_2_last_write_virtual_reg_1",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_2_last_write_virtual_reg_2(simHdl,
					   "m_fifo_2_last_write_virtual_reg_2",
					   this,
					   1u,
					   (tUInt8)0u),
    INST_m_fifo_2_last_write_wires_0(simHdl, "m_fifo_2_last_write_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_last_write_wires_1(simHdl, "m_fifo_2_last_write_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_last_write_wires_2(simHdl, "m_fifo_2_last_write_wires_2", this, 1u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 117u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbPipelineScheduling::init_symbols_0()
{
  init_symbol(&symbols[0u],
	      "CAN_FIRE_RL_m_clear_fifo_2",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_clear_fifo_2,
	      1u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_m_cycle_stuff", SYM_DEF, &DEF_CAN_FIRE_RL_m_cycle_stuff, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_m_deq_fifo_2", SYM_DEF, &DEF_CAN_FIRE_RL_m_deq_fifo_2, 1u);
  init_symbol(&symbols[3u], "CAN_FIRE_RL_m_enq_fifo_2", SYM_DEF, &DEF_CAN_FIRE_RL_m_enq_fifo_2, 1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_m_fifo_1_deqP_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_m_fifo_1_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_m_fifo_1_enqP_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_m_fifo_1_last_write_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize,
	      1u);
  init_symbol(&symbols[8u],
	      "CAN_FIRE_RL_m_fifo_2_deqP_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize,
	      1u);
  init_symbol(&symbols[9u],
	      "CAN_FIRE_RL_m_fifo_2_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[10u],
	      "CAN_FIRE_RL_m_fifo_2_enqP_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize,
	      1u);
  init_symbol(&symbols[11u],
	      "CAN_FIRE_RL_m_fifo_2_last_write_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize,
	      1u);
  init_symbol(&symbols[12u], "m_cycle", SYM_MODULE, &INST_m_cycle);
  init_symbol(&symbols[13u], "m_fifo_1_data_0", SYM_MODULE, &INST_m_fifo_1_data_0);
  init_symbol(&symbols[14u], "m_fifo_1_data_1", SYM_MODULE, &INST_m_fifo_1_data_1);
  init_symbol(&symbols[15u], "m_fifo_1_data_2", SYM_MODULE, &INST_m_fifo_1_data_2);
  init_symbol(&symbols[16u], "m_fifo_1_deqP_ehrReg", SYM_MODULE, &INST_m_fifo_1_deqP_ehrReg);
  init_symbol(&symbols[17u],
	      "m_fifo_1_deqP_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_ignored_wires_0);
  init_symbol(&symbols[18u],
	      "m_fifo_1_deqP_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_ignored_wires_1);
  init_symbol(&symbols[19u],
	      "m_fifo_1_deqP_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_ignored_wires_2);
  init_symbol(&symbols[20u],
	      "m_fifo_1_deqP_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_virtual_reg_0);
  init_symbol(&symbols[21u],
	      "m_fifo_1_deqP_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_virtual_reg_1);
  init_symbol(&symbols[22u],
	      "m_fifo_1_deqP_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_deqP_virtual_reg_2);
  init_symbol(&symbols[23u], "m_fifo_1_deqP_wires_0", SYM_MODULE, &INST_m_fifo_1_deqP_wires_0);
  init_symbol(&symbols[24u], "m_fifo_1_deqP_wires_1", SYM_MODULE, &INST_m_fifo_1_deqP_wires_1);
  init_symbol(&symbols[25u], "m_fifo_1_deqP_wires_2", SYM_MODULE, &INST_m_fifo_1_deqP_wires_2);
  init_symbol(&symbols[26u], "m_fifo_1_ehr_ehrReg", SYM_MODULE, &INST_m_fifo_1_ehr_ehrReg);
  init_symbol(&symbols[27u],
	      "m_fifo_1_ehr_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_0);
  init_symbol(&symbols[28u],
	      "m_fifo_1_ehr_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_1);
  init_symbol(&symbols[29u],
	      "m_fifo_1_ehr_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_2);
  init_symbol(&symbols[30u],
	      "m_fifo_1_ehr_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_0);
  init_symbol(&symbols[31u],
	      "m_fifo_1_ehr_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_1);
  init_symbol(&symbols[32u],
	      "m_fifo_1_ehr_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_2);
  init_symbol(&symbols[33u], "m_fifo_1_ehr_wires_0", SYM_MODULE, &INST_m_fifo_1_ehr_wires_0);
  init_symbol(&symbols[34u], "m_fifo_1_ehr_wires_1", SYM_MODULE, &INST_m_fifo_1_ehr_wires_1);
  init_symbol(&symbols[35u], "m_fifo_1_ehr_wires_2", SYM_MODULE, &INST_m_fifo_1_ehr_wires_2);
  init_symbol(&symbols[36u], "m_fifo_1_enqP_ehrReg", SYM_MODULE, &INST_m_fifo_1_enqP_ehrReg);
  init_symbol(&symbols[37u],
	      "m_fifo_1_enqP_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_enqP_ignored_wires_0);
  init_symbol(&symbols[38u],
	      "m_fifo_1_enqP_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_enqP_ignored_wires_1);
  init_symbol(&symbols[39u],
	      "m_fifo_1_enqP_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_enqP_virtual_reg_0);
  init_symbol(&symbols[40u],
	      "m_fifo_1_enqP_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_enqP_virtual_reg_1);
  init_symbol(&symbols[41u], "m_fifo_1_enqP_wires_0", SYM_MODULE, &INST_m_fifo_1_enqP_wires_0);
  init_symbol(&symbols[42u], "m_fifo_1_enqP_wires_1", SYM_MODULE, &INST_m_fifo_1_enqP_wires_1);
  init_symbol(&symbols[43u],
	      "m_fifo_1_last_write_ehrReg",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_ehrReg);
  init_symbol(&symbols[44u],
	      "m_fifo_1_last_write_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_ignored_wires_0);
  init_symbol(&symbols[45u],
	      "m_fifo_1_last_write_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_ignored_wires_1);
  init_symbol(&symbols[46u],
	      "m_fifo_1_last_write_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_ignored_wires_2);
  init_symbol(&symbols[47u],
	      "m_fifo_1_last_write_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_virtual_reg_0);
  init_symbol(&symbols[48u],
	      "m_fifo_1_last_write_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_virtual_reg_1);
  init_symbol(&symbols[49u],
	      "m_fifo_1_last_write_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_virtual_reg_2);
  init_symbol(&symbols[50u],
	      "m_fifo_1_last_write_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_wires_0);
  init_symbol(&symbols[51u],
	      "m_fifo_1_last_write_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_wires_1);
  init_symbol(&symbols[52u],
	      "m_fifo_1_last_write_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_last_write_wires_2);
  init_symbol(&symbols[53u], "m_fifo_2_data_0", SYM_MODULE, &INST_m_fifo_2_data_0);
  init_symbol(&symbols[54u], "m_fifo_2_data_1", SYM_MODULE, &INST_m_fifo_2_data_1);
  init_symbol(&symbols[55u], "m_fifo_2_data_2", SYM_MODULE, &INST_m_fifo_2_data_2);
  init_symbol(&symbols[56u], "m_fifo_2_deqP_ehrReg", SYM_MODULE, &INST_m_fifo_2_deqP_ehrReg);
  init_symbol(&symbols[57u],
	      "m_fifo_2_deqP_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_ignored_wires_0);
  init_symbol(&symbols[58u],
	      "m_fifo_2_deqP_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_ignored_wires_1);
  init_symbol(&symbols[59u],
	      "m_fifo_2_deqP_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_ignored_wires_2);
  init_symbol(&symbols[60u],
	      "m_fifo_2_deqP_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_virtual_reg_0);
  init_symbol(&symbols[61u],
	      "m_fifo_2_deqP_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_virtual_reg_1);
  init_symbol(&symbols[62u],
	      "m_fifo_2_deqP_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_deqP_virtual_reg_2);
  init_symbol(&symbols[63u], "m_fifo_2_deqP_wires_0", SYM_MODULE, &INST_m_fifo_2_deqP_wires_0);
  init_symbol(&symbols[64u], "m_fifo_2_deqP_wires_1", SYM_MODULE, &INST_m_fifo_2_deqP_wires_1);
  init_symbol(&symbols[65u], "m_fifo_2_deqP_wires_2", SYM_MODULE, &INST_m_fifo_2_deqP_wires_2);
  init_symbol(&symbols[66u], "m_fifo_2_ehr_ehrReg", SYM_MODULE, &INST_m_fifo_2_ehr_ehrReg);
  init_symbol(&symbols[67u],
	      "m_fifo_2_ehr_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_0);
  init_symbol(&symbols[68u],
	      "m_fifo_2_ehr_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_1);
  init_symbol(&symbols[69u],
	      "m_fifo_2_ehr_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_2);
  init_symbol(&symbols[70u],
	      "m_fifo_2_ehr_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_0);
  init_symbol(&symbols[71u],
	      "m_fifo_2_ehr_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_1);
  init_symbol(&symbols[72u],
	      "m_fifo_2_ehr_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_2);
  init_symbol(&symbols[73u], "m_fifo_2_ehr_wires_0", SYM_MODULE, &INST_m_fifo_2_ehr_wires_0);
  init_symbol(&symbols[74u], "m_fifo_2_ehr_wires_1", SYM_MODULE, &INST_m_fifo_2_ehr_wires_1);
  init_symbol(&symbols[75u], "m_fifo_2_ehr_wires_2", SYM_MODULE, &INST_m_fifo_2_ehr_wires_2);
  init_symbol(&symbols[76u], "m_fifo_2_enqP_ehrReg", SYM_MODULE, &INST_m_fifo_2_enqP_ehrReg);
  init_symbol(&symbols[77u],
	      "m_fifo_2_enqP_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_enqP_ignored_wires_0);
  init_symbol(&symbols[78u],
	      "m_fifo_2_enqP_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_enqP_ignored_wires_1);
  init_symbol(&symbols[79u],
	      "m_fifo_2_enqP_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_enqP_virtual_reg_0);
  init_symbol(&symbols[80u],
	      "m_fifo_2_enqP_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_enqP_virtual_reg_1);
  init_symbol(&symbols[81u], "m_fifo_2_enqP_wires_0", SYM_MODULE, &INST_m_fifo_2_enqP_wires_0);
  init_symbol(&symbols[82u], "m_fifo_2_enqP_wires_1", SYM_MODULE, &INST_m_fifo_2_enqP_wires_1);
  init_symbol(&symbols[83u],
	      "m_fifo_2_last_write_ehrReg",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_ehrReg);
  init_symbol(&symbols[84u],
	      "m_fifo_2_last_write_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_ignored_wires_0);
  init_symbol(&symbols[85u],
	      "m_fifo_2_last_write_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_ignored_wires_1);
  init_symbol(&symbols[86u],
	      "m_fifo_2_last_write_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_ignored_wires_2);
  init_symbol(&symbols[87u],
	      "m_fifo_2_last_write_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_virtual_reg_0);
  init_symbol(&symbols[88u],
	      "m_fifo_2_last_write_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_virtual_reg_1);
  init_symbol(&symbols[89u],
	      "m_fifo_2_last_write_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_virtual_reg_2);
  init_symbol(&symbols[90u],
	      "m_fifo_2_last_write_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_wires_0);
  init_symbol(&symbols[91u],
	      "m_fifo_2_last_write_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_wires_1);
  init_symbol(&symbols[92u],
	      "m_fifo_2_last_write_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_last_write_wires_2);
  init_symbol(&symbols[93u], "RL_m_clear_fifo_2", SYM_RULE);
  init_symbol(&symbols[94u], "RL_m_cycle_stuff", SYM_RULE);
  init_symbol(&symbols[95u], "RL_m_deq_fifo_2", SYM_RULE);
  init_symbol(&symbols[96u], "RL_m_enq_fifo_2", SYM_RULE);
  init_symbol(&symbols[97u], "RL_m_fifo_1_deqP_canonicalize", SYM_RULE);
  init_symbol(&symbols[98u], "RL_m_fifo_1_ehr_canonicalize", SYM_RULE);
  init_symbol(&symbols[99u], "RL_m_fifo_1_enqP_canonicalize", SYM_RULE);
  init_symbol(&symbols[100u], "RL_m_fifo_1_last_write_canonicalize", SYM_RULE);
  init_symbol(&symbols[101u], "RL_m_fifo_2_deqP_canonicalize", SYM_RULE);
  init_symbol(&symbols[102u], "RL_m_fifo_2_ehr_canonicalize", SYM_RULE);
  init_symbol(&symbols[103u], "RL_m_fifo_2_enqP_canonicalize", SYM_RULE);
  init_symbol(&symbols[104u], "RL_m_fifo_2_last_write_canonicalize", SYM_RULE);
  init_symbol(&symbols[105u],
	      "WILL_FIRE_RL_m_clear_fifo_2",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_clear_fifo_2,
	      1u);
  init_symbol(&symbols[106u],
	      "WILL_FIRE_RL_m_cycle_stuff",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_cycle_stuff,
	      1u);
  init_symbol(&symbols[107u],
	      "WILL_FIRE_RL_m_deq_fifo_2",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_deq_fifo_2,
	      1u);
  init_symbol(&symbols[108u],
	      "WILL_FIRE_RL_m_enq_fifo_2",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_enq_fifo_2,
	      1u);
  init_symbol(&symbols[109u],
	      "WILL_FIRE_RL_m_fifo_1_deqP_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize,
	      1u);
  init_symbol(&symbols[110u],
	      "WILL_FIRE_RL_m_fifo_1_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[111u],
	      "WILL_FIRE_RL_m_fifo_1_enqP_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize,
	      1u);
  init_symbol(&symbols[112u],
	      "WILL_FIRE_RL_m_fifo_1_last_write_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize,
	      1u);
  init_symbol(&symbols[113u],
	      "WILL_FIRE_RL_m_fifo_2_deqP_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize,
	      1u);
  init_symbol(&symbols[114u],
	      "WILL_FIRE_RL_m_fifo_2_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[115u],
	      "WILL_FIRE_RL_m_fifo_2_enqP_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize,
	      1u);
  init_symbol(&symbols[116u],
	      "WILL_FIRE_RL_m_fifo_2_last_write_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize,
	      1u);
}


/* Rule actions */

void MOD_mkTbPipelineScheduling::RL_m_fifo_1_enqP_canonicalize()
{
  tUInt8 DEF_x__h939;
  tUInt8 DEF_def__h966;
  tUInt8 DEF_def__h1056;
  DEF_def__h1056 = INST_m_fifo_1_enqP_ehrReg.METH_read();
  DEF_def__h966 = INST_m_fifo_1_enqP_wires_0.METH_whas() ? INST_m_fifo_1_enqP_wires_0.METH_wget() : DEF_def__h1056;
  DEF_x__h939 = INST_m_fifo_1_enqP_wires_1.METH_whas() ? INST_m_fifo_1_enqP_wires_1.METH_wget() : DEF_def__h966;
  INST_m_fifo_1_enqP_ehrReg.METH_write(DEF_x__h939);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_1_deqP_canonicalize()
{
  tUInt8 DEF_def__h2125;
  tUInt8 DEF_def__h2007;
  tUInt8 DEF_x__h1973;
  tUInt8 DEF_def__h2143;
  DEF_def__h2143 = INST_m_fifo_1_deqP_ehrReg.METH_read();
  DEF_def__h2125 = INST_m_fifo_1_deqP_wires_0.METH_whas() ? INST_m_fifo_1_deqP_wires_0.METH_wget() : DEF_def__h2143;
  DEF_def__h2007 = INST_m_fifo_1_deqP_wires_1.METH_whas() ? INST_m_fifo_1_deqP_wires_1.METH_wget() : DEF_def__h2125;
  DEF_x__h1973 = INST_m_fifo_1_deqP_wires_2.METH_whas() ? INST_m_fifo_1_deqP_wires_2.METH_wget() : DEF_def__h2007;
  INST_m_fifo_1_deqP_ehrReg.METH_write(DEF_x__h1973);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_1_last_write_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_1_last_write_wires_2_whas__8_THEN_m__ETC___d27;
  tUInt8 DEF_m_fifo_1_last_write_ehrReg__h3263;
  DEF_m_fifo_1_last_write_ehrReg__h3263 = INST_m_fifo_1_last_write_ehrReg.METH_read();
  DEF_IF_m_fifo_1_last_write_wires_2_whas__8_THEN_m__ETC___d27 = INST_m_fifo_1_last_write_wires_2.METH_whas() ? INST_m_fifo_1_last_write_wires_2.METH_wget() : (INST_m_fifo_1_last_write_wires_1.METH_whas() ? INST_m_fifo_1_last_write_wires_1.METH_wget() : (INST_m_fifo_1_last_write_wires_0.METH_whas() ? INST_m_fifo_1_last_write_wires_0.METH_wget() : DEF_m_fifo_1_last_write_ehrReg__h3263));
  INST_m_fifo_1_last_write_ehrReg.METH_write(DEF_IF_m_fifo_1_last_write_wires_2_whas__8_THEN_m__ETC___d27);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_2_enqP_canonicalize()
{
  tUInt8 DEF_x__h4075;
  DEF_def__h12464 = INST_m_fifo_2_enqP_ehrReg.METH_read();
  DEF_x__h12437 = INST_m_fifo_2_enqP_wires_0.METH_whas() ? INST_m_fifo_2_enqP_wires_0.METH_wget() : DEF_def__h12464;
  DEF_x__h4075 = INST_m_fifo_2_enqP_wires_1.METH_whas() ? INST_m_fifo_2_enqP_wires_1.METH_wget() : DEF_x__h12437;
  INST_m_fifo_2_enqP_ehrReg.METH_write(DEF_x__h4075);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_2_deqP_canonicalize()
{
  tUInt8 DEF_x__h5109;
  DEF_def__h12635 = INST_m_fifo_2_deqP_ehrReg.METH_read();
  DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42 = INST_m_fifo_2_deqP_wires_0.METH_whas() ? INST_m_fifo_2_deqP_wires_0.METH_wget() : DEF_def__h12635;
  DEF_x__h12588 = INST_m_fifo_2_deqP_wires_1.METH_whas() ? INST_m_fifo_2_deqP_wires_1.METH_wget() : DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42;
  DEF_x__h5109 = INST_m_fifo_2_deqP_wires_2.METH_whas() ? INST_m_fifo_2_deqP_wires_2.METH_wget() : DEF_x__h12588;
  INST_m_fifo_2_deqP_ehrReg.METH_write(DEF_x__h5109);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_2_last_write_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_2_last_write_wires_2_whas__5_THEN_m__ETC___d54;
  DEF_m_fifo_2_last_write_wires_0_whas____d49 = INST_m_fifo_2_last_write_wires_0.METH_whas();
  DEF_m_fifo_2_last_write_wires_0_wget____d50 = INST_m_fifo_2_last_write_wires_0.METH_wget();
  DEF_m_fifo_2_last_write_ehrReg__h6399 = INST_m_fifo_2_last_write_ehrReg.METH_read();
  DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52 = DEF_m_fifo_2_last_write_wires_0_whas____d49 ? DEF_m_fifo_2_last_write_wires_0_wget____d50 : DEF_m_fifo_2_last_write_ehrReg__h6399;
  DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53 = INST_m_fifo_2_last_write_wires_1.METH_whas() ? INST_m_fifo_2_last_write_wires_1.METH_wget() : DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52;
  DEF_IF_m_fifo_2_last_write_wires_2_whas__5_THEN_m__ETC___d54 = INST_m_fifo_2_last_write_wires_2.METH_whas() ? INST_m_fifo_2_last_write_wires_2.METH_wget() : DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53;
  INST_m_fifo_2_last_write_ehrReg.METH_write(DEF_IF_m_fifo_2_last_write_wires_2_whas__5_THEN_m__ETC___d54);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_1_ehr_canonicalize()
{
  tUInt8 DEF_def__h7497;
  tUInt8 DEF_def__h7379;
  tUInt8 DEF_x__h7345;
  tUInt8 DEF_def__h7515;
  DEF_def__h7515 = INST_m_fifo_1_ehr_ehrReg.METH_read();
  DEF_def__h7497 = INST_m_fifo_1_ehr_wires_0.METH_whas() ? INST_m_fifo_1_ehr_wires_0.METH_wget() : DEF_def__h7515;
  DEF_def__h7379 = INST_m_fifo_1_ehr_wires_1.METH_whas() ? INST_m_fifo_1_ehr_wires_1.METH_wget() : DEF_def__h7497;
  DEF_x__h7345 = INST_m_fifo_1_ehr_wires_2.METH_whas() ? INST_m_fifo_1_ehr_wires_2.METH_wget() : DEF_def__h7379;
  INST_m_fifo_1_ehr_ehrReg.METH_write(DEF_x__h7345);
}

void MOD_mkTbPipelineScheduling::RL_m_fifo_2_ehr_canonicalize()
{
  tUInt8 DEF_x__h8445;
  DEF_def__h12979 = INST_m_fifo_2_ehr_ehrReg.METH_read();
  DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72 = INST_m_fifo_2_ehr_wires_0.METH_whas() ? INST_m_fifo_2_ehr_wires_0.METH_wget() : DEF_def__h12979;
  DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73 = INST_m_fifo_2_ehr_wires_1.METH_whas() ? INST_m_fifo_2_ehr_wires_1.METH_wget() : DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72;
  DEF_x__h8445 = INST_m_fifo_2_ehr_wires_2.METH_whas() ? INST_m_fifo_2_ehr_wires_2.METH_wget() : DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73;
  INST_m_fifo_2_ehr_ehrReg.METH_write(DEF_x__h8445);
}

void MOD_mkTbPipelineScheduling::RL_m_deq_fifo_2()
{
  tUInt8 DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104;
  tUInt8 DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81;
  tUInt8 DEF_x__h10446;
  tUInt8 DEF_IF_IF_m_fifo_2_deqP_virtual_reg_2_read__6_OR_m_ETC___d112;
  tUInt8 DEF_x__h9964;
  tUInt8 DEF_x_first__h6488;
  tUInt8 DEF__read__h3372;
  tUInt8 DEF__read__h3395;
  tUInt8 DEF__read__h3418;
  tUInt8 DEF_x__h8735;
  DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 = INST_m_fifo_2_ehr_virtual_reg_2.METH_read();
  DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 = INST_m_fifo_2_last_write_virtual_reg_1.METH_read();
  DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 = INST_m_fifo_2_last_write_virtual_reg_2.METH_read();
  DEF__read__h3395 = INST_m_fifo_2_data_1.METH_read();
  DEF__read__h3418 = INST_m_fifo_2_data_2.METH_read();
  DEF__read__h3372 = INST_m_fifo_2_data_0.METH_read();
  DEF_def__h12979 = INST_m_fifo_2_ehr_ehrReg.METH_read();
  DEF_def__h12635 = INST_m_fifo_2_deqP_ehrReg.METH_read();
  DEF_def__h12464 = INST_m_fifo_2_enqP_ehrReg.METH_read();
  DEF_x__h10111 = INST_m_fifo_2_enqP_virtual_reg_1.METH_read() || INST_m_fifo_2_enqP_virtual_reg_0.METH_read() ? (tUInt8)0u : DEF_def__h12464;
  DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 = INST_m_fifo_2_ehr_virtual_reg_1.METH_read();
  DEF_x__h8735 = DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 || (DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 || INST_m_fifo_2_ehr_virtual_reg_0.METH_read()) ? (tUInt8)0u : DEF_def__h12979;
  DEF_m_fifo_2_last_write_ehrReg__h6399 = INST_m_fifo_2_last_write_ehrReg.METH_read();
  DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 = INST_m_fifo_2_deqP_virtual_reg_2.METH_read();
  DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 = INST_m_fifo_2_deqP_virtual_reg_1.METH_read();
  DEF_x__h9964 = DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 || (DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 || INST_m_fifo_2_deqP_virtual_reg_0.METH_read()) ? (tUInt8)0u : DEF_def__h12635;
  switch (DEF_x__h9964) {
  case (tUInt8)0u:
    DEF_x_first__h6488 = DEF__read__h3372;
    break;
  case (tUInt8)1u:
    DEF_x_first__h6488 = DEF__read__h3395;
    break;
  case (tUInt8)2u:
    DEF_x_first__h6488 = DEF__read__h3418;
    break;
  default:
    DEF_x_first__h6488 = (tUInt8)170u;
  }
  DEF_x__h10446 = (tUInt8)3u & (DEF_x__h9964 + (tUInt8)1u);
  DEF_IF_IF_m_fifo_2_deqP_virtual_reg_2_read__6_OR_m_ETC___d112 = DEF_x__h9964 == (tUInt8)2u ? (tUInt8)0u : DEF_x__h10446;
  DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81 = DEF_x__h8735 == (tUInt8)0u;
  DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104 = DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81 && (!(DEF_x__h10111 == DEF_x__h9964) || (!DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 && (!DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 && (!INST_m_fifo_2_last_write_virtual_reg_0.METH_read() && DEF_m_fifo_2_last_write_ehrReg__h6399))));
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
      dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_x_first__h6488);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_deqP_wires_0.METH_wset(DEF_IF_IF_m_fifo_2_deqP_virtual_reg_2_read__6_OR_m_ETC___d112);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_deqP_ignored_wires_0.METH_wset(DEF_def__h12635);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_deqP_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_last_write_wires_0.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_last_write_ignored_wires_0.METH_wset(DEF_m_fifo_2_last_write_ehrReg__h6399);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d104)
    INST_m_fifo_2_last_write_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81)
    INST_m_fifo_2_ehr_wires_0.METH_wset((tUInt8)1u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81)
    INST_m_fifo_2_ehr_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d81)
    INST_m_fifo_2_ehr_ignored_wires_0.METH_wset(DEF_def__h12979);
}

void MOD_mkTbPipelineScheduling::RL_m_enq_fifo_2()
{
  tUInt8 DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d128;
  tUInt8 DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d130;
  tUInt8 DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127;
  tUInt8 DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d132;
  tUInt8 DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116;
  tUInt8 DEF_n__read__h11171;
  tUInt8 DEF_x__h11758;
  tUInt8 DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d131;
  tUInt8 DEF_IF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_ETC___d134;
  tUInt8 DEF_x__h11045;
  DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 = INST_m_fifo_2_ehr_virtual_reg_2.METH_read();
  DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 = INST_m_fifo_2_last_write_virtual_reg_1.METH_read();
  DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 = INST_m_fifo_2_last_write_virtual_reg_2.METH_read();
  DEF_def__h12979 = INST_m_fifo_2_ehr_ehrReg.METH_read();
  DEF_def__h12635 = INST_m_fifo_2_deqP_ehrReg.METH_read();
  DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 = INST_m_fifo_2_ehr_virtual_reg_1.METH_read();
  DEF_def__h12464 = INST_m_fifo_2_enqP_ehrReg.METH_read();
  DEF_x__h10111 = INST_m_fifo_2_enqP_virtual_reg_1.METH_read() || INST_m_fifo_2_enqP_virtual_reg_0.METH_read() ? (tUInt8)0u : DEF_def__h12464;
  DEF_m_fifo_2_last_write_wires_0_whas____d49 = INST_m_fifo_2_last_write_wires_0.METH_whas();
  DEF_m_fifo_2_last_write_wires_0_wget____d50 = INST_m_fifo_2_last_write_wires_0.METH_wget();
  DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 = INST_m_fifo_2_deqP_virtual_reg_2.METH_read();
  DEF_m_fifo_2_last_write_ehrReg__h6399 = INST_m_fifo_2_last_write_ehrReg.METH_read();
  DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 = INST_m_fifo_2_deqP_virtual_reg_1.METH_read();
  DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d131 = DEF_x__h10111 == (tUInt8)2u;
  DEF_x__h11758 = (tUInt8)3u & (DEF_x__h10111 + (tUInt8)1u);
  DEF_IF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_ETC___d134 = DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d131 ? (tUInt8)0u : DEF_x__h11758;
  DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42 = INST_m_fifo_2_deqP_wires_0.METH_whas() ? INST_m_fifo_2_deqP_wires_0.METH_wget() : DEF_def__h12635;
  DEF_n__read__h11171 = DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 || DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 ? (tUInt8)0u : DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42;
  DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72 = INST_m_fifo_2_ehr_wires_0.METH_whas() ? INST_m_fifo_2_ehr_wires_0.METH_wget() : DEF_def__h12979;
  DEF_x__h11045 = DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 || DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 ? (tUInt8)0u : DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72;
  DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52 = DEF_m_fifo_2_last_write_wires_0_whas____d49 ? DEF_m_fifo_2_last_write_wires_0_wget____d50 : DEF_m_fifo_2_last_write_ehrReg__h6399;
  DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116 = DEF_x__h11045 == (tUInt8)1u;
  DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127 = DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116 && (!(DEF_x__h10111 == DEF_n__read__h11171) || (DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 || (DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 || (DEF_m_fifo_2_last_write_wires_0_whas____d49 ? !DEF_m_fifo_2_last_write_wires_0_wget____d50 : !DEF_m_fifo_2_last_write_ehrReg__h6399))));
  DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d132 = DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d131 && DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127;
  DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d130 = DEF_x__h10111 == (tUInt8)1u && DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127;
  DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d128 = DEF_x__h10111 == (tUInt8)0u && DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127;
  if (DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d128)
    INST_m_fifo_2_data_0.METH_write((tUInt8)2u);
  if (DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d130)
    INST_m_fifo_2_data_1.METH_write((tUInt8)2u);
  if (DEF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_fi_ETC___d132)
    INST_m_fifo_2_data_2.METH_write((tUInt8)2u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_enqP_wires_0.METH_wset(DEF_IF_IF_m_fifo_2_enqP_virtual_reg_1_read__2_OR_m_ETC___d134);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_enqP_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_enqP_ignored_wires_0.METH_wset(DEF_def__h12464);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_last_write_wires_1.METH_wset((tUInt8)1u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_last_write_ignored_wires_1.METH_wset(DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d127)
    INST_m_fifo_2_last_write_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116)
    INST_m_fifo_2_ehr_wires_1.METH_wset((tUInt8)2u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116)
    INST_m_fifo_2_ehr_ignored_wires_1.METH_wset(DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_OR_m_fif_ETC___d116)
    INST_m_fifo_2_ehr_virtual_reg_1.METH_write((tUInt8)0u);
}

void MOD_mkTbPipelineScheduling::RL_m_clear_fifo_2()
{
  tUInt8 DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136;
  tUInt8 DEF_x__h12241;
  DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 = INST_m_fifo_2_ehr_virtual_reg_2.METH_read();
  DEF_def__h12979 = INST_m_fifo_2_ehr_ehrReg.METH_read();
  DEF_def__h12635 = INST_m_fifo_2_deqP_ehrReg.METH_read();
  DEF_def__h12464 = INST_m_fifo_2_enqP_ehrReg.METH_read();
  DEF_m_fifo_2_last_write_wires_0_wget____d50 = INST_m_fifo_2_last_write_wires_0.METH_wget();
  DEF_m_fifo_2_last_write_wires_0_whas____d49 = INST_m_fifo_2_last_write_wires_0.METH_whas();
  DEF_m_fifo_2_last_write_ehrReg__h6399 = INST_m_fifo_2_last_write_ehrReg.METH_read();
  DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42 = INST_m_fifo_2_deqP_wires_0.METH_whas() ? INST_m_fifo_2_deqP_wires_0.METH_wget() : DEF_def__h12635;
  DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72 = INST_m_fifo_2_ehr_wires_0.METH_whas() ? INST_m_fifo_2_ehr_wires_0.METH_wget() : DEF_def__h12979;
  DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73 = INST_m_fifo_2_ehr_wires_1.METH_whas() ? INST_m_fifo_2_ehr_wires_1.METH_wget() : DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72;
  DEF_x__h12241 = DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 ? (tUInt8)0u : DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73;
  DEF_x__h12588 = INST_m_fifo_2_deqP_wires_1.METH_whas() ? INST_m_fifo_2_deqP_wires_1.METH_wget() : DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42;
  DEF_x__h12437 = INST_m_fifo_2_enqP_wires_0.METH_whas() ? INST_m_fifo_2_enqP_wires_0.METH_wget() : DEF_def__h12464;
  DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52 = DEF_m_fifo_2_last_write_wires_0_whas____d49 ? DEF_m_fifo_2_last_write_wires_0_wget____d50 : DEF_m_fifo_2_last_write_ehrReg__h6399;
  DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53 = INST_m_fifo_2_last_write_wires_1.METH_whas() ? INST_m_fifo_2_last_write_wires_1.METH_wget() : DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52;
  DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136 = DEF_x__h12241 == (tUInt8)2u;
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_enqP_wires_1.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_enqP_ignored_wires_1.METH_wset(DEF_x__h12437);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_enqP_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_deqP_ignored_wires_2.METH_wset(DEF_x__h12588);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_deqP_wires_2.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_deqP_virtual_reg_2.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_last_write_wires_2.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_last_write_ignored_wires_2.METH_wset(DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_last_write_virtual_reg_2.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_ehr_wires_2.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_ehr_virtual_reg_2.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_2_ehr_virtual_reg_2_read__5_THEN_0_E_ETC___d136)
    INST_m_fifo_2_ehr_ignored_wires_2.METH_wset(DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73);
}

void MOD_mkTbPipelineScheduling::RL_m_cycle_stuff()
{
  tUInt32 DEF_x__h13219;
  tUInt8 DEF_m_cycle_37_EQ_5___d138;
  tUInt32 DEF__read__h61;
  DEF__read__h61 = INST_m_cycle.METH_read();
  DEF_m_cycle_37_EQ_5___d138 = DEF__read__h61 == 5u;
  DEF_x__h13219 = DEF__read__h61 + 1u;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_m_cycle_37_EQ_5___d138)
      dollar_display(sim_hdl, this, "s", &__str_literal_2);
    if (DEF_m_cycle_37_EQ_5___d138)
      dollar_display(sim_hdl, this, "s", &__str_literal_3);
    if (DEF_m_cycle_37_EQ_5___d138)
      dollar_display(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_m_cycle_37_EQ_5___d138)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_m_cycle.METH_write(DEF_x__h13219);
}


/* Methods */


/* Reset routines */

void MOD_mkTbPipelineScheduling::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_m_fifo_2_last_write_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_2_enqP_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_2_ehr_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_2_deqP_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_last_write_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_enqP_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_ehr_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_deqP_ehrReg.reset_RST(ARG_rst_in);
  INST_m_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbPipelineScheduling::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbPipelineScheduling::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_m_cycle.dump_state(indent + 2u);
  INST_m_fifo_1_data_0.dump_state(indent + 2u);
  INST_m_fifo_1_data_1.dump_state(indent + 2u);
  INST_m_fifo_1_data_2.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_deqP_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_enqP_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_last_write_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_data_0.dump_state(indent + 2u);
  INST_m_fifo_2_data_1.dump_state(indent + 2u);
  INST_m_fifo_2_data_2.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_deqP_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_enqP_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_last_write_wires_2.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbPipelineScheduling::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 126u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_clear_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_cycle_stuff", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_deq_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_enq_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_deqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_enqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_last_write_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_deqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_enqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_last_write_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_clear_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_cycle_stuff", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_deq_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_enq_fifo_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_deqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_enqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_last_write_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_deqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_enqP_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_last_write_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "def__h12464", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "def__h12635", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "def__h12979", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_deqP_virtual_reg_1_read____d87", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_deqP_virtual_reg_2_read____d86", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_ehr_virtual_reg_1_read____d76", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_ehr_virtual_reg_2_read____d75", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_last_write_ehrReg__h6399", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_last_write_virtual_reg_1_read____d96", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_last_write_virtual_reg_2_read____d94", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_last_write_wires_0_wget____d50", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_2_last_write_wires_0_whas____d49", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h10111", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h12437", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h12588", 2u);
  num = INST_m_cycle.dump_VCD_defs(num);
  num = INST_m_fifo_1_data_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_data_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_data_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_deqP_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_enqP_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_last_write_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_data_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_data_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_data_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_deqP_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_enqP_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_last_write_wires_2.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbPipelineScheduling::dump_VCD(tVCDDumpType dt,
					  unsigned int levels,
					  MOD_mkTbPipelineScheduling &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbPipelineScheduling::vcd_defs(tVCDDumpType dt, MOD_mkTbPipelineScheduling &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_m_clear_fifo_2) != DEF_CAN_FIRE_RL_m_clear_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_clear_fifo_2, 1u);
	backing.DEF_CAN_FIRE_RL_m_clear_fifo_2 = DEF_CAN_FIRE_RL_m_clear_fifo_2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_cycle_stuff) != DEF_CAN_FIRE_RL_m_cycle_stuff)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_cycle_stuff, 1u);
	backing.DEF_CAN_FIRE_RL_m_cycle_stuff = DEF_CAN_FIRE_RL_m_cycle_stuff;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_deq_fifo_2) != DEF_CAN_FIRE_RL_m_deq_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_deq_fifo_2, 1u);
	backing.DEF_CAN_FIRE_RL_m_deq_fifo_2 = DEF_CAN_FIRE_RL_m_deq_fifo_2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_enq_fifo_2) != DEF_CAN_FIRE_RL_m_enq_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_enq_fifo_2, 1u);
	backing.DEF_CAN_FIRE_RL_m_enq_fifo_2 = DEF_CAN_FIRE_RL_m_enq_fifo_2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42) != DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42, 2u);
	backing.DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42 = DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72) != DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72, 2u);
	backing.DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72 = DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73) != DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73, 2u);
	backing.DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73 = DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52) != DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52, 1u);
	backing.DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52 = DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53) != DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53, 1u);
	backing.DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53 = DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_clear_fifo_2) != DEF_WILL_FIRE_RL_m_clear_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_clear_fifo_2, 1u);
	backing.DEF_WILL_FIRE_RL_m_clear_fifo_2 = DEF_WILL_FIRE_RL_m_clear_fifo_2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_cycle_stuff) != DEF_WILL_FIRE_RL_m_cycle_stuff)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_cycle_stuff, 1u);
	backing.DEF_WILL_FIRE_RL_m_cycle_stuff = DEF_WILL_FIRE_RL_m_cycle_stuff;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_deq_fifo_2) != DEF_WILL_FIRE_RL_m_deq_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_deq_fifo_2, 1u);
	backing.DEF_WILL_FIRE_RL_m_deq_fifo_2 = DEF_WILL_FIRE_RL_m_deq_fifo_2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_enq_fifo_2) != DEF_WILL_FIRE_RL_m_enq_fifo_2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_enq_fifo_2, 1u);
	backing.DEF_WILL_FIRE_RL_m_enq_fifo_2 = DEF_WILL_FIRE_RL_m_enq_fifo_2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize;
      }
      ++num;
      if ((backing.DEF_def__h12464) != DEF_def__h12464)
      {
	vcd_write_val(sim_hdl, num, DEF_def__h12464, 2u);
	backing.DEF_def__h12464 = DEF_def__h12464;
      }
      ++num;
      if ((backing.DEF_def__h12635) != DEF_def__h12635)
      {
	vcd_write_val(sim_hdl, num, DEF_def__h12635, 2u);
	backing.DEF_def__h12635 = DEF_def__h12635;
      }
      ++num;
      if ((backing.DEF_def__h12979) != DEF_def__h12979)
      {
	vcd_write_val(sim_hdl, num, DEF_def__h12979, 2u);
	backing.DEF_def__h12979 = DEF_def__h12979;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_deqP_virtual_reg_1_read____d87) != DEF_m_fifo_2_deqP_virtual_reg_1_read____d87)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_deqP_virtual_reg_1_read____d87, 1u);
	backing.DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 = DEF_m_fifo_2_deqP_virtual_reg_1_read____d87;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_deqP_virtual_reg_2_read____d86) != DEF_m_fifo_2_deqP_virtual_reg_2_read____d86)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_deqP_virtual_reg_2_read____d86, 1u);
	backing.DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 = DEF_m_fifo_2_deqP_virtual_reg_2_read____d86;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_ehr_virtual_reg_1_read____d76) != DEF_m_fifo_2_ehr_virtual_reg_1_read____d76)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_ehr_virtual_reg_1_read____d76, 1u);
	backing.DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 = DEF_m_fifo_2_ehr_virtual_reg_1_read____d76;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_ehr_virtual_reg_2_read____d75) != DEF_m_fifo_2_ehr_virtual_reg_2_read____d75)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_ehr_virtual_reg_2_read____d75, 1u);
	backing.DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 = DEF_m_fifo_2_ehr_virtual_reg_2_read____d75;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_last_write_ehrReg__h6399) != DEF_m_fifo_2_last_write_ehrReg__h6399)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_last_write_ehrReg__h6399, 1u);
	backing.DEF_m_fifo_2_last_write_ehrReg__h6399 = DEF_m_fifo_2_last_write_ehrReg__h6399;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_last_write_virtual_reg_1_read____d96) != DEF_m_fifo_2_last_write_virtual_reg_1_read____d96)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_last_write_virtual_reg_1_read____d96, 1u);
	backing.DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 = DEF_m_fifo_2_last_write_virtual_reg_1_read____d96;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_last_write_virtual_reg_2_read____d94) != DEF_m_fifo_2_last_write_virtual_reg_2_read____d94)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_last_write_virtual_reg_2_read____d94, 1u);
	backing.DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 = DEF_m_fifo_2_last_write_virtual_reg_2_read____d94;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_last_write_wires_0_wget____d50) != DEF_m_fifo_2_last_write_wires_0_wget____d50)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_last_write_wires_0_wget____d50, 1u);
	backing.DEF_m_fifo_2_last_write_wires_0_wget____d50 = DEF_m_fifo_2_last_write_wires_0_wget____d50;
      }
      ++num;
      if ((backing.DEF_m_fifo_2_last_write_wires_0_whas____d49) != DEF_m_fifo_2_last_write_wires_0_whas____d49)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_2_last_write_wires_0_whas____d49, 1u);
	backing.DEF_m_fifo_2_last_write_wires_0_whas____d49 = DEF_m_fifo_2_last_write_wires_0_whas____d49;
      }
      ++num;
      if ((backing.DEF_x__h10111) != DEF_x__h10111)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h10111, 2u);
	backing.DEF_x__h10111 = DEF_x__h10111;
      }
      ++num;
      if ((backing.DEF_x__h12437) != DEF_x__h12437)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h12437, 2u);
	backing.DEF_x__h12437 = DEF_x__h12437;
      }
      ++num;
      if ((backing.DEF_x__h12588) != DEF_x__h12588)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h12588, 2u);
	backing.DEF_x__h12588 = DEF_x__h12588;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_clear_fifo_2, 1u);
      backing.DEF_CAN_FIRE_RL_m_clear_fifo_2 = DEF_CAN_FIRE_RL_m_clear_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_cycle_stuff, 1u);
      backing.DEF_CAN_FIRE_RL_m_cycle_stuff = DEF_CAN_FIRE_RL_m_cycle_stuff;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_deq_fifo_2, 1u);
      backing.DEF_CAN_FIRE_RL_m_deq_fifo_2 = DEF_CAN_FIRE_RL_m_deq_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_enq_fifo_2, 1u);
      backing.DEF_CAN_FIRE_RL_m_enq_fifo_2 = DEF_CAN_FIRE_RL_m_enq_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42, 2u);
      backing.DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42 = DEF_IF_m_fifo_2_deqP_wires_0_whas__9_THEN_m_fifo_2_ETC___d42;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72, 2u);
      backing.DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72 = DEF_IF_m_fifo_2_ehr_wires_0_whas__9_THEN_m_fifo_2__ETC___d72;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73, 2u);
      backing.DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73 = DEF_IF_m_fifo_2_ehr_wires_1_whas__7_THEN_m_fifo_2__ETC___d73;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52, 1u);
      backing.DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52 = DEF_IF_m_fifo_2_last_write_wires_0_whas__9_THEN_m__ETC___d52;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53, 1u);
      backing.DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53 = DEF_IF_m_fifo_2_last_write_wires_1_whas__7_THEN_m__ETC___d53;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_clear_fifo_2, 1u);
      backing.DEF_WILL_FIRE_RL_m_clear_fifo_2 = DEF_WILL_FIRE_RL_m_clear_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_cycle_stuff, 1u);
      backing.DEF_WILL_FIRE_RL_m_cycle_stuff = DEF_WILL_FIRE_RL_m_cycle_stuff;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_deq_fifo_2, 1u);
      backing.DEF_WILL_FIRE_RL_m_deq_fifo_2 = DEF_WILL_FIRE_RL_m_deq_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_enq_fifo_2, 1u);
      backing.DEF_WILL_FIRE_RL_m_enq_fifo_2 = DEF_WILL_FIRE_RL_m_enq_fifo_2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_def__h12464, 2u);
      backing.DEF_def__h12464 = DEF_def__h12464;
      vcd_write_val(sim_hdl, num++, DEF_def__h12635, 2u);
      backing.DEF_def__h12635 = DEF_def__h12635;
      vcd_write_val(sim_hdl, num++, DEF_def__h12979, 2u);
      backing.DEF_def__h12979 = DEF_def__h12979;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_deqP_virtual_reg_1_read____d87, 1u);
      backing.DEF_m_fifo_2_deqP_virtual_reg_1_read____d87 = DEF_m_fifo_2_deqP_virtual_reg_1_read____d87;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_deqP_virtual_reg_2_read____d86, 1u);
      backing.DEF_m_fifo_2_deqP_virtual_reg_2_read____d86 = DEF_m_fifo_2_deqP_virtual_reg_2_read____d86;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_ehr_virtual_reg_1_read____d76, 1u);
      backing.DEF_m_fifo_2_ehr_virtual_reg_1_read____d76 = DEF_m_fifo_2_ehr_virtual_reg_1_read____d76;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_ehr_virtual_reg_2_read____d75, 1u);
      backing.DEF_m_fifo_2_ehr_virtual_reg_2_read____d75 = DEF_m_fifo_2_ehr_virtual_reg_2_read____d75;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_last_write_ehrReg__h6399, 1u);
      backing.DEF_m_fifo_2_last_write_ehrReg__h6399 = DEF_m_fifo_2_last_write_ehrReg__h6399;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_last_write_virtual_reg_1_read____d96, 1u);
      backing.DEF_m_fifo_2_last_write_virtual_reg_1_read____d96 = DEF_m_fifo_2_last_write_virtual_reg_1_read____d96;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_last_write_virtual_reg_2_read____d94, 1u);
      backing.DEF_m_fifo_2_last_write_virtual_reg_2_read____d94 = DEF_m_fifo_2_last_write_virtual_reg_2_read____d94;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_last_write_wires_0_wget____d50, 1u);
      backing.DEF_m_fifo_2_last_write_wires_0_wget____d50 = DEF_m_fifo_2_last_write_wires_0_wget____d50;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_2_last_write_wires_0_whas____d49, 1u);
      backing.DEF_m_fifo_2_last_write_wires_0_whas____d49 = DEF_m_fifo_2_last_write_wires_0_whas____d49;
      vcd_write_val(sim_hdl, num++, DEF_x__h10111, 2u);
      backing.DEF_x__h10111 = DEF_x__h10111;
      vcd_write_val(sim_hdl, num++, DEF_x__h12437, 2u);
      backing.DEF_x__h12437 = DEF_x__h12437;
      vcd_write_val(sim_hdl, num++, DEF_x__h12588, 2u);
      backing.DEF_x__h12588 = DEF_x__h12588;
    }
}

void MOD_mkTbPipelineScheduling::vcd_prims(tVCDDumpType dt, MOD_mkTbPipelineScheduling &backing)
{
  INST_m_cycle.dump_VCD(dt, backing.INST_m_cycle);
  INST_m_fifo_1_data_0.dump_VCD(dt, backing.INST_m_fifo_1_data_0);
  INST_m_fifo_1_data_1.dump_VCD(dt, backing.INST_m_fifo_1_data_1);
  INST_m_fifo_1_data_2.dump_VCD(dt, backing.INST_m_fifo_1_data_2);
  INST_m_fifo_1_deqP_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_deqP_ehrReg);
  INST_m_fifo_1_deqP_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_deqP_ignored_wires_0);
  INST_m_fifo_1_deqP_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_deqP_ignored_wires_1);
  INST_m_fifo_1_deqP_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_deqP_ignored_wires_2);
  INST_m_fifo_1_deqP_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_deqP_virtual_reg_0);
  INST_m_fifo_1_deqP_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_deqP_virtual_reg_1);
  INST_m_fifo_1_deqP_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_1_deqP_virtual_reg_2);
  INST_m_fifo_1_deqP_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_deqP_wires_0);
  INST_m_fifo_1_deqP_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_deqP_wires_1);
  INST_m_fifo_1_deqP_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_deqP_wires_2);
  INST_m_fifo_1_ehr_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ehrReg);
  INST_m_fifo_1_ehr_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_0);
  INST_m_fifo_1_ehr_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_1);
  INST_m_fifo_1_ehr_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_2);
  INST_m_fifo_1_ehr_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_0);
  INST_m_fifo_1_ehr_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_1);
  INST_m_fifo_1_ehr_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_2);
  INST_m_fifo_1_ehr_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_0);
  INST_m_fifo_1_ehr_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_1);
  INST_m_fifo_1_ehr_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_2);
  INST_m_fifo_1_enqP_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_enqP_ehrReg);
  INST_m_fifo_1_enqP_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_enqP_ignored_wires_0);
  INST_m_fifo_1_enqP_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_enqP_ignored_wires_1);
  INST_m_fifo_1_enqP_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_enqP_virtual_reg_0);
  INST_m_fifo_1_enqP_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_enqP_virtual_reg_1);
  INST_m_fifo_1_enqP_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_enqP_wires_0);
  INST_m_fifo_1_enqP_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_enqP_wires_1);
  INST_m_fifo_1_last_write_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_last_write_ehrReg);
  INST_m_fifo_1_last_write_ignored_wires_0.dump_VCD(dt,
						    backing.INST_m_fifo_1_last_write_ignored_wires_0);
  INST_m_fifo_1_last_write_ignored_wires_1.dump_VCD(dt,
						    backing.INST_m_fifo_1_last_write_ignored_wires_1);
  INST_m_fifo_1_last_write_ignored_wires_2.dump_VCD(dt,
						    backing.INST_m_fifo_1_last_write_ignored_wires_2);
  INST_m_fifo_1_last_write_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_last_write_virtual_reg_0);
  INST_m_fifo_1_last_write_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_last_write_virtual_reg_1);
  INST_m_fifo_1_last_write_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_1_last_write_virtual_reg_2);
  INST_m_fifo_1_last_write_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_last_write_wires_0);
  INST_m_fifo_1_last_write_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_last_write_wires_1);
  INST_m_fifo_1_last_write_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_last_write_wires_2);
  INST_m_fifo_2_data_0.dump_VCD(dt, backing.INST_m_fifo_2_data_0);
  INST_m_fifo_2_data_1.dump_VCD(dt, backing.INST_m_fifo_2_data_1);
  INST_m_fifo_2_data_2.dump_VCD(dt, backing.INST_m_fifo_2_data_2);
  INST_m_fifo_2_deqP_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_deqP_ehrReg);
  INST_m_fifo_2_deqP_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_deqP_ignored_wires_0);
  INST_m_fifo_2_deqP_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_deqP_ignored_wires_1);
  INST_m_fifo_2_deqP_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_deqP_ignored_wires_2);
  INST_m_fifo_2_deqP_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_deqP_virtual_reg_0);
  INST_m_fifo_2_deqP_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_deqP_virtual_reg_1);
  INST_m_fifo_2_deqP_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_2_deqP_virtual_reg_2);
  INST_m_fifo_2_deqP_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_deqP_wires_0);
  INST_m_fifo_2_deqP_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_deqP_wires_1);
  INST_m_fifo_2_deqP_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_deqP_wires_2);
  INST_m_fifo_2_ehr_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ehrReg);
  INST_m_fifo_2_ehr_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_0);
  INST_m_fifo_2_ehr_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_1);
  INST_m_fifo_2_ehr_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_2);
  INST_m_fifo_2_ehr_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_0);
  INST_m_fifo_2_ehr_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_1);
  INST_m_fifo_2_ehr_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_2);
  INST_m_fifo_2_ehr_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_0);
  INST_m_fifo_2_ehr_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_1);
  INST_m_fifo_2_ehr_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_2);
  INST_m_fifo_2_enqP_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_enqP_ehrReg);
  INST_m_fifo_2_enqP_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_enqP_ignored_wires_0);
  INST_m_fifo_2_enqP_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_enqP_ignored_wires_1);
  INST_m_fifo_2_enqP_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_enqP_virtual_reg_0);
  INST_m_fifo_2_enqP_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_enqP_virtual_reg_1);
  INST_m_fifo_2_enqP_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_enqP_wires_0);
  INST_m_fifo_2_enqP_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_enqP_wires_1);
  INST_m_fifo_2_last_write_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_last_write_ehrReg);
  INST_m_fifo_2_last_write_ignored_wires_0.dump_VCD(dt,
						    backing.INST_m_fifo_2_last_write_ignored_wires_0);
  INST_m_fifo_2_last_write_ignored_wires_1.dump_VCD(dt,
						    backing.INST_m_fifo_2_last_write_ignored_wires_1);
  INST_m_fifo_2_last_write_ignored_wires_2.dump_VCD(dt,
						    backing.INST_m_fifo_2_last_write_ignored_wires_2);
  INST_m_fifo_2_last_write_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_last_write_virtual_reg_0);
  INST_m_fifo_2_last_write_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_last_write_virtual_reg_1);
  INST_m_fifo_2_last_write_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_2_last_write_virtual_reg_2);
  INST_m_fifo_2_last_write_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_last_write_wires_0);
  INST_m_fifo_2_last_write_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_last_write_wires_1);
  INST_m_fifo_2_last_write_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_last_write_wires_2);
}
