/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sun Apr 26 09:32:48 CST 2026
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbBypassScheduling_h__
#define __mkTbBypassScheduling_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbBypassScheduling module */
class MOD_mkTbBypassScheduling : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_0_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_0_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_0_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_0_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_0_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_0_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_0_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_1_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_1_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_1_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_1_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_1_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_1_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_1_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_2_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_2_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_2_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_2_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_data_2_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_2_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_data_2_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqP_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqP_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_last_write_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_last_write_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_0_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_0_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_0_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_0_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_0_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_0_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_0_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_1_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_1_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_1_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_1_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_1_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_1_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_1_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_2_m_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_2_m_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_2_m_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_2_m_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_data_2_m_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_2_m_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_data_2_m_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqP_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqP_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqP_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqP_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_last_write_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_last_write_wires_2;
 
 /* Constructor */
 public:
  MOD_mkTbBypassScheduling(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_WILL_FIRE_RL_m_clear_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_clear_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_last_write_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_last_write_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_enqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_data_2_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_data_2_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_data_1_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_data_1_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_data_0_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_data_0_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_last_write_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_last_write_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_enqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_data_2_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_data_2_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_data_1_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_data_1_m_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_data_0_m_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_data_0_m_canonicalize;
 
 /* Local definitions */
 private:
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_2_read____d124;
  tUInt8 DEF_m_fifo_1_last_write_virtual_reg_1_read____d138;
  tUInt8 DEF_m_fifo_1_last_write_virtual_reg_2_read____d137;
  tUInt8 DEF_def__h17343;
  tUInt8 DEF_def__h17278;
  tUInt8 DEF_def__h17213;
  tUInt8 DEF_def__h18908;
  tUInt8 DEF_def__h18570;
  tUInt8 DEF_def__h18414;
  tUInt8 DEF_m_fifo_1_enqP_virtual_reg_2_read____d117;
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_1_read____d125;
  tUInt8 DEF_m_fifo_1_last_write_ehrReg__h5649;
  tUInt8 DEF_m_fifo_1_enqP_virtual_reg_1_read____d118;
  tUInt8 DEF_y__h14703;
  tUInt8 DEF_IF_m_fifo_1_data_2_m_wires_0_whas__7_THEN_m_fi_ETC___d20;
  tUInt8 DEF_IF_m_fifo_1_data_1_m_wires_0_whas__0_THEN_m_fi_ETC___d13;
  tUInt8 DEF_IF_m_fifo_1_data_0_m_wires_0_whas_THEN_m_fifo__ETC___d6;
  tUInt8 DEF_IF_m_fifo_1_enqP_wires_0_whas__6_THEN_m_fifo_1_ETC___d29;
  tUInt8 DEF_IF_m_fifo_1_ehr_wires_0_whas__01_THEN_m_fifo_1_ETC___d104;
  tUInt8 DEF_IF_m_fifo_1_ehr_wires_1_whas__9_THEN_m_fifo_1__ETC___d105;
  tUInt8 DEF_x__h18543;
  tUInt8 DEF_x__h18367;
  tUInt8 DEF_IF_m_fifo_1_last_write_wires_1_whas__1_THEN_m__ETC___d47;
  tUInt8 DEF_IF_m_fifo_1_last_write_wires_0_whas__3_THEN_m__ETC___d46;
 
 /* Rules */
 public:
  void RL_m_fifo_1_data_0_m_canonicalize();
  void RL_m_fifo_1_data_1_m_canonicalize();
  void RL_m_fifo_1_data_2_m_canonicalize();
  void RL_m_fifo_1_enqP_canonicalize();
  void RL_m_fifo_1_deqP_canonicalize();
  void RL_m_fifo_1_last_write_canonicalize();
  void RL_m_fifo_2_data_0_m_canonicalize();
  void RL_m_fifo_2_data_1_m_canonicalize();
  void RL_m_fifo_2_data_2_m_canonicalize();
  void RL_m_fifo_2_enqP_canonicalize();
  void RL_m_fifo_2_deqP_canonicalize();
  void RL_m_fifo_2_last_write_canonicalize();
  void RL_m_fifo_1_ehr_canonicalize();
  void RL_m_fifo_2_ehr_canonicalize();
  void RL_m_enq_fifo_1();
  void RL_m_deq_fifo_1();
  void RL_m_clear_fifo_1();
  void RL_m_cycle_stuff();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbBypassScheduling &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbBypassScheduling &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbBypassScheduling &backing);
};

#endif /* ifndef __mkTbBypassScheduling_h__ */
