/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Apr  6 17:53:44 CST 2026
 * 
 */

/* Generation options: */
#ifndef __mkFftSuperFolded4_h__
#define __mkFftSuperFolded4_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftSuperFolded4 module */
class MOD_mkFftSuperFolded4 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_sfFft_bfly_0;
  MOD_mkBfly4 INST_sfFft_bfly_1;
  MOD_mkBfly4 INST_sfFft_bfly_2;
  MOD_mkBfly4 INST_sfFft_bfly_3;
  MOD_Reg<tUWide> INST_sfFft_inFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_sfFft_inFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_sfFft_inFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_sfFft_inFifo_da_wires_0;
  MOD_Wire<tUWide> INST_sfFft_inFifo_da_wires_1;
  MOD_Reg<tUWide> INST_sfFft_inFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_sfFft_inFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_sfFft_inFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_sfFft_inFifo_db_wires_0;
  MOD_Wire<tUWide> INST_sfFft_inFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_inFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_inFifo_vb_wires_1;
  MOD_Reg<tUWide> INST_sfFft_outFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_sfFft_outFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_sfFft_outFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_sfFft_outFifo_da_wires_0;
  MOD_Wire<tUWide> INST_sfFft_outFifo_da_wires_1;
  MOD_Reg<tUWide> INST_sfFft_outFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_sfFft_outFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_sfFft_outFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_sfFft_outFifo_db_wires_0;
  MOD_Wire<tUWide> INST_sfFft_outFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_sfFft_outFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_sfFft_outFifo_vb_wires_1;
 
 /* Constructor */
 public:
  MOD_mkFftSuperFolded4(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29;
  tUInt8 DEF_sfFft_outFifo_va_virtual_reg_1_read____d71;
  tUInt8 DEF_sfFft_outFifo_va_ehrReg__h98389;
  tUInt8 DEF_sfFft_inFifo_vb_ehrReg__h53003;
 
 /* Local definitions */
 private:
  tUWide DEF_sfFft_outFifo_db_wires_1_wget____d55;
  tUWide DEF_sfFft_outFifo_db_wires_0_wget____d57;
  tUWide DEF_sfFft_outFifo_db_ehrReg__h115076;
  tUWide DEF_sfFft_outFifo_da_wires_1_wget____d41;
  tUWide DEF_sfFft_outFifo_da_wires_0_wget____d43;
  tUWide DEF_sfFft_outFifo_da_ehrReg__h88571;
  tUWide DEF_sfFft_inFifo_db_wires_1_wget____d16;
  tUWide DEF_sfFft_inFifo_db_wires_0_wget____d18;
  tUWide DEF_sfFft_inFifo_db_ehrReg__h43185;
  tUWide DEF_sfFft_inFifo_da_wires_1_wget____d2;
  tUWide DEF_sfFft_inFifo_da_wires_0_wget____d4;
  tUWide DEF_sfFft_inFifo_da_ehrReg__h16680;
  tUInt8 DEF_sfFft_outFifo_vb_ehrReg__h124894;
  tUInt8 DEF_sfFft_outFifo_va_wires_0_whas____d49;
  tUInt8 DEF_sfFft_outFifo_va_wires_0_wget____d50;
  tUInt8 DEF_sfFft_inFifo_va_wires_0_whas____d10;
  tUInt8 DEF_sfFft_inFifo_va_wires_0_wget____d11;
  tUInt8 DEF_sfFft_inFifo_va_ehrReg__h26498;
  tUWide DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78;
  tUWide DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59;
  tUWide DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60;
  tUWide DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46;
  tUWide DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45;
  tUWide DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39;
  tUWide DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20;
  tUWide DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21;
  tUWide DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6;
  tUWide DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7;
  tUInt8 DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66;
  tUInt8 DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52;
  tUInt8 DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27;
  tUInt8 DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13;
 
 /* Rules */
 public:
  void RL_sfFft_inFifo_da_canonicalize();
  void RL_sfFft_inFifo_va_canonicalize();
  void RL_sfFft_inFifo_db_canonicalize();
  void RL_sfFft_inFifo_vb_canonicalize();
  void RL_sfFft_inFifo_canonicalize();
  void RL_sfFft_outFifo_da_canonicalize();
  void RL_sfFft_outFifo_va_canonicalize();
  void RL_sfFft_outFifo_db_canonicalize();
  void RL_sfFft_outFifo_vb_canonicalize();
  void RL_sfFft_outFifo_canonicalize();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftSuperFolded4 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftSuperFolded4 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftSuperFolded4 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftSuperFolded4 &backing);
};

#endif /* ifndef __mkFftSuperFolded4_h__ */
