/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Apr  6 17:53:44 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkFftSuperFolded4.h"


/* Literal declarations */
static unsigned int const UWide_literal_1024_h0_arr[] = { 0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u,
							  0u };
static tUWide const UWide_literal_1024_h0(1024u, UWide_literal_1024_h0_arr);
static unsigned int const UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u,
																																							 2863311530u };
static tUWide const UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(1024u,
																																					 UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);


/* Constructor */
MOD_mkFftSuperFolded4::MOD_mkFftSuperFolded4(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_sfFft_bfly_0(simHdl, "sfFft_bfly_0", this),
    INST_sfFft_bfly_1(simHdl, "sfFft_bfly_1", this),
    INST_sfFft_bfly_2(simHdl, "sfFft_bfly_2", this),
    INST_sfFft_bfly_3(simHdl, "sfFft_bfly_3", this),
    INST_sfFft_inFifo_da_ehrReg(simHdl,
				"sfFft_inFifo_da_ehrReg",
				this,
				1024u,
				UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
				(tUInt8)0u),
    INST_sfFft_inFifo_da_ignored_wires_0(simHdl,
					 "sfFft_inFifo_da_ignored_wires_0",
					 this,
					 1024u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_da_ignored_wires_1(simHdl,
					 "sfFft_inFifo_da_ignored_wires_1",
					 this,
					 1024u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_da_virtual_reg_0(simHdl, "sfFft_inFifo_da_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_da_virtual_reg_1(simHdl, "sfFft_inFifo_da_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_da_wires_0(simHdl, "sfFft_inFifo_da_wires_0", this, 1024u, (tUInt8)0u),
    INST_sfFft_inFifo_da_wires_1(simHdl, "sfFft_inFifo_da_wires_1", this, 1024u, (tUInt8)0u),
    INST_sfFft_inFifo_db_ehrReg(simHdl,
				"sfFft_inFifo_db_ehrReg",
				this,
				1024u,
				UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
				(tUInt8)0u),
    INST_sfFft_inFifo_db_ignored_wires_0(simHdl,
					 "sfFft_inFifo_db_ignored_wires_0",
					 this,
					 1024u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_db_ignored_wires_1(simHdl,
					 "sfFft_inFifo_db_ignored_wires_1",
					 this,
					 1024u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_db_virtual_reg_0(simHdl, "sfFft_inFifo_db_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_db_virtual_reg_1(simHdl, "sfFft_inFifo_db_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_db_wires_0(simHdl, "sfFft_inFifo_db_wires_0", this, 1024u, (tUInt8)0u),
    INST_sfFft_inFifo_db_wires_1(simHdl, "sfFft_inFifo_db_wires_1", this, 1024u, (tUInt8)0u),
    INST_sfFft_inFifo_va_ehrReg(simHdl, "sfFft_inFifo_va_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_sfFft_inFifo_va_ignored_wires_0(simHdl,
					 "sfFft_inFifo_va_ignored_wires_0",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_va_ignored_wires_1(simHdl,
					 "sfFft_inFifo_va_ignored_wires_1",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_va_virtual_reg_0(simHdl, "sfFft_inFifo_va_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_va_virtual_reg_1(simHdl, "sfFft_inFifo_va_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_va_wires_0(simHdl, "sfFft_inFifo_va_wires_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_va_wires_1(simHdl, "sfFft_inFifo_va_wires_1", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_vb_ehrReg(simHdl, "sfFft_inFifo_vb_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_sfFft_inFifo_vb_ignored_wires_0(simHdl,
					 "sfFft_inFifo_vb_ignored_wires_0",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_vb_ignored_wires_1(simHdl,
					 "sfFft_inFifo_vb_ignored_wires_1",
					 this,
					 1u,
					 (tUInt8)0u),
    INST_sfFft_inFifo_vb_virtual_reg_0(simHdl, "sfFft_inFifo_vb_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_vb_virtual_reg_1(simHdl, "sfFft_inFifo_vb_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_vb_wires_0(simHdl, "sfFft_inFifo_vb_wires_0", this, 1u, (tUInt8)0u),
    INST_sfFft_inFifo_vb_wires_1(simHdl, "sfFft_inFifo_vb_wires_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_da_ehrReg(simHdl,
				 "sfFft_outFifo_da_ehrReg",
				 this,
				 1024u,
				 UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
				 (tUInt8)0u),
    INST_sfFft_outFifo_da_ignored_wires_0(simHdl,
					  "sfFft_outFifo_da_ignored_wires_0",
					  this,
					  1024u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_da_ignored_wires_1(simHdl,
					  "sfFft_outFifo_da_ignored_wires_1",
					  this,
					  1024u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_da_virtual_reg_0(simHdl, "sfFft_outFifo_da_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_da_virtual_reg_1(simHdl, "sfFft_outFifo_da_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_da_wires_0(simHdl, "sfFft_outFifo_da_wires_0", this, 1024u, (tUInt8)0u),
    INST_sfFft_outFifo_da_wires_1(simHdl, "sfFft_outFifo_da_wires_1", this, 1024u, (tUInt8)0u),
    INST_sfFft_outFifo_db_ehrReg(simHdl,
				 "sfFft_outFifo_db_ehrReg",
				 this,
				 1024u,
				 UWide_literal_1024_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
				 (tUInt8)0u),
    INST_sfFft_outFifo_db_ignored_wires_0(simHdl,
					  "sfFft_outFifo_db_ignored_wires_0",
					  this,
					  1024u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_db_ignored_wires_1(simHdl,
					  "sfFft_outFifo_db_ignored_wires_1",
					  this,
					  1024u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_db_virtual_reg_0(simHdl, "sfFft_outFifo_db_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_db_virtual_reg_1(simHdl, "sfFft_outFifo_db_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_db_wires_0(simHdl, "sfFft_outFifo_db_wires_0", this, 1024u, (tUInt8)0u),
    INST_sfFft_outFifo_db_wires_1(simHdl, "sfFft_outFifo_db_wires_1", this, 1024u, (tUInt8)0u),
    INST_sfFft_outFifo_va_ehrReg(simHdl, "sfFft_outFifo_va_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_sfFft_outFifo_va_ignored_wires_0(simHdl,
					  "sfFft_outFifo_va_ignored_wires_0",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_va_ignored_wires_1(simHdl,
					  "sfFft_outFifo_va_ignored_wires_1",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_va_virtual_reg_0(simHdl, "sfFft_outFifo_va_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_va_virtual_reg_1(simHdl, "sfFft_outFifo_va_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_va_wires_0(simHdl, "sfFft_outFifo_va_wires_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_va_wires_1(simHdl, "sfFft_outFifo_va_wires_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_vb_ehrReg(simHdl, "sfFft_outFifo_vb_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_sfFft_outFifo_vb_ignored_wires_0(simHdl,
					  "sfFft_outFifo_vb_ignored_wires_0",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_vb_ignored_wires_1(simHdl,
					  "sfFft_outFifo_vb_ignored_wires_1",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_sfFft_outFifo_vb_virtual_reg_0(simHdl, "sfFft_outFifo_vb_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_vb_virtual_reg_1(simHdl, "sfFft_outFifo_vb_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_vb_wires_0(simHdl, "sfFft_outFifo_vb_wires_0", this, 1u, (tUInt8)0u),
    INST_sfFft_outFifo_vb_wires_1(simHdl, "sfFft_outFifo_vb_wires_1", this, 1u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_sfFft_outFifo_db_wires_1_wget____d55(1024u),
    DEF_sfFft_outFifo_db_wires_0_wget____d57(1024u),
    DEF_sfFft_outFifo_db_ehrReg__h115076(1024u),
    DEF_sfFft_outFifo_da_wires_1_wget____d41(1024u),
    DEF_sfFft_outFifo_da_wires_0_wget____d43(1024u),
    DEF_sfFft_outFifo_da_ehrReg__h88571(1024u),
    DEF_sfFft_inFifo_db_wires_1_wget____d16(1024u),
    DEF_sfFft_inFifo_db_wires_0_wget____d18(1024u),
    DEF_sfFft_inFifo_db_ehrReg__h43185(1024u),
    DEF_sfFft_inFifo_da_wires_1_wget____d2(1024u),
    DEF_sfFft_inFifo_da_wires_0_wget____d4(1024u),
    DEF_sfFft_inFifo_da_ehrReg__h16680(1024u),
    DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78(1024u),
    DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59(1024u),
    DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60(1024u),
    DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46(1024u),
    DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45(1024u),
    DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39(1024u),
    DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20(1024u),
    DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21(1024u),
    DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6(1024u),
    DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7(1024u)
{
  PORT_enq_in.setSize(1024u);
  PORT_enq_in.clear();
  PORT_deq.setSize(1024u);
  PORT_deq.clear();
  symbol_count = 74u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkFftSuperFolded4::init_symbols_0()
{
  init_symbol(&symbols[0u], "deq", SYM_PORT, &PORT_deq, 1024u);
  init_symbol(&symbols[1u], "enq_in", SYM_PORT, &PORT_enq_in, 1024u);
  init_symbol(&symbols[2u], "RL_sfFft_inFifo_canonicalize", SYM_RULE);
  init_symbol(&symbols[3u], "RL_sfFft_inFifo_da_canonicalize", SYM_RULE);
  init_symbol(&symbols[4u], "RL_sfFft_inFifo_db_canonicalize", SYM_RULE);
  init_symbol(&symbols[5u], "RL_sfFft_inFifo_va_canonicalize", SYM_RULE);
  init_symbol(&symbols[6u], "RL_sfFft_inFifo_vb_canonicalize", SYM_RULE);
  init_symbol(&symbols[7u], "RL_sfFft_outFifo_canonicalize", SYM_RULE);
  init_symbol(&symbols[8u], "RL_sfFft_outFifo_da_canonicalize", SYM_RULE);
  init_symbol(&symbols[9u], "RL_sfFft_outFifo_db_canonicalize", SYM_RULE);
  init_symbol(&symbols[10u], "RL_sfFft_outFifo_va_canonicalize", SYM_RULE);
  init_symbol(&symbols[11u], "RL_sfFft_outFifo_vb_canonicalize", SYM_RULE);
  init_symbol(&symbols[12u], "sfFft_bfly_0", SYM_MODULE, &INST_sfFft_bfly_0);
  init_symbol(&symbols[13u], "sfFft_bfly_1", SYM_MODULE, &INST_sfFft_bfly_1);
  init_symbol(&symbols[14u], "sfFft_bfly_2", SYM_MODULE, &INST_sfFft_bfly_2);
  init_symbol(&symbols[15u], "sfFft_bfly_3", SYM_MODULE, &INST_sfFft_bfly_3);
  init_symbol(&symbols[16u], "sfFft_inFifo_da_ehrReg", SYM_MODULE, &INST_sfFft_inFifo_da_ehrReg);
  init_symbol(&symbols[17u],
	      "sfFft_inFifo_da_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_da_ignored_wires_0);
  init_symbol(&symbols[18u],
	      "sfFft_inFifo_da_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_da_ignored_wires_1);
  init_symbol(&symbols[19u],
	      "sfFft_inFifo_da_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_da_virtual_reg_0);
  init_symbol(&symbols[20u],
	      "sfFft_inFifo_da_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_da_virtual_reg_1);
  init_symbol(&symbols[21u], "sfFft_inFifo_da_wires_0", SYM_MODULE, &INST_sfFft_inFifo_da_wires_0);
  init_symbol(&symbols[22u], "sfFft_inFifo_da_wires_1", SYM_MODULE, &INST_sfFft_inFifo_da_wires_1);
  init_symbol(&symbols[23u], "sfFft_inFifo_db_ehrReg", SYM_MODULE, &INST_sfFft_inFifo_db_ehrReg);
  init_symbol(&symbols[24u],
	      "sfFft_inFifo_db_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_db_ignored_wires_0);
  init_symbol(&symbols[25u],
	      "sfFft_inFifo_db_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_db_ignored_wires_1);
  init_symbol(&symbols[26u],
	      "sfFft_inFifo_db_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_db_virtual_reg_0);
  init_symbol(&symbols[27u],
	      "sfFft_inFifo_db_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_db_virtual_reg_1);
  init_symbol(&symbols[28u], "sfFft_inFifo_db_wires_0", SYM_MODULE, &INST_sfFft_inFifo_db_wires_0);
  init_symbol(&symbols[29u], "sfFft_inFifo_db_wires_1", SYM_MODULE, &INST_sfFft_inFifo_db_wires_1);
  init_symbol(&symbols[30u], "sfFft_inFifo_va_ehrReg", SYM_MODULE, &INST_sfFft_inFifo_va_ehrReg);
  init_symbol(&symbols[31u],
	      "sfFft_inFifo_va_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_va_ignored_wires_0);
  init_symbol(&symbols[32u],
	      "sfFft_inFifo_va_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_va_ignored_wires_1);
  init_symbol(&symbols[33u],
	      "sfFft_inFifo_va_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_va_virtual_reg_0);
  init_symbol(&symbols[34u],
	      "sfFft_inFifo_va_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_va_virtual_reg_1);
  init_symbol(&symbols[35u], "sfFft_inFifo_va_wires_0", SYM_MODULE, &INST_sfFft_inFifo_va_wires_0);
  init_symbol(&symbols[36u], "sfFft_inFifo_va_wires_1", SYM_MODULE, &INST_sfFft_inFifo_va_wires_1);
  init_symbol(&symbols[37u], "sfFft_inFifo_vb_ehrReg", SYM_MODULE, &INST_sfFft_inFifo_vb_ehrReg);
  init_symbol(&symbols[38u],
	      "sfFft_inFifo_vb_ehrReg__h53003",
	      SYM_DEF,
	      &DEF_sfFft_inFifo_vb_ehrReg__h53003,
	      1u);
  init_symbol(&symbols[39u],
	      "sfFft_inFifo_vb_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_vb_ignored_wires_0);
  init_symbol(&symbols[40u],
	      "sfFft_inFifo_vb_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_vb_ignored_wires_1);
  init_symbol(&symbols[41u],
	      "sfFft_inFifo_vb_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_vb_virtual_reg_0);
  init_symbol(&symbols[42u],
	      "sfFft_inFifo_vb_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_inFifo_vb_virtual_reg_1);
  init_symbol(&symbols[43u], "sfFft_inFifo_vb_wires_0", SYM_MODULE, &INST_sfFft_inFifo_vb_wires_0);
  init_symbol(&symbols[44u], "sfFft_inFifo_vb_wires_1", SYM_MODULE, &INST_sfFft_inFifo_vb_wires_1);
  init_symbol(&symbols[45u], "sfFft_outFifo_da_ehrReg", SYM_MODULE, &INST_sfFft_outFifo_da_ehrReg);
  init_symbol(&symbols[46u],
	      "sfFft_outFifo_da_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_da_ignored_wires_0);
  init_symbol(&symbols[47u],
	      "sfFft_outFifo_da_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_da_ignored_wires_1);
  init_symbol(&symbols[48u],
	      "sfFft_outFifo_da_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_da_virtual_reg_0);
  init_symbol(&symbols[49u],
	      "sfFft_outFifo_da_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_da_virtual_reg_1);
  init_symbol(&symbols[50u], "sfFft_outFifo_da_wires_0", SYM_MODULE, &INST_sfFft_outFifo_da_wires_0);
  init_symbol(&symbols[51u], "sfFft_outFifo_da_wires_1", SYM_MODULE, &INST_sfFft_outFifo_da_wires_1);
  init_symbol(&symbols[52u], "sfFft_outFifo_db_ehrReg", SYM_MODULE, &INST_sfFft_outFifo_db_ehrReg);
  init_symbol(&symbols[53u],
	      "sfFft_outFifo_db_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_db_ignored_wires_0);
  init_symbol(&symbols[54u],
	      "sfFft_outFifo_db_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_db_ignored_wires_1);
  init_symbol(&symbols[55u],
	      "sfFft_outFifo_db_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_db_virtual_reg_0);
  init_symbol(&symbols[56u],
	      "sfFft_outFifo_db_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_db_virtual_reg_1);
  init_symbol(&symbols[57u], "sfFft_outFifo_db_wires_0", SYM_MODULE, &INST_sfFft_outFifo_db_wires_0);
  init_symbol(&symbols[58u], "sfFft_outFifo_db_wires_1", SYM_MODULE, &INST_sfFft_outFifo_db_wires_1);
  init_symbol(&symbols[59u], "sfFft_outFifo_va_ehrReg", SYM_MODULE, &INST_sfFft_outFifo_va_ehrReg);
  init_symbol(&symbols[60u],
	      "sfFft_outFifo_va_ehrReg__h98389",
	      SYM_DEF,
	      &DEF_sfFft_outFifo_va_ehrReg__h98389,
	      1u);
  init_symbol(&symbols[61u],
	      "sfFft_outFifo_va_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_va_ignored_wires_0);
  init_symbol(&symbols[62u],
	      "sfFft_outFifo_va_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_va_ignored_wires_1);
  init_symbol(&symbols[63u],
	      "sfFft_outFifo_va_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_va_virtual_reg_0);
  init_symbol(&symbols[64u],
	      "sfFft_outFifo_va_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_va_virtual_reg_1);
  init_symbol(&symbols[65u], "sfFft_outFifo_va_wires_0", SYM_MODULE, &INST_sfFft_outFifo_va_wires_0);
  init_symbol(&symbols[66u], "sfFft_outFifo_va_wires_1", SYM_MODULE, &INST_sfFft_outFifo_va_wires_1);
  init_symbol(&symbols[67u], "sfFft_outFifo_vb_ehrReg", SYM_MODULE, &INST_sfFft_outFifo_vb_ehrReg);
  init_symbol(&symbols[68u],
	      "sfFft_outFifo_vb_ignored_wires_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_vb_ignored_wires_0);
  init_symbol(&symbols[69u],
	      "sfFft_outFifo_vb_ignored_wires_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_vb_ignored_wires_1);
  init_symbol(&symbols[70u],
	      "sfFft_outFifo_vb_virtual_reg_0",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_vb_virtual_reg_0);
  init_symbol(&symbols[71u],
	      "sfFft_outFifo_vb_virtual_reg_1",
	      SYM_MODULE,
	      &INST_sfFft_outFifo_vb_virtual_reg_1);
  init_symbol(&symbols[72u], "sfFft_outFifo_vb_wires_0", SYM_MODULE, &INST_sfFft_outFifo_vb_wires_0);
  init_symbol(&symbols[73u], "sfFft_outFifo_vb_wires_1", SYM_MODULE, &INST_sfFft_outFifo_vb_wires_1);
}


/* Rule actions */

void MOD_mkFftSuperFolded4::RL_sfFft_inFifo_da_canonicalize()
{
  DEF_sfFft_inFifo_da_wires_1_wget____d2 = INST_sfFft_inFifo_da_wires_1.METH_wget();
  DEF_sfFft_inFifo_da_wires_0_wget____d4 = INST_sfFft_inFifo_da_wires_0.METH_wget();
  DEF_sfFft_inFifo_da_ehrReg__h16680 = INST_sfFft_inFifo_da_ehrReg.METH_read();
  DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6 = INST_sfFft_inFifo_da_wires_0.METH_whas() ? DEF_sfFft_inFifo_da_wires_0_wget____d4 : DEF_sfFft_inFifo_da_ehrReg__h16680;
  DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7 = INST_sfFft_inFifo_da_wires_1.METH_whas() ? DEF_sfFft_inFifo_da_wires_1_wget____d2 : DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6;
  INST_sfFft_inFifo_da_ehrReg.METH_write(DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7);
}

void MOD_mkFftSuperFolded4::RL_sfFft_inFifo_va_canonicalize()
{
  tUInt8 DEF_IF_sfFft_inFifo_va_wires_1_whas_THEN_sfFft_inF_ETC___d14;
  DEF_sfFft_inFifo_va_wires_0_whas____d10 = INST_sfFft_inFifo_va_wires_0.METH_whas();
  DEF_sfFft_inFifo_va_wires_0_wget____d11 = INST_sfFft_inFifo_va_wires_0.METH_wget();
  DEF_sfFft_inFifo_va_ehrReg__h26498 = INST_sfFft_inFifo_va_ehrReg.METH_read();
  DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13 = DEF_sfFft_inFifo_va_wires_0_whas____d10 ? DEF_sfFft_inFifo_va_wires_0_wget____d11 : DEF_sfFft_inFifo_va_ehrReg__h26498;
  DEF_IF_sfFft_inFifo_va_wires_1_whas_THEN_sfFft_inF_ETC___d14 = INST_sfFft_inFifo_va_wires_1.METH_whas() ? INST_sfFft_inFifo_va_wires_1.METH_wget() : DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13;
  INST_sfFft_inFifo_va_ehrReg.METH_write(DEF_IF_sfFft_inFifo_va_wires_1_whas_THEN_sfFft_inF_ETC___d14);
}

void MOD_mkFftSuperFolded4::RL_sfFft_inFifo_db_canonicalize()
{
  DEF_sfFft_inFifo_db_wires_1_wget____d16 = INST_sfFft_inFifo_db_wires_1.METH_wget();
  DEF_sfFft_inFifo_db_wires_0_wget____d18 = INST_sfFft_inFifo_db_wires_0.METH_wget();
  DEF_sfFft_inFifo_db_ehrReg__h43185 = INST_sfFft_inFifo_db_ehrReg.METH_read();
  DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20 = INST_sfFft_inFifo_db_wires_0.METH_whas() ? DEF_sfFft_inFifo_db_wires_0_wget____d18 : DEF_sfFft_inFifo_db_ehrReg__h43185;
  DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21 = INST_sfFft_inFifo_db_wires_1.METH_whas() ? DEF_sfFft_inFifo_db_wires_1_wget____d16 : DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20;
  INST_sfFft_inFifo_db_ehrReg.METH_write(DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21);
}

void MOD_mkFftSuperFolded4::RL_sfFft_inFifo_vb_canonicalize()
{
  tUInt8 DEF_IF_sfFft_inFifo_vb_wires_1_whas__2_THEN_sfFft__ETC___d28;
  DEF_sfFft_inFifo_vb_ehrReg__h53003 = INST_sfFft_inFifo_vb_ehrReg.METH_read();
  DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27 = INST_sfFft_inFifo_vb_wires_0.METH_whas() ? INST_sfFft_inFifo_vb_wires_0.METH_wget() : DEF_sfFft_inFifo_vb_ehrReg__h53003;
  DEF_IF_sfFft_inFifo_vb_wires_1_whas__2_THEN_sfFft__ETC___d28 = INST_sfFft_inFifo_vb_wires_1.METH_whas() ? INST_sfFft_inFifo_vb_wires_1.METH_wget() : DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27;
  INST_sfFft_inFifo_vb_ehrReg.METH_write(DEF_IF_sfFft_inFifo_vb_wires_1_whas__2_THEN_sfFft__ETC___d28);
}

void MOD_mkFftSuperFolded4::RL_sfFft_inFifo_canonicalize()
{
  tUInt8 DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37;
  DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 = INST_sfFft_inFifo_vb_virtual_reg_1.METH_read();
  DEF_sfFft_inFifo_db_wires_0_wget____d18 = INST_sfFft_inFifo_db_wires_0.METH_wget();
  DEF_sfFft_inFifo_db_ehrReg__h43185 = INST_sfFft_inFifo_db_ehrReg.METH_read();
  DEF_sfFft_inFifo_da_wires_0_wget____d4 = INST_sfFft_inFifo_da_wires_0.METH_wget();
  DEF_sfFft_inFifo_vb_ehrReg__h53003 = INST_sfFft_inFifo_vb_ehrReg.METH_read();
  DEF_sfFft_inFifo_da_ehrReg__h16680 = INST_sfFft_inFifo_da_ehrReg.METH_read();
  DEF_sfFft_inFifo_va_wires_0_whas____d10 = INST_sfFft_inFifo_va_wires_0.METH_whas();
  DEF_sfFft_inFifo_va_wires_0_wget____d11 = INST_sfFft_inFifo_va_wires_0.METH_wget();
  DEF_sfFft_inFifo_va_ehrReg__h26498 = INST_sfFft_inFifo_va_ehrReg.METH_read();
  DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20 = INST_sfFft_inFifo_db_wires_0.METH_whas() ? DEF_sfFft_inFifo_db_wires_0_wget____d18 : DEF_sfFft_inFifo_db_ehrReg__h43185;
  DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39 = INST_sfFft_inFifo_db_virtual_reg_1.METH_read() ? UWide_literal_1024_h0 : DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20;
  DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6 = INST_sfFft_inFifo_da_wires_0.METH_whas() ? DEF_sfFft_inFifo_da_wires_0_wget____d4 : DEF_sfFft_inFifo_da_ehrReg__h16680;
  DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27 = INST_sfFft_inFifo_vb_wires_0.METH_whas() ? INST_sfFft_inFifo_vb_wires_0.METH_wget() : DEF_sfFft_inFifo_vb_ehrReg__h53003;
  DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13 = DEF_sfFft_inFifo_va_wires_0_whas____d10 ? DEF_sfFft_inFifo_va_wires_0_wget____d11 : DEF_sfFft_inFifo_va_ehrReg__h26498;
  DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37 = (!DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 && DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27) && (INST_sfFft_inFifo_va_virtual_reg_1.METH_read() || (DEF_sfFft_inFifo_va_wires_0_whas____d10 ? !DEF_sfFft_inFifo_va_wires_0_wget____d11 : !DEF_sfFft_inFifo_va_ehrReg__h26498));
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_da_wires_1.METH_wset(DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_da_ignored_wires_1.METH_wset(DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_da_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_va_wires_1.METH_wset((tUInt8)1u);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_va_ignored_wires_1.METH_wset(DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_va_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_vb_wires_1.METH_wset((tUInt8)0u);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_vb_ignored_wires_1.METH_wset(DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27);
  if (DEF_NOT_sfFft_inFifo_vb_virtual_reg_1_read__9_0_AN_ETC___d37)
    INST_sfFft_inFifo_vb_virtual_reg_1.METH_write((tUInt8)0u);
}

void MOD_mkFftSuperFolded4::RL_sfFft_outFifo_da_canonicalize()
{
  DEF_sfFft_outFifo_da_wires_1_wget____d41 = INST_sfFft_outFifo_da_wires_1.METH_wget();
  DEF_sfFft_outFifo_da_wires_0_wget____d43 = INST_sfFft_outFifo_da_wires_0.METH_wget();
  DEF_sfFft_outFifo_da_ehrReg__h88571 = INST_sfFft_outFifo_da_ehrReg.METH_read();
  DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45 = INST_sfFft_outFifo_da_wires_0.METH_whas() ? DEF_sfFft_outFifo_da_wires_0_wget____d43 : DEF_sfFft_outFifo_da_ehrReg__h88571;
  DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46 = INST_sfFft_outFifo_da_wires_1.METH_whas() ? DEF_sfFft_outFifo_da_wires_1_wget____d41 : DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45;
  INST_sfFft_outFifo_da_ehrReg.METH_write(DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46);
}

void MOD_mkFftSuperFolded4::RL_sfFft_outFifo_va_canonicalize()
{
  tUInt8 DEF_IF_sfFft_outFifo_va_wires_1_whas__7_THEN_sfFft_ETC___d53;
  DEF_sfFft_outFifo_va_wires_0_whas____d49 = INST_sfFft_outFifo_va_wires_0.METH_whas();
  DEF_sfFft_outFifo_va_wires_0_wget____d50 = INST_sfFft_outFifo_va_wires_0.METH_wget();
  DEF_sfFft_outFifo_va_ehrReg__h98389 = INST_sfFft_outFifo_va_ehrReg.METH_read();
  DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52 = DEF_sfFft_outFifo_va_wires_0_whas____d49 ? DEF_sfFft_outFifo_va_wires_0_wget____d50 : DEF_sfFft_outFifo_va_ehrReg__h98389;
  DEF_IF_sfFft_outFifo_va_wires_1_whas__7_THEN_sfFft_ETC___d53 = INST_sfFft_outFifo_va_wires_1.METH_whas() ? INST_sfFft_outFifo_va_wires_1.METH_wget() : DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52;
  INST_sfFft_outFifo_va_ehrReg.METH_write(DEF_IF_sfFft_outFifo_va_wires_1_whas__7_THEN_sfFft_ETC___d53);
}

void MOD_mkFftSuperFolded4::RL_sfFft_outFifo_db_canonicalize()
{
  DEF_sfFft_outFifo_db_wires_1_wget____d55 = INST_sfFft_outFifo_db_wires_1.METH_wget();
  DEF_sfFft_outFifo_db_wires_0_wget____d57 = INST_sfFft_outFifo_db_wires_0.METH_wget();
  DEF_sfFft_outFifo_db_ehrReg__h115076 = INST_sfFft_outFifo_db_ehrReg.METH_read();
  DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59 = INST_sfFft_outFifo_db_wires_0.METH_whas() ? DEF_sfFft_outFifo_db_wires_0_wget____d57 : DEF_sfFft_outFifo_db_ehrReg__h115076;
  DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60 = INST_sfFft_outFifo_db_wires_1.METH_whas() ? DEF_sfFft_outFifo_db_wires_1_wget____d55 : DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59;
  INST_sfFft_outFifo_db_ehrReg.METH_write(DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60);
}

void MOD_mkFftSuperFolded4::RL_sfFft_outFifo_vb_canonicalize()
{
  tUInt8 DEF_IF_sfFft_outFifo_vb_wires_1_whas__1_THEN_sfFft_ETC___d67;
  DEF_sfFft_outFifo_vb_ehrReg__h124894 = INST_sfFft_outFifo_vb_ehrReg.METH_read();
  DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66 = INST_sfFft_outFifo_vb_wires_0.METH_whas() ? INST_sfFft_outFifo_vb_wires_0.METH_wget() : DEF_sfFft_outFifo_vb_ehrReg__h124894;
  DEF_IF_sfFft_outFifo_vb_wires_1_whas__1_THEN_sfFft_ETC___d67 = INST_sfFft_outFifo_vb_wires_1.METH_whas() ? INST_sfFft_outFifo_vb_wires_1.METH_wget() : DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66;
  INST_sfFft_outFifo_vb_ehrReg.METH_write(DEF_IF_sfFft_outFifo_vb_wires_1_whas__1_THEN_sfFft_ETC___d67);
}

void MOD_mkFftSuperFolded4::RL_sfFft_outFifo_canonicalize()
{
  tUInt8 DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76;
  DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 = INST_sfFft_outFifo_va_virtual_reg_1.METH_read();
  DEF_sfFft_outFifo_db_wires_0_wget____d57 = INST_sfFft_outFifo_db_wires_0.METH_wget();
  DEF_sfFft_outFifo_db_ehrReg__h115076 = INST_sfFft_outFifo_db_ehrReg.METH_read();
  DEF_sfFft_outFifo_da_wires_0_wget____d43 = INST_sfFft_outFifo_da_wires_0.METH_wget();
  DEF_sfFft_outFifo_vb_ehrReg__h124894 = INST_sfFft_outFifo_vb_ehrReg.METH_read();
  DEF_sfFft_outFifo_da_ehrReg__h88571 = INST_sfFft_outFifo_da_ehrReg.METH_read();
  DEF_sfFft_outFifo_va_wires_0_whas____d49 = INST_sfFft_outFifo_va_wires_0.METH_whas();
  DEF_sfFft_outFifo_va_wires_0_wget____d50 = INST_sfFft_outFifo_va_wires_0.METH_wget();
  DEF_sfFft_outFifo_va_ehrReg__h98389 = INST_sfFft_outFifo_va_ehrReg.METH_read();
  DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59 = INST_sfFft_outFifo_db_wires_0.METH_whas() ? DEF_sfFft_outFifo_db_wires_0_wget____d57 : DEF_sfFft_outFifo_db_ehrReg__h115076;
  DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78 = INST_sfFft_outFifo_db_virtual_reg_1.METH_read() ? UWide_literal_1024_h0 : DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59;
  DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45 = INST_sfFft_outFifo_da_wires_0.METH_whas() ? DEF_sfFft_outFifo_da_wires_0_wget____d43 : DEF_sfFft_outFifo_da_ehrReg__h88571;
  DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66 = INST_sfFft_outFifo_vb_wires_0.METH_whas() ? INST_sfFft_outFifo_vb_wires_0.METH_wget() : DEF_sfFft_outFifo_vb_ehrReg__h124894;
  DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52 = DEF_sfFft_outFifo_va_wires_0_whas____d49 ? DEF_sfFft_outFifo_va_wires_0_wget____d50 : DEF_sfFft_outFifo_va_ehrReg__h98389;
  DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76 = (!INST_sfFft_outFifo_vb_virtual_reg_1.METH_read() && DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66) && (DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 || (DEF_sfFft_outFifo_va_wires_0_whas____d49 ? !DEF_sfFft_outFifo_va_wires_0_wget____d50 : !DEF_sfFft_outFifo_va_ehrReg__h98389));
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_da_wires_1.METH_wset(DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_da_ignored_wires_1.METH_wset(DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_da_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_va_wires_1.METH_wset((tUInt8)1u);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_va_ignored_wires_1.METH_wset(DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_va_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_vb_wires_1.METH_wset((tUInt8)0u);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_vb_ignored_wires_1.METH_wset(DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66);
  if (DEF_NOT_sfFft_outFifo_vb_virtual_reg_1_read__8_9_A_ETC___d76)
    INST_sfFft_outFifo_vb_virtual_reg_1.METH_write((tUInt8)0u);
}


/* Methods */

void MOD_mkFftSuperFolded4::METH_enq(tUWide ARG_enq_in)
{
  PORT_enq_in = ARG_enq_in;
  DEF_sfFft_inFifo_db_ehrReg__h43185 = INST_sfFft_inFifo_db_ehrReg.METH_read();
  DEF_sfFft_inFifo_vb_ehrReg__h53003 = INST_sfFft_inFifo_vb_ehrReg.METH_read();
  INST_sfFft_inFifo_db_wires_0.METH_wset(ARG_enq_in);
  INST_sfFft_inFifo_db_ignored_wires_0.METH_wset(DEF_sfFft_inFifo_db_ehrReg__h43185);
  INST_sfFft_inFifo_db_virtual_reg_0.METH_write((tUInt8)0u);
  INST_sfFft_inFifo_vb_wires_0.METH_wset((tUInt8)1u);
  INST_sfFft_inFifo_vb_ignored_wires_0.METH_wset(DEF_sfFft_inFifo_vb_ehrReg__h53003);
  INST_sfFft_inFifo_vb_virtual_reg_0.METH_write((tUInt8)0u);
}

tUInt8 MOD_mkFftSuperFolded4::METH_RDY_enq()
{
  tUInt8 DEF_CAN_FIRE_enq;
  tUInt8 PORT_RDY_enq;
  DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 = INST_sfFft_inFifo_vb_virtual_reg_1.METH_read();
  DEF_sfFft_inFifo_vb_ehrReg__h53003 = INST_sfFft_inFifo_vb_ehrReg.METH_read();
  DEF_CAN_FIRE_enq = DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 || (INST_sfFft_inFifo_vb_virtual_reg_0.METH_read() || !DEF_sfFft_inFifo_vb_ehrReg__h53003);
  PORT_RDY_enq = DEF_CAN_FIRE_enq;
  return PORT_RDY_enq;
}

tUWide MOD_mkFftSuperFolded4::METH_deq()
{
  tUInt8 DEF_sfFft_outFifo_da_virtual_reg_1_read__2_OR_sfFf_ETC___d84;
  DEF_sfFft_outFifo_da_ehrReg__h88571 = INST_sfFft_outFifo_da_ehrReg.METH_read();
  DEF_sfFft_outFifo_va_ehrReg__h98389 = INST_sfFft_outFifo_va_ehrReg.METH_read();
  DEF_sfFft_outFifo_da_virtual_reg_1_read__2_OR_sfFf_ETC___d84 = INST_sfFft_outFifo_da_virtual_reg_1.METH_read() || INST_sfFft_outFifo_da_virtual_reg_0.METH_read();
  PORT_deq = DEF_sfFft_outFifo_da_virtual_reg_1_read__2_OR_sfFf_ETC___d84 ? UWide_literal_1024_h0 : DEF_sfFft_outFifo_da_ehrReg__h88571;
  INST_sfFft_outFifo_va_wires_0.METH_wset((tUInt8)0u);
  INST_sfFft_outFifo_va_virtual_reg_0.METH_write((tUInt8)0u);
  INST_sfFft_outFifo_va_ignored_wires_0.METH_wset(DEF_sfFft_outFifo_va_ehrReg__h98389);
  return PORT_deq;
}

tUInt8 MOD_mkFftSuperFolded4::METH_RDY_deq()
{
  tUInt8 DEF_CAN_FIRE_deq;
  tUInt8 PORT_RDY_deq;
  DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 = INST_sfFft_outFifo_va_virtual_reg_1.METH_read();
  DEF_sfFft_outFifo_va_ehrReg__h98389 = INST_sfFft_outFifo_va_ehrReg.METH_read();
  DEF_CAN_FIRE_deq = !DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 && (!INST_sfFft_outFifo_va_virtual_reg_0.METH_read() && DEF_sfFft_outFifo_va_ehrReg__h98389);
  PORT_RDY_deq = DEF_CAN_FIRE_deq;
  return PORT_RDY_deq;
}


/* Reset routines */

void MOD_mkFftSuperFolded4::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_sfFft_outFifo_vb_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_outFifo_va_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_outFifo_db_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_outFifo_da_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_inFifo_vb_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_inFifo_va_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_inFifo_db_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_inFifo_da_ehrReg.reset_RST(ARG_rst_in);
  INST_sfFft_bfly_3.reset_RST_N(ARG_rst_in);
  INST_sfFft_bfly_2.reset_RST_N(ARG_rst_in);
  INST_sfFft_bfly_1.reset_RST_N(ARG_rst_in);
  INST_sfFft_bfly_0.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkFftSuperFolded4::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkFftSuperFolded4::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_sfFft_bfly_0.dump_state(indent + 2u);
  INST_sfFft_bfly_1.dump_state(indent + 2u);
  INST_sfFft_bfly_2.dump_state(indent + 2u);
  INST_sfFft_bfly_3.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_ehrReg.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_da_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_ehrReg.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_db_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_ehrReg.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_va_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_ehrReg.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_wires_0.dump_state(indent + 2u);
  INST_sfFft_inFifo_vb_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_ehrReg.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_da_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_ehrReg.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_db_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_ehrReg.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_va_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_ehrReg.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_ignored_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_ignored_wires_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_virtual_reg_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_virtual_reg_1.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_wires_0.dump_state(indent + 2u);
  INST_sfFft_outFifo_vb_wires_1.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkFftSuperFolded4::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 95u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_da_ehrReg__h16680", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_da_wires_0_wget____d4", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_da_wires_1_wget____d2", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_db_ehrReg__h43185", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_db_wires_0_wget____d18", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_db_wires_1_wget____d16", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_va_ehrReg__h26498", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_va_wires_0_wget____d11", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_va_wires_0_whas____d10", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_vb_ehrReg__h53003", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_inFifo_vb_virtual_reg_1_read____d29", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_da_ehrReg__h88571", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_da_wires_0_wget____d43", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_da_wires_1_wget____d41", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_db_ehrReg__h115076", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_db_wires_0_wget____d57", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_db_wires_1_wget____d55", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_va_ehrReg__h98389", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_va_virtual_reg_1_read____d71", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_va_wires_0_wget____d50", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_va_wires_0_whas____d49", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "sfFft_outFifo_vb_ehrReg__h124894", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "deq", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "enq_in", 1024u);
  num = INST_sfFft_inFifo_da_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_da_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_db_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_va_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_inFifo_vb_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_da_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_db_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_va_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_ehrReg.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_ignored_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_ignored_wires_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_virtual_reg_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_virtual_reg_1.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_wires_0.dump_VCD_defs(num);
  num = INST_sfFft_outFifo_vb_wires_1.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_sfFft_bfly_0.dump_VCD_defs(l);
    num = INST_sfFft_bfly_1.dump_VCD_defs(l);
    num = INST_sfFft_bfly_2.dump_VCD_defs(l);
    num = INST_sfFft_bfly_3.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkFftSuperFolded4::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_mkFftSuperFolded4 &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkFftSuperFolded4::vcd_defs(tVCDDumpType dt, MOD_mkFftSuperFolded4 &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1024u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6) != DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6, 1024u);
	backing.DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6 = DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7) != DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7, 1024u);
	backing.DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7 = DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39) != DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39, 1024u);
	backing.DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39 = DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20) != DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20, 1024u);
	backing.DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20 = DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21) != DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21, 1024u);
	backing.DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21 = DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13) != DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13, 1u);
	backing.DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13 = DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27) != DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27, 1u);
	backing.DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27 = DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45) != DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45, 1024u);
	backing.DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45 = DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46) != DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46, 1024u);
	backing.DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46 = DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78) != DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78, 1024u);
	backing.DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78 = DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59) != DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59, 1024u);
	backing.DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59 = DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60) != DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60, 1024u);
	backing.DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60 = DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52) != DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52, 1u);
	backing.DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52 = DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52;
      }
      ++num;
      if ((backing.DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66) != DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66, 1u);
	backing.DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66 = DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_da_ehrReg__h16680) != DEF_sfFft_inFifo_da_ehrReg__h16680)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_da_ehrReg__h16680, 1024u);
	backing.DEF_sfFft_inFifo_da_ehrReg__h16680 = DEF_sfFft_inFifo_da_ehrReg__h16680;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_da_wires_0_wget____d4) != DEF_sfFft_inFifo_da_wires_0_wget____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_da_wires_0_wget____d4, 1024u);
	backing.DEF_sfFft_inFifo_da_wires_0_wget____d4 = DEF_sfFft_inFifo_da_wires_0_wget____d4;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_da_wires_1_wget____d2) != DEF_sfFft_inFifo_da_wires_1_wget____d2)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_da_wires_1_wget____d2, 1024u);
	backing.DEF_sfFft_inFifo_da_wires_1_wget____d2 = DEF_sfFft_inFifo_da_wires_1_wget____d2;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_db_ehrReg__h43185) != DEF_sfFft_inFifo_db_ehrReg__h43185)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_db_ehrReg__h43185, 1024u);
	backing.DEF_sfFft_inFifo_db_ehrReg__h43185 = DEF_sfFft_inFifo_db_ehrReg__h43185;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_db_wires_0_wget____d18) != DEF_sfFft_inFifo_db_wires_0_wget____d18)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_db_wires_0_wget____d18, 1024u);
	backing.DEF_sfFft_inFifo_db_wires_0_wget____d18 = DEF_sfFft_inFifo_db_wires_0_wget____d18;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_db_wires_1_wget____d16) != DEF_sfFft_inFifo_db_wires_1_wget____d16)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_db_wires_1_wget____d16, 1024u);
	backing.DEF_sfFft_inFifo_db_wires_1_wget____d16 = DEF_sfFft_inFifo_db_wires_1_wget____d16;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_va_ehrReg__h26498) != DEF_sfFft_inFifo_va_ehrReg__h26498)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_va_ehrReg__h26498, 1u);
	backing.DEF_sfFft_inFifo_va_ehrReg__h26498 = DEF_sfFft_inFifo_va_ehrReg__h26498;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_va_wires_0_wget____d11) != DEF_sfFft_inFifo_va_wires_0_wget____d11)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_va_wires_0_wget____d11, 1u);
	backing.DEF_sfFft_inFifo_va_wires_0_wget____d11 = DEF_sfFft_inFifo_va_wires_0_wget____d11;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_va_wires_0_whas____d10) != DEF_sfFft_inFifo_va_wires_0_whas____d10)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_va_wires_0_whas____d10, 1u);
	backing.DEF_sfFft_inFifo_va_wires_0_whas____d10 = DEF_sfFft_inFifo_va_wires_0_whas____d10;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_vb_ehrReg__h53003) != DEF_sfFft_inFifo_vb_ehrReg__h53003)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_vb_ehrReg__h53003, 1u);
	backing.DEF_sfFft_inFifo_vb_ehrReg__h53003 = DEF_sfFft_inFifo_vb_ehrReg__h53003;
      }
      ++num;
      if ((backing.DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29) != DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29, 1u);
	backing.DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 = DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_da_ehrReg__h88571) != DEF_sfFft_outFifo_da_ehrReg__h88571)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_da_ehrReg__h88571, 1024u);
	backing.DEF_sfFft_outFifo_da_ehrReg__h88571 = DEF_sfFft_outFifo_da_ehrReg__h88571;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_da_wires_0_wget____d43) != DEF_sfFft_outFifo_da_wires_0_wget____d43)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_da_wires_0_wget____d43, 1024u);
	backing.DEF_sfFft_outFifo_da_wires_0_wget____d43 = DEF_sfFft_outFifo_da_wires_0_wget____d43;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_da_wires_1_wget____d41) != DEF_sfFft_outFifo_da_wires_1_wget____d41)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_da_wires_1_wget____d41, 1024u);
	backing.DEF_sfFft_outFifo_da_wires_1_wget____d41 = DEF_sfFft_outFifo_da_wires_1_wget____d41;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_db_ehrReg__h115076) != DEF_sfFft_outFifo_db_ehrReg__h115076)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_db_ehrReg__h115076, 1024u);
	backing.DEF_sfFft_outFifo_db_ehrReg__h115076 = DEF_sfFft_outFifo_db_ehrReg__h115076;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_db_wires_0_wget____d57) != DEF_sfFft_outFifo_db_wires_0_wget____d57)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_db_wires_0_wget____d57, 1024u);
	backing.DEF_sfFft_outFifo_db_wires_0_wget____d57 = DEF_sfFft_outFifo_db_wires_0_wget____d57;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_db_wires_1_wget____d55) != DEF_sfFft_outFifo_db_wires_1_wget____d55)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_db_wires_1_wget____d55, 1024u);
	backing.DEF_sfFft_outFifo_db_wires_1_wget____d55 = DEF_sfFft_outFifo_db_wires_1_wget____d55;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_va_ehrReg__h98389) != DEF_sfFft_outFifo_va_ehrReg__h98389)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_va_ehrReg__h98389, 1u);
	backing.DEF_sfFft_outFifo_va_ehrReg__h98389 = DEF_sfFft_outFifo_va_ehrReg__h98389;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_va_virtual_reg_1_read____d71) != DEF_sfFft_outFifo_va_virtual_reg_1_read____d71)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_va_virtual_reg_1_read____d71, 1u);
	backing.DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 = DEF_sfFft_outFifo_va_virtual_reg_1_read____d71;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_va_wires_0_wget____d50) != DEF_sfFft_outFifo_va_wires_0_wget____d50)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_va_wires_0_wget____d50, 1u);
	backing.DEF_sfFft_outFifo_va_wires_0_wget____d50 = DEF_sfFft_outFifo_va_wires_0_wget____d50;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_va_wires_0_whas____d49) != DEF_sfFft_outFifo_va_wires_0_whas____d49)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_va_wires_0_whas____d49, 1u);
	backing.DEF_sfFft_outFifo_va_wires_0_whas____d49 = DEF_sfFft_outFifo_va_wires_0_whas____d49;
      }
      ++num;
      if ((backing.DEF_sfFft_outFifo_vb_ehrReg__h124894) != DEF_sfFft_outFifo_vb_ehrReg__h124894)
      {
	vcd_write_val(sim_hdl, num, DEF_sfFft_outFifo_vb_ehrReg__h124894, 1u);
	backing.DEF_sfFft_outFifo_vb_ehrReg__h124894 = DEF_sfFft_outFifo_vb_ehrReg__h124894;
      }
      ++num;
      if ((backing.PORT_deq) != PORT_deq)
      {
	vcd_write_val(sim_hdl, num, PORT_deq, 1024u);
	backing.PORT_deq = PORT_deq;
      }
      ++num;
      if ((backing.PORT_enq_in) != PORT_enq_in)
      {
	vcd_write_val(sim_hdl, num, PORT_enq_in, 1024u);
	backing.PORT_enq_in = PORT_enq_in;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6, 1024u);
      backing.DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6 = DEF_IF_sfFft_inFifo_da_wires_0_whas_THEN_sfFft_inF_ETC___d6;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7, 1024u);
      backing.DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7 = DEF_IF_sfFft_inFifo_da_wires_1_whas_THEN_sfFft_inF_ETC___d7;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39, 1024u);
      backing.DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39 = DEF_IF_sfFft_inFifo_db_virtual_reg_1_read__8_THEN__ETC___d39;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20, 1024u);
      backing.DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20 = DEF_IF_sfFft_inFifo_db_wires_0_whas__7_THEN_sfFft__ETC___d20;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21, 1024u);
      backing.DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21 = DEF_IF_sfFft_inFifo_db_wires_1_whas__5_THEN_sfFft__ETC___d21;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13, 1u);
      backing.DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13 = DEF_IF_sfFft_inFifo_va_wires_0_whas__0_THEN_sfFft__ETC___d13;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27, 1u);
      backing.DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27 = DEF_IF_sfFft_inFifo_vb_wires_0_whas__4_THEN_sfFft__ETC___d27;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45, 1024u);
      backing.DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45 = DEF_IF_sfFft_outFifo_da_wires_0_whas__2_THEN_sfFft_ETC___d45;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46, 1024u);
      backing.DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46 = DEF_IF_sfFft_outFifo_da_wires_1_whas__0_THEN_sfFft_ETC___d46;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78, 1024u);
      backing.DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78 = DEF_IF_sfFft_outFifo_db_virtual_reg_1_read__7_THEN_ETC___d78;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59, 1024u);
      backing.DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59 = DEF_IF_sfFft_outFifo_db_wires_0_whas__6_THEN_sfFft_ETC___d59;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60, 1024u);
      backing.DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60 = DEF_IF_sfFft_outFifo_db_wires_1_whas__4_THEN_sfFft_ETC___d60;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52, 1u);
      backing.DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52 = DEF_IF_sfFft_outFifo_va_wires_0_whas__9_THEN_sfFft_ETC___d52;
      vcd_write_val(sim_hdl, num++, DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66, 1u);
      backing.DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66 = DEF_IF_sfFft_outFifo_vb_wires_0_whas__3_THEN_sfFft_ETC___d66;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_da_ehrReg__h16680, 1024u);
      backing.DEF_sfFft_inFifo_da_ehrReg__h16680 = DEF_sfFft_inFifo_da_ehrReg__h16680;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_da_wires_0_wget____d4, 1024u);
      backing.DEF_sfFft_inFifo_da_wires_0_wget____d4 = DEF_sfFft_inFifo_da_wires_0_wget____d4;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_da_wires_1_wget____d2, 1024u);
      backing.DEF_sfFft_inFifo_da_wires_1_wget____d2 = DEF_sfFft_inFifo_da_wires_1_wget____d2;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_db_ehrReg__h43185, 1024u);
      backing.DEF_sfFft_inFifo_db_ehrReg__h43185 = DEF_sfFft_inFifo_db_ehrReg__h43185;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_db_wires_0_wget____d18, 1024u);
      backing.DEF_sfFft_inFifo_db_wires_0_wget____d18 = DEF_sfFft_inFifo_db_wires_0_wget____d18;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_db_wires_1_wget____d16, 1024u);
      backing.DEF_sfFft_inFifo_db_wires_1_wget____d16 = DEF_sfFft_inFifo_db_wires_1_wget____d16;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_va_ehrReg__h26498, 1u);
      backing.DEF_sfFft_inFifo_va_ehrReg__h26498 = DEF_sfFft_inFifo_va_ehrReg__h26498;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_va_wires_0_wget____d11, 1u);
      backing.DEF_sfFft_inFifo_va_wires_0_wget____d11 = DEF_sfFft_inFifo_va_wires_0_wget____d11;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_va_wires_0_whas____d10, 1u);
      backing.DEF_sfFft_inFifo_va_wires_0_whas____d10 = DEF_sfFft_inFifo_va_wires_0_whas____d10;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_vb_ehrReg__h53003, 1u);
      backing.DEF_sfFft_inFifo_vb_ehrReg__h53003 = DEF_sfFft_inFifo_vb_ehrReg__h53003;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29, 1u);
      backing.DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29 = DEF_sfFft_inFifo_vb_virtual_reg_1_read____d29;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_da_ehrReg__h88571, 1024u);
      backing.DEF_sfFft_outFifo_da_ehrReg__h88571 = DEF_sfFft_outFifo_da_ehrReg__h88571;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_da_wires_0_wget____d43, 1024u);
      backing.DEF_sfFft_outFifo_da_wires_0_wget____d43 = DEF_sfFft_outFifo_da_wires_0_wget____d43;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_da_wires_1_wget____d41, 1024u);
      backing.DEF_sfFft_outFifo_da_wires_1_wget____d41 = DEF_sfFft_outFifo_da_wires_1_wget____d41;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_db_ehrReg__h115076, 1024u);
      backing.DEF_sfFft_outFifo_db_ehrReg__h115076 = DEF_sfFft_outFifo_db_ehrReg__h115076;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_db_wires_0_wget____d57, 1024u);
      backing.DEF_sfFft_outFifo_db_wires_0_wget____d57 = DEF_sfFft_outFifo_db_wires_0_wget____d57;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_db_wires_1_wget____d55, 1024u);
      backing.DEF_sfFft_outFifo_db_wires_1_wget____d55 = DEF_sfFft_outFifo_db_wires_1_wget____d55;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_va_ehrReg__h98389, 1u);
      backing.DEF_sfFft_outFifo_va_ehrReg__h98389 = DEF_sfFft_outFifo_va_ehrReg__h98389;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_va_virtual_reg_1_read____d71, 1u);
      backing.DEF_sfFft_outFifo_va_virtual_reg_1_read____d71 = DEF_sfFft_outFifo_va_virtual_reg_1_read____d71;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_va_wires_0_wget____d50, 1u);
      backing.DEF_sfFft_outFifo_va_wires_0_wget____d50 = DEF_sfFft_outFifo_va_wires_0_wget____d50;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_va_wires_0_whas____d49, 1u);
      backing.DEF_sfFft_outFifo_va_wires_0_whas____d49 = DEF_sfFft_outFifo_va_wires_0_whas____d49;
      vcd_write_val(sim_hdl, num++, DEF_sfFft_outFifo_vb_ehrReg__h124894, 1u);
      backing.DEF_sfFft_outFifo_vb_ehrReg__h124894 = DEF_sfFft_outFifo_vb_ehrReg__h124894;
      vcd_write_val(sim_hdl, num++, PORT_deq, 1024u);
      backing.PORT_deq = PORT_deq;
      vcd_write_val(sim_hdl, num++, PORT_enq_in, 1024u);
      backing.PORT_enq_in = PORT_enq_in;
    }
}

void MOD_mkFftSuperFolded4::vcd_prims(tVCDDumpType dt, MOD_mkFftSuperFolded4 &backing)
{
  INST_sfFft_inFifo_da_ehrReg.dump_VCD(dt, backing.INST_sfFft_inFifo_da_ehrReg);
  INST_sfFft_inFifo_da_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_da_ignored_wires_0);
  INST_sfFft_inFifo_da_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_da_ignored_wires_1);
  INST_sfFft_inFifo_da_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_inFifo_da_virtual_reg_0);
  INST_sfFft_inFifo_da_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_inFifo_da_virtual_reg_1);
  INST_sfFft_inFifo_da_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_da_wires_0);
  INST_sfFft_inFifo_da_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_da_wires_1);
  INST_sfFft_inFifo_db_ehrReg.dump_VCD(dt, backing.INST_sfFft_inFifo_db_ehrReg);
  INST_sfFft_inFifo_db_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_db_ignored_wires_0);
  INST_sfFft_inFifo_db_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_db_ignored_wires_1);
  INST_sfFft_inFifo_db_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_inFifo_db_virtual_reg_0);
  INST_sfFft_inFifo_db_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_inFifo_db_virtual_reg_1);
  INST_sfFft_inFifo_db_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_db_wires_0);
  INST_sfFft_inFifo_db_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_db_wires_1);
  INST_sfFft_inFifo_va_ehrReg.dump_VCD(dt, backing.INST_sfFft_inFifo_va_ehrReg);
  INST_sfFft_inFifo_va_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_va_ignored_wires_0);
  INST_sfFft_inFifo_va_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_va_ignored_wires_1);
  INST_sfFft_inFifo_va_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_inFifo_va_virtual_reg_0);
  INST_sfFft_inFifo_va_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_inFifo_va_virtual_reg_1);
  INST_sfFft_inFifo_va_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_va_wires_0);
  INST_sfFft_inFifo_va_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_va_wires_1);
  INST_sfFft_inFifo_vb_ehrReg.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_ehrReg);
  INST_sfFft_inFifo_vb_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_ignored_wires_0);
  INST_sfFft_inFifo_vb_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_ignored_wires_1);
  INST_sfFft_inFifo_vb_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_virtual_reg_0);
  INST_sfFft_inFifo_vb_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_virtual_reg_1);
  INST_sfFft_inFifo_vb_wires_0.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_wires_0);
  INST_sfFft_inFifo_vb_wires_1.dump_VCD(dt, backing.INST_sfFft_inFifo_vb_wires_1);
  INST_sfFft_outFifo_da_ehrReg.dump_VCD(dt, backing.INST_sfFft_outFifo_da_ehrReg);
  INST_sfFft_outFifo_da_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_da_ignored_wires_0);
  INST_sfFft_outFifo_da_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_da_ignored_wires_1);
  INST_sfFft_outFifo_da_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_outFifo_da_virtual_reg_0);
  INST_sfFft_outFifo_da_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_outFifo_da_virtual_reg_1);
  INST_sfFft_outFifo_da_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_da_wires_0);
  INST_sfFft_outFifo_da_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_da_wires_1);
  INST_sfFft_outFifo_db_ehrReg.dump_VCD(dt, backing.INST_sfFft_outFifo_db_ehrReg);
  INST_sfFft_outFifo_db_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_db_ignored_wires_0);
  INST_sfFft_outFifo_db_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_db_ignored_wires_1);
  INST_sfFft_outFifo_db_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_outFifo_db_virtual_reg_0);
  INST_sfFft_outFifo_db_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_outFifo_db_virtual_reg_1);
  INST_sfFft_outFifo_db_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_db_wires_0);
  INST_sfFft_outFifo_db_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_db_wires_1);
  INST_sfFft_outFifo_va_ehrReg.dump_VCD(dt, backing.INST_sfFft_outFifo_va_ehrReg);
  INST_sfFft_outFifo_va_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_va_ignored_wires_0);
  INST_sfFft_outFifo_va_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_va_ignored_wires_1);
  INST_sfFft_outFifo_va_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_outFifo_va_virtual_reg_0);
  INST_sfFft_outFifo_va_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_outFifo_va_virtual_reg_1);
  INST_sfFft_outFifo_va_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_va_wires_0);
  INST_sfFft_outFifo_va_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_va_wires_1);
  INST_sfFft_outFifo_vb_ehrReg.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_ehrReg);
  INST_sfFft_outFifo_vb_ignored_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_ignored_wires_0);
  INST_sfFft_outFifo_vb_ignored_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_ignored_wires_1);
  INST_sfFft_outFifo_vb_virtual_reg_0.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_virtual_reg_0);
  INST_sfFft_outFifo_vb_virtual_reg_1.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_virtual_reg_1);
  INST_sfFft_outFifo_vb_wires_0.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_wires_0);
  INST_sfFft_outFifo_vb_wires_1.dump_VCD(dt, backing.INST_sfFft_outFifo_vb_wires_1);
}

void MOD_mkFftSuperFolded4::vcd_submodules(tVCDDumpType dt,
					   unsigned int levels,
					   MOD_mkFftSuperFolded4 &backing)
{
  INST_sfFft_bfly_0.dump_VCD(dt, levels, backing.INST_sfFft_bfly_0);
  INST_sfFft_bfly_1.dump_VCD(dt, levels, backing.INST_sfFft_bfly_1);
  INST_sfFft_bfly_2.dump_VCD(dt, levels, backing.INST_sfFft_bfly_2);
  INST_sfFft_bfly_3.dump_VCD(dt, levels, backing.INST_sfFft_bfly_3);
}
