/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Apr  6 17:53:33 CST 2026
 * 
 */

/* Generation options: */
#ifndef __mkFftFolded_h__
#define __mkFftFolded_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftFolded module */
class MOD_mkFftFolded : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0;
  MOD_mkBfly4 INST_bfly_1;
  MOD_mkBfly4 INST_bfly_10;
  MOD_mkBfly4 INST_bfly_11;
  MOD_mkBfly4 INST_bfly_12;
  MOD_mkBfly4 INST_bfly_13;
  MOD_mkBfly4 INST_bfly_14;
  MOD_mkBfly4 INST_bfly_15;
  MOD_mkBfly4 INST_bfly_2;
  MOD_mkBfly4 INST_bfly_3;
  MOD_mkBfly4 INST_bfly_4;
  MOD_mkBfly4 INST_bfly_5;
  MOD_mkBfly4 INST_bfly_6;
  MOD_mkBfly4 INST_bfly_7;
  MOD_mkBfly4 INST_bfly_8;
  MOD_mkBfly4 INST_bfly_9;
  MOD_Reg<tUWide> INST_inFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_da_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_wires_1;
  MOD_Reg<tUWide> INST_inFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_db_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_1;
  MOD_Reg<tUWide> INST_outFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_da_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_wires_1;
  MOD_Reg<tUWide> INST_outFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_db_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_1;
  MOD_Reg<tUInt8> INST_stage;
  MOD_Reg<tUWide> INST_stage_data;
 
 /* Constructor */
 public:
  MOD_mkFftFolded(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_inFifo_vb_virtual_reg_1_read____d29;
  tUInt8 DEF_outFifo_va_virtual_reg_1_read____d71;
  tUInt8 DEF_inFifo_va_virtual_reg_1_read____d32;
  tUInt8 DEF_x__h244304;
  tUInt8 DEF_outFifo_va_ehrReg__h98384;
  tUInt8 DEF_inFifo_vb_ehrReg__h52999;
  tUInt8 DEF_inFifo_va_ehrReg__h26494;
 
 /* Local definitions */
 private:
  tUInt8 DEF_outFifo_vb_virtual_reg_1_read____d68;
  tUWide DEF_outFifo_db_wires_1_wget____d55;
  tUWide DEF_outFifo_db_wires_0_wget____d57;
  tUWide DEF_outFifo_db_ehrReg__h115071;
  tUWide DEF_outFifo_da_wires_1_wget____d41;
  tUWide DEF_outFifo_da_wires_0_wget____d43;
  tUWide DEF_outFifo_da_ehrReg__h88566;
  tUWide DEF_inFifo_db_wires_1_wget____d16;
  tUWide DEF_inFifo_db_wires_0_wget____d18;
  tUWide DEF_inFifo_db_ehrReg__h43181;
  tUWide DEF_inFifo_da_wires_1_wget____d2;
  tUWide DEF_inFifo_da_wires_0_wget____d4;
  tUWide DEF_inFifo_da_ehrReg__h16676;
  tUWide DEF_stage_data__h230736;
  tUInt8 DEF_outFifo_vb_ehrReg__h124889;
  tUInt8 DEF_outFifo_va_wires_0_whas____d49;
  tUInt8 DEF_outFifo_va_wires_0_wget____d50;
  tUInt8 DEF_inFifo_va_wires_0_whas____d10;
  tUInt8 DEF_inFifo_va_wires_0_wget____d11;
  tUWide DEF_IF_outFifo_db_virtual_reg_1_read__7_THEN_0_ELS_ETC___d78;
  tUWide DEF_IF_outFifo_db_wires_0_whas__6_THEN_outFifo_db__ETC___d59;
  tUWide DEF_IF_outFifo_db_wires_1_whas__4_THEN_outFifo_db__ETC___d60;
  tUWide DEF_IF_outFifo_da_wires_1_whas__0_THEN_outFifo_da__ETC___d46;
  tUWide DEF_IF_outFifo_da_wires_0_whas__2_THEN_outFifo_da__ETC___d45;
  tUWide DEF_IF_inFifo_db_virtual_reg_1_read__8_THEN_0_ELSE_ETC___d39;
  tUWide DEF_IF_inFifo_db_wires_0_whas__7_THEN_inFifo_db_wi_ETC___d20;
  tUWide DEF_IF_inFifo_db_wires_1_whas__5_THEN_inFifo_db_wi_ETC___d21;
  tUWide DEF_IF_inFifo_da_wires_0_whas_THEN_inFifo_da_wires_ETC___d6;
  tUWide DEF_IF_inFifo_da_wires_1_whas_THEN_inFifo_da_wires_ETC___d7;
  tUInt8 DEF_IF_outFifo_vb_wires_0_whas__3_THEN_outFifo_vb__ETC___d66;
  tUInt8 DEF_IF_outFifo_va_wires_0_whas__9_THEN_outFifo_va__ETC___d52;
  tUInt8 DEF_IF_inFifo_vb_wires_0_whas__4_THEN_inFifo_vb_wi_ETC___d27;
  tUInt8 DEF_IF_inFifo_va_wires_0_whas__0_THEN_inFifo_va_wi_ETC___d13;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d233;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d230;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d549;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d546;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d227;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d543;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d224;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d540;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d221;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d537;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d218;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d534;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d215;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d531;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d212;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d528;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d209;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d525;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d206;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d522;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d203;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d519;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d200;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d516;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d197;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d513;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d194;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d510;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d191;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d507;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d188;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d504;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d185;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d501;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d179;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d485;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d173;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d469;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d167;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d453;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d161;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d437;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d155;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d421;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d149;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d405;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d143;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d389;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d137;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d373;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d131;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d357;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d125;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d341;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d119;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d325;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d113;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d309;
  tUWide DEF_bfly_15_bfly4_2251552690364292668_IF_inFifo_da_ETC___d107;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_stage_4__ETC___d293;
 
 /* Rules */
 public:
  void RL_inFifo_da_canonicalize();
  void RL_inFifo_va_canonicalize();
  void RL_inFifo_db_canonicalize();
  void RL_inFifo_vb_canonicalize();
  void RL_inFifo_canonicalize();
  void RL_outFifo_da_canonicalize();
  void RL_outFifo_va_canonicalize();
  void RL_outFifo_db_canonicalize();
  void RL_outFifo_vb_canonicalize();
  void RL_outFifo_canonicalize();
  void RL_doFftStage0();
  void RL_doFftOther();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftFolded &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftFolded &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftFolded &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftFolded &backing);
};

#endif /* ifndef __mkFftFolded_h__ */
