/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Mar 21 18:43:54 CST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbCSASimple.h"


/* String declarations */
static std::string const __str_literal_2("%d + %d = %d", 12u);
static std::string const __str_literal_3("FAILED %d + %d gave %d instead of %d", 36u);
static std::string const __str_literal_1("PASSED", 6u);


/* Constructor */
MOD_mkTbCSASimple::MOD_mkTbCSASimple(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 2u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbCSASimple::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_test", SYM_RULE);
}


/* Rule actions */

void MOD_mkTbCSASimple::RL_test()
{
  tUInt8 DEF_upper_result__h183;
  tUInt32 DEF_x__h4178;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d18;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d14;
  tUInt8 DEF_a__h188;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d10;
  tUInt8 DEF_b__h189;
  tUInt8 DEF_out_and_1__h192;
  tUInt8 DEF_out_and_0__h191;
  tUInt8 DEF_cout__h182;
  tUInt8 DEF_out_and_1__h3726;
  tUInt8 DEF_out_and_0__h3725;
  tUInt8 DEF_out_and_1__h3830;
  tUInt8 DEF_out_and_0__h3829;
  tUInt8 DEF_out_and_1__h3877;
  tUInt8 DEF_out_and_0__h3876;
  tUInt8 DEF_out_and_1__h3924;
  tUInt8 DEF_out_and_0__h3923;
  tUInt8 DEF_a__h3873;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19;
  tUInt8 DEF_b__h3874;
  tUInt8 DEF_c_in__h1246;
  tUInt8 DEF_a__h3826;
  tUInt8 DEF_c_in__h3107;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15;
  tUInt8 DEF_b__h3827;
  tUInt8 DEF_c_in__h1344;
  tUInt8 DEF_a__h3722;
  tUInt8 DEF_c_in__h3205;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11;
  tUInt8 DEF_b__h3723;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_1_ETC___d42;
  tUInt8 DEF_c_in__h2176;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_2_ETC___d38;
  tUInt8 DEF_c_in__h2274;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_3_ETC___d34;
  tUInt8 DEF_a__h3920;
  tUInt8 DEF_b__h3921;
  tUInt8 DEF_sel__h3624;
  tUInt8 DEF_sel_not__h3724;
  tUInt8 DEF_NOT_cycle_EQ_8_AND_SEL_ARR_1_8_63_102_177_128__ETC___d100;
  tUInt8 DEF_NOT_cycle_EQ_8___d3;
  tUInt8 DEF_NOT_cycle_EQ_8_AND_NOT_SEL_ARR_1_8_63_102_177__ETC___d102;
  tUInt32 DEF_realAns__h3993;
  tUInt32 DEF_v__h175;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d99;
  tUInt8 DEF_cycle_EQ_8___d2;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4_ETC___d22;
  tUInt8 DEF_c_in__h2077;
  tUInt8 DEF_c_in__h1147;
  tUInt8 DEF_c_in__h3008;
  tUInt8 DEF_b__h1943;
  tUInt8 DEF_b__h2076;
  tUInt8 DEF_b__h2175;
  tUInt8 DEF_b__h2273;
  tUInt8 DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle_BIT_4___d21;
  tUInt8 DEF_b__h1146;
  tUInt8 DEF_b__h1245;
  tUInt8 DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8;
  tUInt8 DEF_b__h1343;
  tUInt8 DEF_a__h1942;
  tUInt8 DEF_a__h2075;
  tUInt8 DEF_a__h2174;
  tUInt8 DEF_a__h2272;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4___d20;
  tUInt8 DEF_a__h1145;
  tUInt8 DEF_a__h1244;
  tUInt8 DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5;
  tUInt8 DEF_a__h1342;
  tUInt32 DEF_x__h786;
  DEF_x__h786 = INST_cycle.METH_read();
  switch (DEF_x__h786) {
  case 0u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)1u;
    break;
  case 1u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)8u;
    break;
  case 2u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)63u;
    break;
  case 3u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)102u;
    break;
  case 4u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)177u;
    break;
  case 5u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)128u;
    break;
  case 6u:
  case 7u:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)255u;
    break;
  default:
    DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 = (tUInt8)170u;
  }
  DEF_a__h1342 = (tUInt8)(DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 7u);
  DEF_a__h1244 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 6u));
  DEF_a__h1145 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 5u));
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4___d20 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 4u));
  DEF_a__h2272 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 3u));
  DEF_a__h2174 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 2u));
  DEF_a__h2075 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5 >> 1u));
  DEF_a__h1942 = (tUInt8)((tUInt8)1u & DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5);
  switch (DEF_x__h786) {
  case 0u:
  case 6u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)1u;
    break;
  case 1u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)8u;
    break;
  case 2u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)27u;
    break;
  case 3u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)92u;
    break;
  case 4u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)202u;
    break;
  case 5u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)128u;
    break;
  case 7u:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)255u;
    break;
  default:
    DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 = (tUInt8)170u;
  }
  DEF_b__h1343 = (tUInt8)(DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 7u);
  DEF_b__h1245 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 6u));
  DEF_b__h1146 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 5u));
  DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle_BIT_4___d21 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 4u));
  DEF_b__h2273 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 3u));
  DEF_b__h2175 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 2u));
  DEF_b__h2076 = (tUInt8)((tUInt8)1u & (DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8 >> 1u));
  DEF_b__h1943 = (tUInt8)((tUInt8)1u & DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8);
  DEF_c_in__h2077 = (tUInt8)((tUInt8)1u & ((DEF_a__h1942 & DEF_b__h1943 ? (tUInt8)2u : (tUInt8)0u) >> 1u));
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4_ETC___d22 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4___d20 & DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle_BIT_4___d21;
  DEF_c_in__h1147 = (tUInt8)((tUInt8)1u & ((DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4_ETC___d22 ? (tUInt8)2u : (tUInt8)0u) >> 1u));
  DEF_cycle_EQ_8___d2 = DEF_x__h786 == 8u;
  DEF_realAns__h3993 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8))));
  DEF_NOT_cycle_EQ_8___d3 = !DEF_cycle_EQ_8___d2;
  DEF_a__h3920 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4___d20 ^ DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle_BIT_4___d21;
  DEF_c_in__h3008 = (tUInt8)((tUInt8)1u & ((DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_4_ETC___d22 | DEF_a__h3920 ? (tUInt8)3u : (tUInt8)1u) >> 1u));
  DEF_b__h3921 = (tUInt8)1u & ~DEF_a__h3920;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_3_ETC___d34 = DEF_a__h2272 ^ DEF_b__h2273;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_2_ETC___d38 = DEF_a__h2174 ^ DEF_b__h2175;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_1_ETC___d42 = DEF_a__h2075 ^ DEF_b__h2076;
  DEF_c_in__h2176 = (DEF_a__h2075 & DEF_b__h2076) | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_1_ETC___d42 & DEF_c_in__h2077);
  DEF_c_in__h2274 = (DEF_a__h2174 & DEF_b__h2175) | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_2_ETC___d38 & DEF_c_in__h2176);
  DEF_sel__h3624 = (DEF_a__h2272 & DEF_b__h2273) | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_3_ETC___d34 & DEF_c_in__h2274);
  DEF_sel_not__h3724 = (tUInt8)1u & ~DEF_sel__h3624;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11 = DEF_a__h1342 ^ DEF_b__h1343;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15 = DEF_a__h1244 ^ DEF_b__h1245;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19 = DEF_a__h1145 ^ DEF_b__h1146;
  DEF_b__h3874 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19 ^ DEF_c_in__h3008;
  DEF_a__h3873 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19 ^ DEF_c_in__h1147;
  DEF_out_and_0__h3923 = DEF_a__h3920 & DEF_sel_not__h3724;
  DEF_out_and_1__h3924 = DEF_b__h3921 & DEF_sel__h3624;
  DEF_out_and_0__h3876 = DEF_a__h3873 & DEF_sel_not__h3724;
  DEF_out_and_1__h3877 = DEF_b__h3874 & DEF_sel__h3624;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d10 = DEF_a__h1342 & DEF_b__h1343;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d14 = DEF_a__h1244 & DEF_b__h1245;
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d18 = DEF_a__h1145 & DEF_b__h1146;
  DEF_c_in__h3107 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d18 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19 & DEF_c_in__h3008);
  DEF_c_in__h3205 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d14 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15 & DEF_c_in__h3107);
  DEF_b__h3723 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11 ^ DEF_c_in__h3205;
  DEF_b__h3827 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15 ^ DEF_c_in__h3107;
  DEF_c_in__h1246 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d18 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_5_ETC___d19 & DEF_c_in__h1147);
  DEF_c_in__h1344 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d14 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15 & DEF_c_in__h1246);
  DEF_a__h3722 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11 ^ DEF_c_in__h1344;
  DEF_a__h3826 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_6_ETC___d15 ^ DEF_c_in__h1246;
  DEF_out_and_0__h3829 = DEF_a__h3826 & DEF_sel_not__h3724;
  DEF_out_and_1__h3830 = DEF_b__h3827 & DEF_sel__h3624;
  DEF_out_and_0__h3725 = DEF_a__h3722 & DEF_sel_not__h3724;
  DEF_out_and_1__h3726 = DEF_b__h3723 & DEF_sel__h3624;
  DEF_b__h189 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d10 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11 & DEF_c_in__h3205);
  DEF_out_and_1__h192 = DEF_b__h189 & DEF_sel__h3624;
  DEF_a__h188 = DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d10 | (DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d11 & DEF_c_in__h1344);
  DEF_out_and_0__h191 = DEF_a__h188 & DEF_sel_not__h3724;
  DEF_cout__h182 = DEF_out_and_0__h191 | DEF_out_and_1__h192;
  DEF_x__h4178 = DEF_x__h786 + 1u;
  DEF_upper_result__h183 = (tUInt8)15u & (((((DEF_out_and_0__h3725 | DEF_out_and_1__h3726) << 3u) | ((DEF_out_and_0__h3829 | DEF_out_and_1__h3830) << 2u)) | ((DEF_out_and_0__h3876 | DEF_out_and_1__h3877) << 1u)) | (DEF_out_and_0__h3923 | DEF_out_and_1__h3924));
  DEF_v__h175 = 511u & ((((((((tUInt32)(DEF_cout__h182)) << 8u) | (((tUInt32)(DEF_upper_result__h183)) << 4u)) | (((tUInt32)(DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_3_ETC___d34 ^ DEF_c_in__h2274)) << 3u)) | (((tUInt32)(DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_2_ETC___d38 ^ DEF_c_in__h2176)) << 2u)) | (((tUInt32)(DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_1_ETC___d42 ^ DEF_c_in__h2077)) << 1u)) | (tUInt32)(DEF_a__h1942 ^ DEF_b__h1943));
  DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d99 = DEF_v__h175 == DEF_realAns__h3993;
  DEF_NOT_cycle_EQ_8_AND_NOT_SEL_ARR_1_8_63_102_177__ETC___d102 = DEF_NOT_cycle_EQ_8___d3 && !DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d99;
  DEF_NOT_cycle_EQ_8_AND_SEL_ARR_1_8_63_102_177_128__ETC___d100 = DEF_NOT_cycle_EQ_8___d3 && DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle_BIT_7_ETC___d99;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_EQ_8___d2)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_EQ_8___d2)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_EQ_8_AND_SEL_ARR_1_8_63_102_177_128__ETC___d100)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9",
		     &__str_literal_2,
		     DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5,
		     DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8,
		     DEF_v__h175);
    if (DEF_NOT_cycle_EQ_8_AND_NOT_SEL_ARR_1_8_63_102_177__ETC___d102)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9,9",
		     &__str_literal_3,
		     DEF_SEL_ARR_1_8_63_102_177_128_255_255_cycle___d5,
		     DEF_SEL_ARR_1_8_27_92_202_128_1_255_cycle___d8,
		     DEF_v__h175,
		     DEF_realAns__h3993);
    if (DEF_NOT_cycle_EQ_8_AND_NOT_SEL_ARR_1_8_63_102_177__ETC___d102)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h4178);
}


/* Methods */


/* Reset routines */

void MOD_mkTbCSASimple::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbCSASimple::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbCSASimple::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbCSASimple::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 2u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  num = INST_cycle.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbCSASimple::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCSASimple &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbCSASimple::vcd_defs(tVCDDumpType dt, MOD_mkTbCSASimple &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}

void MOD_mkTbCSASimple::vcd_prims(tVCDDumpType dt, MOD_mkTbCSASimple &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}
